# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python -m loom.gen.builders

from __future__ import annotations

from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Predicate, Region, Type


class TestBuilders:
    """Typed builder methods for test ops."""

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def addi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Test binary integer op.

        Example::
            %result = test.addi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("test.addi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def neg(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Test unary float op.

        Example::
            %result = test.neg %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("test.neg", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Test cast op.

        Example::
            %result = test.cast %input : i32 to f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("test.cast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def constant(self, *, value: Any, result_types: list[Type]) -> ValueRef:
        """Test constant materialization.

        Example::
            %c42 = test.constant 42 : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("test.constant", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def use(self, *, values: list[ValueRef]) -> None:
        """Side-effecting sink that observes values without producing results. Not DCE-able. Use in tests to keep values alive for inspection.

        Example::
            test.use %a : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(values)
        self._b.build("test.use", _operands, attributes=_attributes, regions=_regions)

    def cmp(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Test comparison op.

        Example::
            %result = test.cmp lt, %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("test.cmp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def map(self, *, inputs: list[ValueRef], body: Region | None = None, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test region-capture elementwise op.

        Example::
            %result = test.map(%element = %input : tile<4xf32>) {
              %negated = test.neg %element : f32
              test.yield %negated : f32
            } -> (tile<4xf32>)
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(inputs)
        if body is not None:
            _regions.append(body)
        return cast(ValueRef, self._b.build("test.map", _operands, results=results, attributes=_attributes, regions=_regions))

    def update(self, *, source: ValueRef, target: ValueRef, offsets: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test tied result with index list.

        Example::
            %result = test.update %tile, %tensor[%offset] : tile<4xf32> -> (%tensor as tensor<[%M]xf32>)
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _operands.append(target)
        _sentinel = -(2**63)
        _static = []
        for _idx in offsets:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_offsets"] = _static
        return cast(ValueRef, self._b.build("test.update", _operands, results=results, attributes=_attributes, regions=_regions))

    def invoke(self, *, callee: str, operands: list[ValueRef], results: list[Type | TiedResultSpec]) -> list[ValueRef]:
        """Test variadic call-like op with tied results.

        Example::
            %output, %count = test.invoke @callee(%weights, %input) : (tile<4xf32>, index) -> (%weights as tile<4xf32>, index)
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["callee"] = callee
        _operands.extend(operands)
        return cast(list[ValueRef], self._b.build("test.invoke", _operands, results=results, attributes=_attributes, regions=_regions))

    def slice(self, *, source: ValueRef, offsets: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test index list with mixed static/dynamic offsets.

        Example::
            %subtile = test.slice %source[0, %offset] : tile<64x64xf16> -> (tile<16x16xf16>)
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _sentinel = -(2**63)
        _static = []
        for _idx in offsets:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_offsets"] = _static
        return cast(ValueRef, self._b.build("test.slice", _operands, results=results, attributes=_attributes, regions=_regions))

    def loop(self, *, lower_bound: ValueRef, upper_bound: ValueRef, step: ValueRef, iter_args: list[ValueRef], results: list[Type | TiedResultSpec], body: Region | None = None) -> list[ValueRef]:
        """Test for-loop with iter_args and tied results.

        Example::
            %result = test.loop %i = %c0 to %count step %c1 iter_args(%accumulator = %init : f32) -> (%init as f32) {
              %next = test.neg %accumulator : f32
              test.yield %next : f32
            }
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lower_bound)
        _operands.append(upper_bound)
        _operands.append(step)
        _operands.extend(iter_args)
        if body is not None:
            _regions.append(body)
        return cast(list[ValueRef], self._b.build("test.loop", _operands, results=results, attributes=_attributes, regions=_regions))

    def branch(self, *, condition: ValueRef, results: list[Type | TiedResultSpec], then_region: Region | None = None, else_region: Region | None = None) -> list[ValueRef]:
        """Test if/else with both regions always present.

        Example::
            %result = test.branch %condition -> (f32) {
              test.yield %true_value : f32
            } else {
              test.yield %false_value : f32
            }
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(condition)
        if then_region is not None:
            _regions.append(then_region)
        if else_region is not None:
            _regions.append(else_region)
        return cast(list[ValueRef], self._b.build("test.branch", _operands, results=results, attributes=_attributes, regions=_regions))

    def yield_(self, *, values: list[ValueRef]) -> None:
        """Test yield terminator.

        Example::
            test.yield
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(values)
        self._b.build("test.yield", _operands, attributes=_attributes, regions=_regions)

    def func(
        self, *, visibility: str | None = None, cc: str | None = None, callee: str, results: list[Type | TiedResultSpec], predicates: list[Predicate] | None = None, body: Region | None = None
    ) -> list[ValueRef]:
        """Test function definition with body always present.

        Example::
            test.func @identity(%input: f32) -> (f32) {
              test.yield %input : f32
            }
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        if visibility is not None:
            _attributes["visibility"] = visibility
        if cc is not None:
            _attributes["cc"] = cc
        _attributes["callee"] = callee
        if predicates:
            _attributes["predicates"] = predicates
        if body is not None:
            _regions.append(body)
        return cast(list[ValueRef], self._b.build("test.func", _operands, results=results, attributes=_attributes, regions=_regions))

    def attrs(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Test op with attribute dictionary.

        Example::
            %result = test.attrs %input {axis = 0, label = "foo"} : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("test.attrs", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def deflate(self, *, input: ValueRef, results: list[Type | TiedResultSpec]) -> list[ValueRef]:
        """Test op with result type referencing a co-result dim.

        Example::
            %output, %length = test.deflate %input : tensor<[%M]xf32> -> (tensor<[%length]xf32>, index)
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(list[ValueRef], self._b.build("test.deflate", _operands, results=results, attributes=_attributes, regions=_regions))

    def assume(self, *, values: list[ValueRef], predicates: list[Predicate], result_types: list[Type]) -> list[ValueRef]:
        """Test predicate-constrained identity (SSA assume).

        Example::
            %M2 = test.assume %M [mul(%M, 16)] : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(values)
        _attributes["predicates"] = predicates
        return cast(list[ValueRef], self._b.build("test.assume", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def convert(self, *, input: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test op with bare result type (no parentheses).

        Example::
            %result = test.convert %input : i32 -> f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("test.convert", _operands, results=results, attributes=_attributes, regions=_regions))

    def reduce(self, *, inputs: list[ValueRef], result_types: list[Type]) -> ValueRef:
        """Test variadic operands with SameType constraint across variadic and result.

        Example::
            %sum = test.reduce %a, %b, %c : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(inputs)
        return cast(ValueRef, self._b.build("test.reduce", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def read_resource(self, *, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test op that reads from a resource operand.

        Example::
            %tile = test.read_resource %pool : pool<[%BS]> -> tile<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        return cast(ValueRef, self._b.build("test.read_resource", _operands, results=results, attributes=_attributes, regions=_regions))

    def write_resource(self, *, target: ValueRef, data: ValueRef) -> None:
        """Test op that writes to a resource operand.

        Example::
            test.write_resource %pool, %tile : pool<[%BS]>, tile<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(target)
        _operands.append(data)
        self._b.build("test.write_resource", _operands, attributes=_attributes, regions=_regions)

    def mutate_resource(self, *, target: ValueRef, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test op that atomically reads and writes a resource operand.

        Example::
            %old = test.mutate_resource %pool, %delta : pool<[%BS]>, i32 -> i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(target)
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.mutate_resource", _operands, results=results, attributes=_attributes, regions=_regions))

    def alloc(self, *, size: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test allocation op. Each execution produces a distinct identity even with identical operands. Prevents CSE but allows DCE when unused.

        Example::
            %pool = test.alloc %sz : index -> pool<[%BS]>
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(size)
        return cast(ValueRef, self._b.build("test.alloc", _operands, results=results, attributes=_attributes, regions=_regions))

    def isolated_region(self, *, results: list[Type | TiedResultSpec], body: Region | None = None) -> list[ValueRef]:
        """Test op with an isolated single-block region. Values from the enclosing scope are not visible inside the body.

        Example::
            %r = test.isolated_region -> (i32) {
              %c = test.constant 42 : i32
              test.yield %c : i32
            }
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        if body is not None:
            _regions.append(body)
        return cast(list[ValueRef], self._b.build("test.isolated_region", _operands, results=results, attributes=_attributes, regions=_regions))

    def counter(self, *, value: int, result_types: list[Type]) -> ValueRef:
        """Test op for canonicalize multi-step and error path testing. Canonicalize: value < 0 returns error, value > 0 decrements, value == 0 is fixed point.

        Example::
            %c = test.counter 3 : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("test.counter", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def dim(self, *, source: ValueRef, dim_index: int, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Test dimension query to exercise ATTR_IN_RANGE_RANK constraint.

        Example::
            %d = test.dim %t[0] : tile<4xf32> -> index
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _attributes["dim_index"] = dim_index
        return cast(ValueRef, self._b.build("test.dim", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_range_lo(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Exposes the analysis range lower bound as an i64 constant.

        Example::
            %lo = test.fact_range_lo %x : index -> i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_range_lo", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_range_hi(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Exposes the analysis range upper bound as an i64 constant.

        Example::
            %hi = test.fact_range_hi %x : index -> i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_range_hi", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_divisor(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Exposes the analysis known divisor as an i64 constant.

        Example::
            %div = test.fact_divisor %x : index -> i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_divisor", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_non_negative(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Returns 1 if the input is provably non-negative, 0 otherwise.

        Example::
            %nn = test.fact_non_negative %x : index -> i1
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_non_negative", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_non_zero(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Returns 1 if the input is provably non-zero, 0 otherwise.

        Example::
            %nz = test.fact_non_zero %x : index -> i1
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_non_zero", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_positive(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Returns 1 if the input is provably positive (> 0), 0 otherwise.

        Example::
            %pos = test.fact_positive %x : index -> i1
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_positive", _operands, results=results, attributes=_attributes, regions=_regions))

    def fact_power_of_two(self, *, value: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Returns 1 if the input is provably a power of two, 0 otherwise.

        Example::
            %p2 = test.fact_power_of_two %x : index -> i1
        """
        _operands: list[ValueRef | int] = []
        _attributes: dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        return cast(ValueRef, self._b.build("test.fact_power_of_two", _operands, results=results, attributes=_attributes, regions=_regions))
