// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: cd runtime/py && PYTHONPATH=. python3 -m loom.gen.c_tables
// clang-format off

#ifndef LOOM_OPS_TEST_OPS_H_
#define LOOM_OPS_TEST_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_TEST_ADDI = LOOM_OP_KIND(LOOM_DIALECT_TEST, 0),
  LOOM_OP_TEST_NEG = LOOM_OP_KIND(LOOM_DIALECT_TEST, 1),
  LOOM_OP_TEST_CAST = LOOM_OP_KIND(LOOM_DIALECT_TEST, 2),
  LOOM_OP_TEST_CONSTANT = LOOM_OP_KIND(LOOM_DIALECT_TEST, 3),
  LOOM_OP_TEST_USE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 4),
  LOOM_OP_TEST_CMP = LOOM_OP_KIND(LOOM_DIALECT_TEST, 5),
  LOOM_OP_TEST_MAP = LOOM_OP_KIND(LOOM_DIALECT_TEST, 6),
  LOOM_OP_TEST_UPDATE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 7),
  LOOM_OP_TEST_INVOKE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 8),
  LOOM_OP_TEST_SLICE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 9),
  LOOM_OP_TEST_LOOP = LOOM_OP_KIND(LOOM_DIALECT_TEST, 10),
  LOOM_OP_TEST_BRANCH = LOOM_OP_KIND(LOOM_DIALECT_TEST, 11),
  LOOM_OP_TEST_YIELD = LOOM_OP_KIND(LOOM_DIALECT_TEST, 12),
  LOOM_OP_TEST_FUNC = LOOM_OP_KIND(LOOM_DIALECT_TEST, 13),
  LOOM_OP_TEST_ATTRS = LOOM_OP_KIND(LOOM_DIALECT_TEST, 14),
  LOOM_OP_TEST_DEFLATE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 15),
  LOOM_OP_TEST_ASSUME = LOOM_OP_KIND(LOOM_DIALECT_TEST, 16),
  LOOM_OP_TEST_CONVERT = LOOM_OP_KIND(LOOM_DIALECT_TEST, 17),
  LOOM_OP_TEST_REDUCE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 18),
  LOOM_OP_TEST_READ_RESOURCE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 19),
  LOOM_OP_TEST_WRITE_RESOURCE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 20),
  LOOM_OP_TEST_MUTATE_RESOURCE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 21),
  LOOM_OP_TEST_ALLOC = LOOM_OP_KIND(LOOM_DIALECT_TEST, 22),
  LOOM_OP_TEST_ISOLATED_REGION = LOOM_OP_KIND(LOOM_DIALECT_TEST, 23),
  LOOM_OP_TEST_COUNTER = LOOM_OP_KIND(LOOM_DIALECT_TEST, 24),
  LOOM_OP_TEST_DIM = LOOM_OP_KIND(LOOM_DIALECT_TEST, 25),
  LOOM_OP_TEST_FACT_RANGE_LO = LOOM_OP_KIND(LOOM_DIALECT_TEST, 26),
  LOOM_OP_TEST_FACT_RANGE_HI = LOOM_OP_KIND(LOOM_DIALECT_TEST, 27),
  LOOM_OP_TEST_FACT_DIVISOR = LOOM_OP_KIND(LOOM_DIALECT_TEST, 28),
  LOOM_OP_TEST_FACT_NON_NEGATIVE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 29),
  LOOM_OP_TEST_FACT_NON_ZERO = LOOM_OP_KIND(LOOM_DIALECT_TEST, 30),
  LOOM_OP_TEST_FACT_POSITIVE = LOOM_OP_KIND(LOOM_DIALECT_TEST, 31),
  LOOM_OP_TEST_FACT_POWER_OF_TWO = LOOM_OP_KIND(LOOM_DIALECT_TEST, 32),
  LOOM_OP_TEST_COUNT_ = 33,
};

typedef enum loom_test_cmp_predicate_e {
  LOOM_TEST_CMP_PREDICATE_EQ = 0,
  LOOM_TEST_CMP_PREDICATE_NE = 1,
  LOOM_TEST_CMP_PREDICATE_LT = 2,
  LOOM_TEST_CMP_PREDICATE_LE = 3,
  LOOM_TEST_CMP_PREDICATE_GT = 4,
  LOOM_TEST_CMP_PREDICATE_GE = 5,
  LOOM_TEST_CMP_PREDICATE_COUNT_ = 6,
} loom_test_cmp_predicate_t;

// Function visibility. Absent (0) means private.
typedef enum loom_test_func_visibility_e {
  LOOM_TEST_FUNC_VISIBILITY_PUBLIC = 1,
  LOOM_TEST_FUNC_VISIBILITY_COUNT_ = 2,
} loom_test_func_visibility_t;

// Function calling convention. Absent (0) means host.
typedef enum loom_test_func_cc_e {
  LOOM_TEST_FUNC_CC_HOST = 1,
  LOOM_TEST_FUNC_CC_DEVICE = 2,
  LOOM_TEST_FUNC_CC_INITIALIZER = 3,
  LOOM_TEST_FUNC_CC_DEINITIALIZER = 4,
  LOOM_TEST_FUNC_CC_COUNT_ = 5,
} loom_test_func_cc_t;

// LOOM_OP_TEST_ADDI: Test binary integer op.
// %result = test.addi %lhs, %rhs : i32
LOOM_DEFINE_ISA(loom_test_addi_isa, LOOM_OP_TEST_ADDI)
LOOM_DEFINE_OPERAND(loom_test_addi_lhs, 0)
LOOM_DEFINE_OPERAND(loom_test_addi_rhs, 1)
LOOM_DEFINE_RESULT(loom_test_addi_result, 0)
iree_status_t loom_test_addi_build(
    loom_builder_t* builder, loom_value_id_t lhs,
    loom_value_id_t rhs, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_addi_vtable;
iree_status_t loom_test_addi_canonicalize(loom_op_t* op, loom_rewriter_t* rewriter);
void loom_test_addi_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_NEG: Test unary float op.
// %result = test.neg %input : f32
LOOM_DEFINE_ISA(loom_test_neg_isa, LOOM_OP_TEST_NEG)
LOOM_DEFINE_OPERAND(loom_test_neg_input, 0)
LOOM_DEFINE_RESULT(loom_test_neg_result, 0)
iree_status_t loom_test_neg_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_neg_vtable;

// LOOM_OP_TEST_CAST: Test cast op.
// %result = test.cast %input : i32 to f32
LOOM_DEFINE_ISA(loom_test_cast_isa, LOOM_OP_TEST_CAST)
LOOM_DEFINE_OPERAND(loom_test_cast_input, 0)
LOOM_DEFINE_RESULT(loom_test_cast_result, 0)
iree_status_t loom_test_cast_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_cast_vtable;

// LOOM_OP_TEST_CONSTANT: Test constant materialization.
// %c42 = test.constant 42 : i32
LOOM_DEFINE_ISA(loom_test_constant_isa, LOOM_OP_TEST_CONSTANT)
LOOM_DEFINE_RESULT(loom_test_constant_result, 0)
iree_status_t loom_test_constant_build(
    loom_builder_t* builder,
    loom_attribute_t value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_constant_vtable;
void loom_test_constant_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_USE: Side-effecting sink that observes values without producing results. Not DCE-able. Use in tests to keep values alive for inspection.
// test.use %a : i32
LOOM_DEFINE_ISA(loom_test_use_isa, LOOM_OP_TEST_USE)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_use_values, 0)
iree_status_t loom_test_use_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_use_vtable;

// LOOM_OP_TEST_CMP: Test comparison op.
// %result = test.cmp lt, %lhs, %rhs : i32
LOOM_DEFINE_ISA(loom_test_cmp_isa, LOOM_OP_TEST_CMP)
LOOM_DEFINE_OPERAND(loom_test_cmp_lhs, 0)
LOOM_DEFINE_OPERAND(loom_test_cmp_rhs, 1)
LOOM_DEFINE_RESULT(loom_test_cmp_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_test_cmp_predicate, 0)
iree_status_t loom_test_cmp_build(
    loom_builder_t* builder, uint8_t predicate,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t operand_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_cmp_vtable;

// LOOM_OP_TEST_MAP: Test region-capture elementwise op.
// %result = test.map(%element = %input : tile<4xf32>) {
LOOM_DEFINE_ISA(loom_test_map_isa, LOOM_OP_TEST_MAP)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_map_inputs, 0)
LOOM_DEFINE_RESULT(loom_test_map_result, 0)
LOOM_DEFINE_REGION(loom_test_map_body, 0)
iree_status_t loom_test_map_build(
    loom_builder_t* builder,
    loom_may_consume const loom_value_id_t* inputs,
    iree_host_size_t inputs_count,
    loom_type_t result_type,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_map_vtable;

// LOOM_OP_TEST_UPDATE: Test tied result with index list.
// %result = test.update %tile, %tensor[%offset] : tile<4xf32> -> (%tensor as tensor<[%M]xf32>)
LOOM_DEFINE_ISA(loom_test_update_isa, LOOM_OP_TEST_UPDATE)
LOOM_DEFINE_OPERAND(loom_test_update_source, 0)
LOOM_DEFINE_OPERAND(loom_test_update_target, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_update_offsets, 2)
LOOM_DEFINE_RESULT(loom_test_update_result, 0)
iree_status_t loom_test_update_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    loom_may_consume loom_value_id_t target,
    const loom_value_id_t* offsets,
    iree_host_size_t offsets_count,
    const int64_t* static_offsets,
    iree_host_size_t static_offsets_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_update_vtable;

// LOOM_OP_TEST_INVOKE: Test variadic call-like op with tied results.
// %output, %count = test.invoke @callee(%weights, %input) : (tile<4xf32>, index) -> (%weights as tile<4xf32>, index)
LOOM_DEFINE_ISA(loom_test_invoke_isa, LOOM_OP_TEST_INVOKE)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_invoke_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_invoke_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_test_invoke_callee, 0)
iree_status_t loom_test_invoke_build(
    loom_builder_t* builder,
    loom_symbol_ref_t callee,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_invoke_vtable;

// LOOM_OP_TEST_SLICE: Test index list with mixed static/dynamic offsets.
// %subtile = test.slice %source[0, %offset] : tile<64x64xf16> -> (tile<16x16xf16>)
LOOM_DEFINE_ISA(loom_test_slice_isa, LOOM_OP_TEST_SLICE)
LOOM_DEFINE_OPERAND(loom_test_slice_source, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_slice_offsets, 1)
LOOM_DEFINE_RESULT(loom_test_slice_result, 0)
iree_status_t loom_test_slice_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    const loom_value_id_t* offsets,
    iree_host_size_t offsets_count,
    const int64_t* static_offsets,
    iree_host_size_t static_offsets_count,
    loom_type_t result_type,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_slice_vtable;

// LOOM_OP_TEST_LOOP: Test for-loop with iter_args and tied results.
// %result = test.loop %i = %c0 to %count step %c1 iter_args(%accumulator = %init : f32) -> (f32) {
LOOM_DEFINE_ISA(loom_test_loop_isa, LOOM_OP_TEST_LOOP)
LOOM_DEFINE_OPERAND(loom_test_loop_lower_bound, 0)
LOOM_DEFINE_OPERAND(loom_test_loop_upper_bound, 1)
LOOM_DEFINE_OPERAND(loom_test_loop_step, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_loop_iter_args, 3)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_loop_results, 0)
LOOM_DEFINE_REGION(loom_test_loop_body, 0)
iree_status_t loom_test_loop_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t lower_bound,
    loom_may_consume loom_value_id_t upper_bound,
    loom_may_consume loom_value_id_t step,
    loom_may_consume const loom_value_id_t* iter_args,
    iree_host_size_t iter_args_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_loop_vtable;

// LOOM_OP_TEST_BRANCH: Test if/else with both regions always present.
// %result = test.branch %condition -> (f32) {
LOOM_DEFINE_ISA(loom_test_branch_isa, LOOM_OP_TEST_BRANCH)
LOOM_DEFINE_OPERAND(loom_test_branch_condition, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_branch_results, 0)
LOOM_DEFINE_REGION(loom_test_branch_then_region, 0)
LOOM_DEFINE_REGION(loom_test_branch_else_region, 1)
iree_status_t loom_test_branch_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t condition,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_branch_vtable;

// LOOM_OP_TEST_YIELD: Test yield terminator.
// test.yield
LOOM_DEFINE_ISA(loom_test_yield_isa, LOOM_OP_TEST_YIELD)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_yield_values, 0)
iree_status_t loom_test_yield_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_yield_vtable;

// LOOM_OP_TEST_FUNC: Test function definition with body always present.
// test.func @identity(%input: f32) -> (f32) {
LOOM_DEFINE_ISA(loom_test_func_isa, LOOM_OP_TEST_FUNC)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_func_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_test_func_callee, 0)
LOOM_DEFINE_ATTR_ENUM(loom_test_func_visibility, 1)
LOOM_DEFINE_ATTR_ENUM(loom_test_func_cc, 2)
LOOM_DEFINE_REGION(loom_test_func_body, 0)
iree_status_t loom_test_func_build(
    loom_builder_t* builder,
    loom_optional uint8_t visibility,
    loom_optional uint8_t cc,
    loom_symbol_ref_t callee,
    const loom_type_t* arg_types,
    iree_host_size_t arg_types_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_func_vtable;

// LOOM_OP_TEST_ATTRS: Test op with attribute dictionary.
// %result = test.attrs %input {axis = 0, label = "foo"} : f32
LOOM_DEFINE_ISA(loom_test_attrs_isa, LOOM_OP_TEST_ATTRS)
LOOM_DEFINE_OPERAND(loom_test_attrs_input, 0)
LOOM_DEFINE_RESULT(loom_test_attrs_result, 0)
iree_status_t loom_test_attrs_build(
    loom_builder_t* builder,
    loom_value_id_t input,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_attrs_vtable;

// LOOM_OP_TEST_DEFLATE: Test op with result ordinal dim.
// %output, %length = test.deflate %input : tensor<[%M]xf32> -> (tensor<[#1]xf32>, index)
LOOM_DEFINE_ISA(loom_test_deflate_isa, LOOM_OP_TEST_DEFLATE)
LOOM_DEFINE_OPERAND(loom_test_deflate_input, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_deflate_results, 0)
iree_status_t loom_test_deflate_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t input,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_deflate_vtable;

// LOOM_OP_TEST_ASSUME: Test predicate-constrained identity (SSA assume).
// %M2 = test.assume %M [mul(%M, 16)] : index
LOOM_DEFINE_ISA(loom_test_assume_isa, LOOM_OP_TEST_ASSUME)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_assume_values, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_assume_results, 0)
iree_status_t loom_test_assume_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_assume_vtable;

// LOOM_OP_TEST_CONVERT: Test op with bare result type (no parentheses).
// %result = test.convert %input : i32 -> f32
LOOM_DEFINE_ISA(loom_test_convert_isa, LOOM_OP_TEST_CONVERT)
LOOM_DEFINE_OPERAND(loom_test_convert_input, 0)
LOOM_DEFINE_RESULT(loom_test_convert_result, 0)
iree_status_t loom_test_convert_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_convert_vtable;

// LOOM_OP_TEST_REDUCE: Test variadic operands with SameType constraint across variadic and result.
// %sum = test.reduce %a, %b, %c : i32
LOOM_DEFINE_ISA(loom_test_reduce_isa, LOOM_OP_TEST_REDUCE)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_test_reduce_inputs, 0)
LOOM_DEFINE_RESULT(loom_test_reduce_result, 0)
iree_status_t loom_test_reduce_build(
    loom_builder_t* builder,
    const loom_value_id_t* inputs,
    iree_host_size_t inputs_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_reduce_vtable;

// LOOM_OP_TEST_READ_RESOURCE: Test op that reads from a resource operand.
// %tile = test.read_resource %pool : pool<[%BS]> -> tile<4xf32>
LOOM_DEFINE_ISA(loom_test_read_resource_isa, LOOM_OP_TEST_READ_RESOURCE)
LOOM_DEFINE_OPERAND(loom_test_read_resource_source, 0)
LOOM_DEFINE_RESULT(loom_test_read_resource_result, 0)
iree_status_t loom_test_read_resource_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_read_resource_vtable;

// LOOM_OP_TEST_WRITE_RESOURCE: Test op that writes to a resource operand.
// test.write_resource %pool, %tile : pool<[%BS]>, tile<4xf32>
LOOM_DEFINE_ISA(loom_test_write_resource_isa, LOOM_OP_TEST_WRITE_RESOURCE)
LOOM_DEFINE_OPERAND(loom_test_write_resource_target, 0)
LOOM_DEFINE_OPERAND(loom_test_write_resource_data, 1)
iree_status_t loom_test_write_resource_build(
    loom_builder_t* builder,
    loom_value_id_t target,
    loom_value_id_t data,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_write_resource_vtable;

// LOOM_OP_TEST_MUTATE_RESOURCE: Test op that atomically reads and writes a resource operand.
// %old = test.mutate_resource %pool, %delta : pool<[%BS]>, i32 -> i32
LOOM_DEFINE_ISA(loom_test_mutate_resource_isa, LOOM_OP_TEST_MUTATE_RESOURCE)
LOOM_DEFINE_OPERAND(loom_test_mutate_resource_target, 0)
LOOM_DEFINE_OPERAND(loom_test_mutate_resource_value, 1)
LOOM_DEFINE_RESULT(loom_test_mutate_resource_old_value, 0)
iree_status_t loom_test_mutate_resource_build(
    loom_builder_t* builder, loom_value_id_t lhs,
    loom_value_id_t rhs, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_mutate_resource_vtable;

// LOOM_OP_TEST_ALLOC: Test allocation op. Each execution produces a distinct identity even with identical operands. Prevents CSE but allows DCE when unused.
// %pool = test.alloc %sz : index -> pool<[%BS]>
LOOM_DEFINE_ISA(loom_test_alloc_isa, LOOM_OP_TEST_ALLOC)
LOOM_DEFINE_OPERAND(loom_test_alloc_size, 0)
LOOM_DEFINE_RESULT(loom_test_alloc_result, 0)
iree_status_t loom_test_alloc_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_alloc_vtable;

// LOOM_OP_TEST_ISOLATED_REGION: Test op with an isolated single-block region. Values from the enclosing scope are not visible inside the body.
// %r = test.isolated_region -> (i32) {
LOOM_DEFINE_ISA(loom_test_isolated_region_isa, LOOM_OP_TEST_ISOLATED_REGION)
LOOM_DEFINE_VARIADIC_RESULTS(loom_test_isolated_region_results, 0)
LOOM_DEFINE_REGION(loom_test_isolated_region_body, 0)
iree_status_t loom_test_isolated_region_build(
    loom_builder_t* builder,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_isolated_region_vtable;

// LOOM_OP_TEST_COUNTER: Test op for canonicalize multi-step and error path testing. Canonicalize: value < 0 returns error, value > 0 decrements, value == 0 is fixed point.
// %c = test.counter 3 : i32
LOOM_DEFINE_ISA(loom_test_counter_isa, LOOM_OP_TEST_COUNTER)
LOOM_DEFINE_RESULT(loom_test_counter_result, 0)
LOOM_DEFINE_ATTR_I64(loom_test_counter_value, 0)
iree_status_t loom_test_counter_build(
    loom_builder_t* builder,
    int64_t value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_counter_vtable;
iree_status_t loom_test_counter_canonicalize(loom_op_t* op, loom_rewriter_t* rewriter);

// LOOM_OP_TEST_DIM: Test dimension query to exercise ATTR_IN_RANGE_RANK constraint.
// %d = test.dim %t[0] : tile<4xf32> -> index
LOOM_DEFINE_ISA(loom_test_dim_isa, LOOM_OP_TEST_DIM)
LOOM_DEFINE_OPERAND(loom_test_dim_source, 0)
LOOM_DEFINE_RESULT(loom_test_dim_result, 0)
LOOM_DEFINE_ATTR_I64(loom_test_dim_dim_index, 0)
iree_status_t loom_test_dim_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    int64_t dim_index,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_dim_vtable;

// LOOM_OP_TEST_FACT_RANGE_LO: Exposes the analysis range lower bound as an i64 constant.
// %lo = test.fact_range_lo %x : index -> i64
LOOM_DEFINE_ISA(loom_test_fact_range_lo_isa, LOOM_OP_TEST_FACT_RANGE_LO)
LOOM_DEFINE_OPERAND(loom_test_fact_range_lo_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_range_lo_result, 0)
iree_status_t loom_test_fact_range_lo_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_range_lo_vtable;
void loom_test_fact_range_lo_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_RANGE_HI: Exposes the analysis range upper bound as an i64 constant.
// %hi = test.fact_range_hi %x : index -> i64
LOOM_DEFINE_ISA(loom_test_fact_range_hi_isa, LOOM_OP_TEST_FACT_RANGE_HI)
LOOM_DEFINE_OPERAND(loom_test_fact_range_hi_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_range_hi_result, 0)
iree_status_t loom_test_fact_range_hi_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_range_hi_vtable;
void loom_test_fact_range_hi_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_DIVISOR: Exposes the analysis known divisor as an i64 constant.
// %div = test.fact_divisor %x : index -> i64
LOOM_DEFINE_ISA(loom_test_fact_divisor_isa, LOOM_OP_TEST_FACT_DIVISOR)
LOOM_DEFINE_OPERAND(loom_test_fact_divisor_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_divisor_result, 0)
iree_status_t loom_test_fact_divisor_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_divisor_vtable;
void loom_test_fact_divisor_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_NON_NEGATIVE: Returns 1 if the input is provably non-negative, 0 otherwise.
// %nn = test.fact_non_negative %x : index -> i1
LOOM_DEFINE_ISA(loom_test_fact_non_negative_isa, LOOM_OP_TEST_FACT_NON_NEGATIVE)
LOOM_DEFINE_OPERAND(loom_test_fact_non_negative_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_non_negative_result, 0)
iree_status_t loom_test_fact_non_negative_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_non_negative_vtable;
void loom_test_fact_non_negative_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_NON_ZERO: Returns 1 if the input is provably non-zero, 0 otherwise.
// %nz = test.fact_non_zero %x : index -> i1
LOOM_DEFINE_ISA(loom_test_fact_non_zero_isa, LOOM_OP_TEST_FACT_NON_ZERO)
LOOM_DEFINE_OPERAND(loom_test_fact_non_zero_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_non_zero_result, 0)
iree_status_t loom_test_fact_non_zero_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_non_zero_vtable;
void loom_test_fact_non_zero_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_POSITIVE: Returns 1 if the input is provably positive (> 0), 0 otherwise.
// %pos = test.fact_positive %x : index -> i1
LOOM_DEFINE_ISA(loom_test_fact_positive_isa, LOOM_OP_TEST_FACT_POSITIVE)
LOOM_DEFINE_OPERAND(loom_test_fact_positive_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_positive_result, 0)
iree_status_t loom_test_fact_positive_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_positive_vtable;
void loom_test_fact_positive_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// LOOM_OP_TEST_FACT_POWER_OF_TWO: Returns 1 if the input is provably a power of two, 0 otherwise.
// %p2 = test.fact_power_of_two %x : index -> i1
LOOM_DEFINE_ISA(loom_test_fact_power_of_two_isa, LOOM_OP_TEST_FACT_POWER_OF_TWO)
LOOM_DEFINE_OPERAND(loom_test_fact_power_of_two_value, 0)
LOOM_DEFINE_RESULT(loom_test_fact_power_of_two_result, 0)
iree_status_t loom_test_fact_power_of_two_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_test_fact_power_of_two_vtable;
void loom_test_fact_power_of_two_fold(
    const loom_module_t* module, const loom_op_t* op,
    const loom_value_facts_t* operand_facts,
    loom_value_facts_t* result_facts);

// Returns the vtable array for the test dialect.
const loom_op_vtable_t* const* loom_test_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_TEST_OPS_H_
