// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: cd runtime/py && PYTHONPATH=. python3 -m loom.gen.c_tables
// clang-format off

#ifndef LOOM_OPS_GLOBAL_OPS_H_
#define LOOM_OPS_GLOBAL_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_GLOBAL_CONSTANT = LOOM_OP_KIND(LOOM_DIALECT_GLOBAL, 0),
  LOOM_OP_GLOBAL_VARIABLE = LOOM_OP_KIND(LOOM_DIALECT_GLOBAL, 1),
  LOOM_OP_GLOBAL_LOAD = LOOM_OP_KIND(LOOM_DIALECT_GLOBAL, 2),
  LOOM_OP_GLOBAL_STORE = LOOM_OP_KIND(LOOM_DIALECT_GLOBAL, 3),
  LOOM_OP_GLOBAL_COUNT_ = 4,
};

// LOOM_OP_GLOBAL_CONSTANT: Immutable global value. May have an inline initial value, a resource reference, or be initialized by an initializer function. After initialization, never written. Named type variables in the type annotation express structural constraints. Predicates constrain dynamic dimensions and are propagated to every load site as value facts.
// global.constant @pi : f32
LOOM_DEFINE_ISA(loom_global_constant_isa, LOOM_OP_GLOBAL_CONSTANT)
LOOM_DEFINE_RESULT(loom_global_constant_type, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_global_constant_callee, 0)
iree_status_t loom_global_constant_build(
    loom_builder_t* builder,
    loom_symbol_ref_t callee,
    loom_type_t result_type,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_global_constant_vtable;

// LOOM_OP_GLOBAL_VARIABLE: Mutable global value. Can be stored from any function at any time. Named type variables and predicates work the same as global.constant.
// global.variable @kv_cache : tile<[%s]x[%d]xf32> where [mul(%s, 64)]
LOOM_DEFINE_ISA(loom_global_variable_isa, LOOM_OP_GLOBAL_VARIABLE)
LOOM_DEFINE_RESULT(loom_global_variable_type, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_global_variable_callee, 0)
iree_status_t loom_global_variable_build(
    loom_builder_t* builder,
    loom_symbol_ref_t callee,
    loom_type_t result_type,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_global_variable_vtable;

// LOOM_OP_GLOBAL_LOAD: Load a value from a global. The type annotation uses #N result ordinals for fresh dynamic dims (new SSA values) and %name references for bound dims (existing SSA values, assertion). Predicates on the global definition are propagated as value facts.
// %tile, %m, %k = global.load @weights : tile<[#1]x[#2]xf32>
LOOM_DEFINE_ISA(loom_global_load_isa, LOOM_OP_GLOBAL_LOAD)
LOOM_DEFINE_VARIADIC_RESULTS(loom_global_load_result, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_global_load_global, 0)
iree_status_t loom_global_load_build(
    loom_builder_t* builder,
    loom_symbol_ref_t global,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_global_load_vtable;
iree_status_t loom_global_load_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_GLOBAL_STORE: Store a value to a global. Dynamic dims and encodings are captured implicitly from the type annotation, which references existing SSA values. The verifier checks that stores to global.constant only happen from initializer-reachable code paths.
// global.store %tile, @kv_cache : tile<[%m]xf32>
LOOM_DEFINE_ISA(loom_global_store_isa, LOOM_OP_GLOBAL_STORE)
LOOM_DEFINE_OPERAND(loom_global_store_value, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_global_store_global, 0)
iree_status_t loom_global_store_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_symbol_ref_t global,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_global_store_vtable;
iree_status_t loom_global_store_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the global dialect.
const loom_op_vtable_t* const* loom_global_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_GLOBAL_OPS_H_
