# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any

from loom.builder import IRBuilder, ValueRef
from loom.ir import Region


class KernelBuilders:
    """Typed builder methods for kernel ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def barrier(self, *, memory_space: str, ordering: str, scope: str) -> None:
        """Synchronize invocations in an explicit execution scope and fence a named memory space with a required ordering. The initial supported form is a workgroup barrier over workgroup memory with acquire-release ordering; other enum cases are reserved until their lowering and legality rules are implemented.

        Example::
            kernel.barrier {memory_space = workgroup, ordering = acq_rel, scope = workgroup}
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["memory_space"] = memory_space
        _attributes["ordering"] = ordering
        _attributes["scope"] = scope
        self._b.build("kernel.barrier", _operands, attributes=_attributes, regions=_regions)
