# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any

from loom.builder import IRBuilder, ValueRef
from loom.ir import Block, Region


class CfgBuilders:
    """Typed builder methods for cfg ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def br(self, *, dest: Block, args: list[ValueRef]) -> None:
        """Unconditional branch to a successor block, forwarding zero or more block argument values.

        Example::
            cfg.br ^ done
        """
        _operands: list[ValueRef | int] = []
        _successors: list[Block] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _successors.append(dest)
        _operands.extend(args)
        self._b.build("cfg.br", _operands, successors=_successors, attributes=_attributes, regions=_regions)

    def cond_br(self, *, condition: ValueRef, true_dest: Block, false_dest: Block) -> None:
        """Conditional branch to one of two successor blocks based on an i1 condition.

        Example::
            cfg.cond_br %condition, ^then, ^else : i1
        """
        _operands: list[ValueRef | int] = []
        _successors: list[Block] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _successors.append(true_dest)
        _successors.append(false_dest)
        _operands.append(condition)
        self._b.build("cfg.cond_br", _operands, successors=_successors, attributes=_attributes, regions=_regions)
