// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_LLVMIR_OPS_H_
#define LOOM_OPS_LLVMIR_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_LLVMIR_INLINE_ASM = LOOM_OP_KIND(LOOM_DIALECT_LLVMIR, 0),
  LOOM_OP_LLVMIR_INTRINSIC = LOOM_OP_KIND(LOOM_DIALECT_LLVMIR, 1),
  LOOM_OP_LLVMIR_COUNT_ = 2,
};

// LLVM inline asm call flags.
#define LOOM_LLVMIR_ASMFLAGS_SIDEEFFECT ((uint8_t)1)
#define LOOM_LLVMIR_ASMFLAGS_ALIGNSTACK ((uint8_t)2)
#define LOOM_LLVMIR_ASMFLAGS_INTELDIALECT ((uint8_t)4)

// LOOM_OP_LLVMIR_INLINE_ASM: Structured LLVM inline assembly call. The asm template and constraint strings use LLVM inline asm syntax; operands/results remain ordinary typed Loom SSA values.
// %sum = llvmir.inline_asm<sideeffect> "addl $2, $0", "=r,r,r"(%lhs, %rhs) : (i32, i32) -> i32
LOOM_DEFINE_ISA(loom_llvmir_inline_asm_isa, LOOM_OP_LLVMIR_INLINE_ASM)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_llvmir_inline_asm_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_llvmir_inline_asm_results, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_llvmir_inline_asm_flags)
LOOM_DEFINE_ATTR_STRING(loom_llvmir_inline_asm_asm_template, 0)
LOOM_DEFINE_ATTR_STRING(loom_llvmir_inline_asm_constraints, 1)
iree_status_t loom_llvmir_inline_asm_build(
    loom_builder_t* builder,
    uint8_t instance_flags,
    loom_string_id_t asm_template,
    loom_string_id_t constraints,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LLVMIR_INTRINSIC: Structured call to a supported LLVM intrinsic. The intrinsic spelling is a string so target-family providers can recognize their own intrinsics without extending a central enum.
// %ticks = llvmir.intrinsic<llvm.x86.rdtsc> () : () -> i64
LOOM_DEFINE_ISA(loom_llvmir_intrinsic_isa, LOOM_OP_LLVMIR_INTRINSIC)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_llvmir_intrinsic_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_llvmir_intrinsic_results, 0)
LOOM_DEFINE_ATTR_STRING(loom_llvmir_intrinsic_kind, 0)
iree_status_t loom_llvmir_intrinsic_build(
    loom_builder_t* builder,
    loom_string_id_t kind,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// Returns the vtable array for the llvmir dialect.
const loom_op_vtable_t* const* loom_llvmir_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_LLVMIR_OPS_H_
