# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python -m loom.gen.builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Region, Type


class PoolBuilders:
    """Typed builder methods for pool ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def load(self, *, pool: ValueRef, page_id: ValueRef, page_bytes: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Read a page from the pool as a typed tile.

        Example::
            %tile = pool.load %pool, %pid, %pb : pool<[%BS]>, i32, index -> tile<[16, 128]xf16>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(pool)
        _operands.append(page_id)
        _operands.append(page_bytes)
        return cast(ValueRef, self._b.build("pool.load", _operands, results=results, attributes=_attributes, regions=_regions))

    def store(self, *, pool: ValueRef, page_id: ValueRef, page_bytes: ValueRef, offset_in_page: ValueRef, data: ValueRef) -> None:
        """Write tile data into the pool at a page offset.

        Example::
            pool.store %pool, %pid, %pb, %off, %data : pool<[%BS]>, i32, index, i32, tile<[16, 128]xf16>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(pool)
        _operands.append(page_id)
        _operands.append(page_bytes)
        _operands.append(offset_in_page)
        _operands.append(data)
        self._b.build("pool.store", _operands, attributes=_attributes, regions=_regions)

    def pin(self, *, pool: ValueRef, block_id: ValueRef) -> None:
        """Atomically increment the pin count for a block.

        Example::
            pool.pin %pool, %bid : pool<[%BS]>, i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(pool)
        _operands.append(block_id)
        self._b.build("pool.pin", _operands, attributes=_attributes, regions=_regions)

    def unpin(self, *, pool: ValueRef, block_id: ValueRef) -> None:
        """Atomically decrement the pin count for a block.

        Example::
            pool.unpin %pool, %bid : pool<[%BS]>, i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(pool)
        _operands.append(block_id)
        self._b.build("pool.unpin", _operands, attributes=_attributes, regions=_regions)

    def buffer(self, *, pool: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract the raw device buffer handle from a pool.

        Example::
            %buf = pool.buffer %pool : pool<[%BS]> -> hal.buffer
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(pool)
        return cast(ValueRef, self._b.build("pool.buffer", _operands, results=results, attributes=_attributes, regions=_regions))
