# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from collections.abc import Mapping
from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Region, Type


class CheckBuilders:
    """Typed builder methods for check ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def case(self, *, visibility: str | None = None, case_symbol: str, body: Region | None = None) -> None:
        """Named correctness harness.

        Example::
            check.case @empty {
              check.return
            }
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if visibility is not None:
            _attributes["visibility"] = visibility
        _attributes["case_symbol"] = case_symbol
        if body is not None:
            _regions.append(body)
        self._b.build("check.case", _operands, attributes=_attributes, regions=_regions)

    def return_(self) -> None:
        """Terminates a check.case body.

        Example::
            check.return
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        self._b.build("check.return", _operands, attributes=_attributes, regions=_regions)

    def requires(self, *, provider: str, attrs: Mapping[str, Any]) -> None:
        """Declares a provider requirement; unmet requirements skip the case.

        Example::
            check.requires<target.feature> attrs({feature = "amdgpu.gfx11"})
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["provider"] = provider
        _attributes["attrs"] = attrs
        self._b.build("check.requires", _operands, attributes=_attributes, regions=_regions)

    def skip_if(self, *, provider: str, attrs: Mapping[str, Any], reason: str | None = None) -> None:
        """Declares a provider skip predicate for exceptional environments.

        Example::
            check.skip_if<device.memory> attrs({max_bytes = 1073741824}) reason("fixture too large")
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["provider"] = provider
        _attributes["attrs"] = attrs
        if reason is not None:
            _attributes["reason"] = reason
        self._b.build("check.skip_if", _operands, attributes=_attributes, regions=_regions)

    def range(self, *, policy: str, lower: Any, upper: Any, step: Any | None = None, result_types: list[Type]) -> ValueRef:
        """Produces one sampled scalar parameter from a static interval.

        Example::
            %m = check.param.range po2 bounds(1 to 64) : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["policy"] = policy
        _attributes["lower"] = lower
        _attributes["upper"] = upper
        if step is not None:
            _attributes["step"] = step
        return cast(ValueRef, self._b.build("check.param.range", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def choice(self, *, values: list[int], result_types: list[Type]) -> ValueRef:
        """Produces one sampled integer/index parameter from an explicit choice set.

        Example::
            %k = check.param.choice values([16, 24, 32, 64]) : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["values"] = values
        return cast(ValueRef, self._b.build("check.param.choice", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def seed(self, *, base: int, count: int, result_types: list[Type]) -> ValueRef:
        """Produces deterministic i64 seeds for randomized generators.

        Example::
            %seed = check.param.seed base(0x4c6f6f6d) count(32) : i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["base"] = base
        _attributes["count"] = count
        return cast(ValueRef, self._b.build("check.param.seed", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def literal(self, *, value: Any, result_types: list[Type]) -> ValueRef:
        """Materializes a typed scalar literal for reproducer inputs or expected values.

        Example::
            %scalar = check.literal value(42) : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("check.literal", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def iota(self, *, offset: Any, step: Any, result_types: list[Type]) -> ValueRef:
        """Generates a deterministic iota-shaped value.

        Example::
            %lhs = check.generate.iota offset(0) step(1) : tensor<[%m]x[%n]xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["offset"] = offset
        _attributes["step"] = step
        return cast(ValueRef, self._b.build("check.generate.iota", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fill(self, *, value: Any, result_types: list[Type]) -> ValueRef:
        """Generates a value filled with one static scalar payload.

        Example::
            %rhs = check.generate.fill value(17) : tensor<[%m]x[%n]xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("check.generate.fill", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def uniform(self, *, seed: ValueRef, lower: Any, upper: Any, result_types: list[Type]) -> ValueRef:
        """Generates a deterministic random-uniform value from a sampled seed.

        Example::
            %input = check.generate.random.uniform seed(%seed) range(-1.0 to 1.0) : tensor<[%m]xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["lower"] = lower
        _attributes["upper"] = upper
        _operands.append(seed)
        return cast(ValueRef, self._b.build("check.generate.random.uniform", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def file_read_npy(self, *, path: str, result_types: list[Type]) -> ValueRef:
        """Reads a typed value from an NPY fixture file.

        Example::
            %input = check.file.read.npy path("fixtures/layer_norm/input.npy") : tensor<1024xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["path"] = path
        return cast(ValueRef, self._b.build("check.file.read.npy", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def file_write_npy(self, *, value: ValueRef, path: str, mode: str | None = None) -> None:
        """Writes a typed value to an NPY file according to a static output policy.

        Example::
            check.file.write.npy value(%actual) path("outputs/layer_norm.actual.npy") mode(on_failure) : tensor<1024xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["path"] = path
        if mode is not None:
            _attributes["mode"] = mode
        _operands.append(value)
        self._b.build("check.file.write.npy", _operands, attributes=_attributes, regions=_regions)

    def call(self, *, provider: str, callee: str, inputs: list[ValueRef], results: list[Type | TiedResultSpec]) -> list[ValueRef]:
        """Calls a pluggable oracle provider for expected values.

        Example::
            %expected = check.oracle.call<reference.scalar> callee(@gemv_f32) inputs(%lhs, %rhs) : (tensor<[%m]x[%n]xf32>, tensor<[%n]xf32>) -> (tensor<[%m]xf32>)
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["provider"] = provider
        _attributes["callee"] = callee
        _operands.extend(inputs)
        return cast(list[ValueRef], self._b.build("check.oracle.call", _operands, results=results, attributes=_attributes, regions=_regions))

    def equal(self, *, actual: ValueRef, expected: ValueRef) -> None:
        """Requires actual and expected values to compare equal.

        Example::
            check.expect.equal actual(%actual) expected(%expected) : tensor<[%m]xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(actual)
        _operands.append(expected)
        self._b.build("check.expect.equal", _operands, attributes=_attributes, regions=_regions)

    def bitwise(self, *, actual: ValueRef, expected: ValueRef) -> None:
        """Requires actual and expected values to match bit-for-bit.

        Example::
            check.expect.bitwise actual(%actual) expected(%expected) : tensor<1024xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(actual)
        _operands.append(expected)
        self._b.build("check.expect.bitwise", _operands, attributes=_attributes, regions=_regions)

    def close(self, *, actual: ValueRef, expected: ValueRef, atol: float, rtol: float, nan: str) -> None:
        """Requires actual and expected floating-point values to be approximately equal.

        Example::
            check.expect.close actual(%actual) expected(%expected) atol(0.0001) rtol(0.0001) nan(same) : tensor<[%m]xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["atol"] = atol
        _attributes["rtol"] = rtol
        _attributes["nan"] = nan
        _operands.append(actual)
        _operands.append(expected)
        self._b.build("check.expect.close", _operands, attributes=_attributes, regions=_regions)

    def shape(self, *, value: ValueRef, dims: list[int | ValueRef]) -> None:
        """Requires a shaped value to have the expected dynamic/static shape.

        Example::
            check.expect.shape value(%actual) shape([%m, %n, 4]) : tensor<[%m]x[%n]x4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _sentinel = -(2**63)
        _static = []
        for _idx in dims:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_dims"] = _static
        self._b.build("check.expect.shape", _operands, attributes=_attributes, regions=_regions)

    def expect(self, *, provider: str, actual: ValueRef, expected: ValueRef, attrs: Mapping[str, Any] | None = None) -> None:
        """Runs a pluggable custom validator over actual and expected values.

        Example::
            check.expect<topk.equal> actual(%actual) expected(%expected) attrs({k = 5}) : tensor<1000xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["provider"] = provider
        if attrs is not None:
            _attributes["attrs"] = attrs
        _operands.append(actual)
        _operands.append(expected)
        self._b.build("check.expect", _operands, attributes=_attributes, regions=_regions)

    def benchmark(self, *, benchmark: str, case_ref: str, attrs: Mapping[str, Any]) -> None:
        """Declarative benchmark/tuning policy over a check.case.

        Example::
            check.benchmark @gemv_latency case(@gemv_sweep) attrs({measure = "dispatch_complete", iterations = 100})
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["benchmark"] = benchmark
        _attributes["case_ref"] = case_ref
        _attributes["attrs"] = attrs
        self._b.build("check.benchmark", _operands, attributes=_attributes, regions=_regions)
