// Auto-generated by loom.gen.c_errors — do not edit.

#include "loom/error/error_defs.h"

static const char* const
    loom_diagnostic_severity_names[LOOM_DIAGNOSTIC_COUNT_] = {
        [LOOM_DIAGNOSTIC_ERROR] = "error",
        [LOOM_DIAGNOSTIC_WARNING] = "warning",
        [LOOM_DIAGNOSTIC_REMARK] = "remark",
};

const char* loom_diagnostic_severity_name(loom_diagnostic_severity_t severity) {
  if (severity < LOOM_DIAGNOSTIC_COUNT_) {
    return loom_diagnostic_severity_names[severity];
  }
  return "unknown";
}

static const char* const loom_error_domain_names[LOOM_ERROR_DOMAIN_COUNT_] = {
    [LOOM_ERROR_DOMAIN_TYPE] = "TYPE",
    [LOOM_ERROR_DOMAIN_SHAPE] = "SHAPE",
    [LOOM_ERROR_DOMAIN_SUBRANGE] = "SUBRANGE",
    [LOOM_ERROR_DOMAIN_ENCODING] = "ENCODING",
    [LOOM_ERROR_DOMAIN_STRUCTURE] = "STRUCTURE",
    [LOOM_ERROR_DOMAIN_DOMINANCE] = "DOMINANCE",
    [LOOM_ERROR_DOMAIN_SYMBOL] = "SYMBOL",
    [LOOM_ERROR_DOMAIN_PARSE] = "PARSE",
    [LOOM_ERROR_DOMAIN_BYTECODE] = "BYTECODE",
    [LOOM_ERROR_DOMAIN_FOLD] = "FOLD",
};

const char* loom_error_domain_name(loom_error_domain_t domain) {
  if (domain < LOOM_ERROR_DOMAIN_COUNT_) {
    return loom_error_domain_names[domain];
  }
  return "UNKNOWN";
}

bool loom_error_domain_from_name(iree_string_view_t name,
                                 loom_error_domain_t* out_domain) {
  for (int i = 0; i < LOOM_ERROR_DOMAIN_COUNT_; ++i) {
    if (iree_string_view_equal(
            name, iree_make_cstring_view(loom_error_domain_names[i]))) {
      *out_domain = (loom_error_domain_t)i;
      return true;
    }
  }
  return false;
}

static const char* const loom_emitter_names[LOOM_EMITTER_COUNT_] = {
    [LOOM_EMITTER_VERIFIER] = "verifier",
    [LOOM_EMITTER_PARSER] = "parser",
    [LOOM_EMITTER_BYTECODE_READER] = "bytecode_reader",
    [LOOM_EMITTER_PASS] = "pass",
    [LOOM_EMITTER_BUILDER] = "builder",
};

const char* loom_emitter_name(loom_emitter_t emitter) {
  if (emitter < LOOM_EMITTER_COUNT_) {
    return loom_emitter_names[emitter];
  }
  return "unknown";
}

static const loom_error_param_def_t loom_err_type_001_params[] = {
    {"field_a", LOOM_PARAM_STRING},
    {"type_a", LOOM_PARAM_TYPE},
    {"field_b", LOOM_PARAM_STRING},
    {"type_b", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_001 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "SameType constraint violated.",
    .message_template =
        "'{field_a}' type {type_a} does not match '{field_b}' type {type_b}",
    .fix_hint_template =
        "Ensure '{field_a}' and '{field_b}' have the same type",
    .param_defs = loom_err_type_001_params,
    .param_count = 4,
};

static const loom_error_param_def_t loom_err_type_002_params[] = {
    {"field_a", LOOM_PARAM_STRING},
    {"element_type_a", LOOM_PARAM_TYPE},
    {"field_b", LOOM_PARAM_STRING},
    {"element_type_b", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_002 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Operands must have the same element type.",
    .message_template =
        "element type mismatch: '{field_a}' has element type {element_type_a}, "
        "'{field_b}' has element type {element_type_b}",
    .fix_hint_template =
        "Operands '{field_a}' and '{field_b}' must have the same element type; "
        "use explicit type casts if needed",
    .param_defs = loom_err_type_002_params,
    .param_count = 4,
};

static const loom_error_param_def_t loom_err_type_003_params[] = {
    {"operand_name", LOOM_PARAM_STRING},
    {"actual_type", LOOM_PARAM_TYPE},
    {"expected_constraint", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_type_003 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Operand type constraint violated.",
    .message_template =
        "operand '{operand_name}' has type {actual_type}, expected "
        "{expected_constraint}",
    .fix_hint_template =
        "'{operand_name}' must satisfy type constraint '{expected_constraint}'",
    .param_defs = loom_err_type_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_type_004_params[] = {
    {"result_name", LOOM_PARAM_STRING},
    {"actual_type", LOOM_PARAM_TYPE},
    {"expected_constraint", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_type_004 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Result type constraint violated.",
    .message_template =
        "result '{result_name}' has type {actual_type}, expected "
        "{expected_constraint}",
    .fix_hint_template =
        "'{result_name}' must satisfy type constraint '{expected_constraint}'",
    .param_defs = loom_err_type_004_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_type_005_params[] = {
    {"attr_name", LOOM_PARAM_STRING},
    {"actual_kind", LOOM_PARAM_U32},
    {"expected_kind", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_type_005 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Attribute kind mismatch.",
    .message_template =
        "attribute '{attr_name}' has kind {actual_kind}, expected "
        "{expected_kind}",
    .fix_hint_template = "'{attr_name}' must be a {expected_kind} attribute",
    .param_defs = loom_err_type_005_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_type_006_params[] = {
    {"value_type", LOOM_PARAM_TYPE},
    {"element_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_006 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 6,
    .summary = "Fill value type mismatch.",
    .message_template =
        "fill value has type {value_type}, but tile element type is "
        "{element_type}",
    .fix_hint_template = "Cast or convert fill value to type {element_type}",
    .param_defs = loom_err_type_006_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_type_007_params[] = {
    {"attr_type", LOOM_PARAM_TYPE},
    {"result_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_007 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 7,
    .summary = "Constant attribute type mismatch.",
    .message_template =
        "constant attribute has type {attr_type} but result tile has type "
        "{result_type}",
    .fix_hint_template =
        "Ensure constant attribute shape and element type match "
        "'{result_type}'",
    .param_defs = loom_err_type_007_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_type_008_params[] = {
    {"arg_index", LOOM_PARAM_U32},
    {"arg_type", LOOM_PARAM_TYPE},
    {"element_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_008 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 8,
    .summary = "Block argument type does not match input element type.",
    .message_template =
        "block argument {arg_index} has type {arg_type}, expected element type "
        "{element_type}",
    .fix_hint_template =
        "Block argument should have type {element_type} to match tile element "
        "type",
    .param_defs = loom_err_type_008_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_type_009_params[] = {
    {"yield_type", LOOM_PARAM_TYPE},
    {"result_element_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_type_009 = {
    .domain = LOOM_ERROR_DOMAIN_TYPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 9,
    .summary = "Yielded value type does not match result tile element type.",
    .message_template =
        "yielded value has type {yield_type}, but result tile element type is "
        "{result_element_type}",
    .fix_hint_template = "Convert yielded value to type {result_element_type}",
    .param_defs = loom_err_type_009_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_shape_001_params[] = {
    {"operand_a", LOOM_PARAM_STRING},
    {"rank_a", LOOM_PARAM_I64},
    {"operand_b", LOOM_PARAM_STRING},
    {"rank_b", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_shape_001 = {
    .domain = LOOM_ERROR_DOMAIN_SHAPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Operand ranks do not match.",
    .message_template =
        "'{operand_a}' rank ({rank_a}) does not match '{operand_b}' rank "
        "({rank_b})",
    .fix_hint_template =
        "'{operand_a}' and '{operand_b}' must have the same rank",
    .param_defs = loom_err_shape_001_params,
    .param_count = 4,
};

static const loom_error_param_def_t loom_err_shape_002_params[] = {
    {"field_a", LOOM_PARAM_STRING},
    {"field_b", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_shape_002 = {
    .domain = LOOM_ERROR_DOMAIN_SHAPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "SameShape constraint violated.",
    .message_template = "'{field_a}' shape does not match '{field_b}' shape",
    .fix_hint_template =
        "Ensure '{field_a}' and '{field_b}' have identical shapes",
    .param_defs = loom_err_shape_002_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_shape_003_params[] = {
    {"first_type", LOOM_PARAM_TYPE},
    {"other_index", LOOM_PARAM_U32},
    {"other_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_shape_003 = {
    .domain = LOOM_ERROR_DOMAIN_SHAPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Input tiles must have identical shapes.",
    .message_template =
        "input tile shapes do not match: input 0 has type {first_type}, input "
        "{other_index} has type {other_type}",
    .fix_hint_template =
        "Ensure all input tiles have identical shapes, or use tile.broadcast "
        "first",
    .param_defs = loom_err_shape_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_shape_004_params[] = {
    {"source_axis", LOOM_PARAM_U32},
    {"source_size", LOOM_PARAM_I64},
    {"result_axis", LOOM_PARAM_U32},
    {"result_size", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_shape_004 = {
    .domain = LOOM_ERROR_DOMAIN_SHAPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Incompatible dimension sizes during broadcast.",
    .message_template =
        "incompatible dimension at source axis {source_axis} (size "
        "{source_size}) with result axis {result_axis} (size {result_size})",
    .fix_hint_template =
        "Source axis {source_axis} (size {source_size}) must be 1 or match "
        "result axis {result_axis} (size {result_size})",
    .param_defs = loom_err_shape_004_params,
    .param_count = 4,
};

static const loom_error_param_def_t loom_err_shape_005_params[] = {
    {"result_type", LOOM_PARAM_TYPE},
    {"input_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_shape_005 = {
    .domain = LOOM_ERROR_DOMAIN_SHAPE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Result tile shape must match input tile shapes.",
    .message_template =
        "result tile type {result_type} does not match input tile type "
        "{input_type}",
    .fix_hint_template =
        "Ensure result type has the same shape as the input tiles",
    .param_defs = loom_err_shape_005_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_subrange_001_params[] = {
    {"operand_name", LOOM_PARAM_STRING},
    {"offset_count", LOOM_PARAM_U32},
    {"rank", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_subrange_001 = {
    .domain = LOOM_ERROR_DOMAIN_SUBRANGE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Offset count must match operand rank.",
    .message_template =
        "'{operand_name}' offset count ({offset_count}) does not match rank "
        "({rank})",
    .fix_hint_template = "Provide exactly {rank} offsets for '{operand_name}'",
    .param_defs = loom_err_subrange_001_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_subrange_002_params[] = {
    {"dim_index", LOOM_PARAM_I64},
    {"rank", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_subrange_002 = {
    .domain = LOOM_ERROR_DOMAIN_SUBRANGE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Dimension index out of bounds.",
    .message_template =
        "dimension index {dim_index} is out of bounds for type with rank "
        "{rank}",
    .fix_hint_template = "Use an index in range [0, {rank})",
    .param_defs = loom_err_subrange_002_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_subrange_003_params[] = {
    {"operand_name", LOOM_PARAM_STRING},
    {"size_count", LOOM_PARAM_U32},
    {"rank", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_subrange_003 = {
    .domain = LOOM_ERROR_DOMAIN_SUBRANGE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Size count must match operand rank.",
    .message_template =
        "'{operand_name}' size count ({size_count}) does not match rank "
        "({rank})",
    .fix_hint_template = "Provide exactly {rank} sizes for '{operand_name}'",
    .param_defs = loom_err_subrange_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_subrange_004_params[] = {
    {"dim_index", LOOM_PARAM_I64}, {"offset", LOOM_PARAM_I64},
    {"size", LOOM_PARAM_I64},      {"total", LOOM_PARAM_I64},
    {"bound", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_subrange_004 = {
    .domain = LOOM_ERROR_DOMAIN_SUBRANGE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Static slice extends beyond bounds.",
    .message_template =
        "dimension {dim_index}: offset ({offset}) + size ({size}) = {total} "
        "exceeds bound {bound}",
    .fix_hint_template =
        "Ensure offset + size <= {bound} for dimension {dim_index}",
    .param_defs = loom_err_subrange_004_params,
    .param_count = 5,
};

static const loom_error_param_def_t loom_err_encoding_001_params[] = {
    {"field_a", LOOM_PARAM_STRING},
    {"field_b", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_encoding_001 = {
    .domain = LOOM_ERROR_DOMAIN_ENCODING,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Operands must have the same encoding.",
    .message_template =
        "encoding mismatch: '{field_a}' and '{field_b}' have different "
        "encodings",
    .fix_hint_template =
        "Operands '{field_a}' and '{field_b}' must have the same encoding; use "
        "explicit encoding casts if needed",
    .param_defs = loom_err_encoding_001_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_encoding_002_params[] = {
    {"op_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_encoding_002 = {
    .domain = LOOM_ERROR_DOMAIN_ENCODING,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Encoding must be preserved across slice/view operations.",
    .message_template =
        "result encoding does not match source encoding for '{op_name}'",
    .fix_hint_template =
        "Slice and view operations must preserve the source encoding",
    .param_defs = loom_err_encoding_002_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_encoding_003_params[] = {
    {"field_name", LOOM_PARAM_STRING},
    {"value_id", LOOM_PARAM_U32},
    {"value_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_encoding_003 = {
    .domain = LOOM_ERROR_DOMAIN_ENCODING,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "SSA encoding reference out of range.",
    .message_template =
        "{field_name} type references encoding value %{value_id}, but module "
        "has only {value_count} values",
    .fix_hint_template =
        "The encoding value_id in the type is invalid; this indicates a "
        "corrupted or malformed module",
    .param_defs = loom_err_encoding_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_encoding_004_params[] = {
    {"field_name", LOOM_PARAM_STRING},
    {"value_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_encoding_004 = {
    .domain = LOOM_ERROR_DOMAIN_ENCODING,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "SSA encoding value not visible at point of use.",
    .message_template =
        "{field_name} type references encoding value '%{value_name}' which is "
        "not defined at this point",
    .fix_hint_template =
        "The encoding value must be defined before it can be referenced in a "
        "type; ensure the encoding.define op dominates this use",
    .param_defs = loom_err_encoding_004_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_encoding_005_params[] = {
    {"field_name", LOOM_PARAM_STRING},
    {"value_name", LOOM_PARAM_STRING},
    {"actual_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_encoding_005 = {
    .domain = LOOM_ERROR_DOMAIN_ENCODING,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "SSA encoding reference has wrong type.",
    .message_template =
        "{field_name} type references encoding value '%{value_name}' which has "
        "type {actual_type}, expected 'encoding'",
    .fix_hint_template =
        "The encoding value must have type 'encoding'; it should be the result "
        "of an encoding.define op",
    .param_defs = loom_err_encoding_005_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_001_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_001 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Wrong operand count.",
    .message_template =
        "'{op_name}' has {actual_count} operands, expected {expected_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_001_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_002_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_002 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Wrong result count.",
    .message_template =
        "'{op_name}' has {actual_count} results, expected {expected_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_002_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_003_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_003 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Wrong attribute count.",
    .message_template =
        "'{op_name}' has {actual_count} attributes, expected {expected_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_004_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_004 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Wrong region count.",
    .message_template =
        "'{op_name}' has {actual_count} regions, expected {expected_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_004_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_005_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"region_index", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_005 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Missing terminator in block.",
    .message_template =
        "block in '{op_name}' region {region_index} is missing a terminator",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_005_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_structure_006_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"region_index", LOOM_PARAM_U32},
    {"block_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_006 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 6,
    .summary = "Single-block region has wrong block count.",
    .message_template =
        "'{op_name}' region {region_index} must have exactly one block, has "
        "{block_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_006_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_007_params[] = {
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_007 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 7,
    .summary = "Region block argument count mismatch.",
    .message_template =
        "region has {actual_count} block arguments, expected {expected_count} "
        "(one per input tile)",
    .fix_hint_template =
        "Ensure the region has exactly one block argument per input tile",
    .param_defs = loom_err_structure_007_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_structure_008_params[] = {
    {"actual_count", LOOM_PARAM_U32},
    {"expected_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_008 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 8,
    .summary = "Yield must produce the correct number of values.",
    .message_template =
        "yield has {actual_count} operands, expected {expected_count}",
    .fix_hint_template = "Yield exactly {expected_count} values",
    .param_defs = loom_err_structure_008_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_structure_009_params[] = {
    {"op_kind", LOOM_PARAM_U32},
    {"op_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_structure_009 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 9,
    .summary = "Unknown op kind.",
    .message_template = "unknown op kind {op_kind} in '{op_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_structure_009_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_structure_010_params[] = {
    {"attr_name", LOOM_PARAM_STRING},
    {"actual_value", LOOM_PARAM_U32},
    {"enum_case_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_structure_010 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 10,
    .summary = "Enum attribute value out of range.",
    .message_template =
        "attribute '{attr_name}' has enum value {actual_value}, but only "
        "{enum_case_count} values are defined",
    .fix_hint_template =
        "'{attr_name}' must have a value in range [0, {enum_case_count})",
    .param_defs = loom_err_structure_010_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_structure_011_params[] = {
    {"op_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_structure_011 = {
    .domain = LOOM_ERROR_DOMAIN_STRUCTURE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 11,
    .summary = "Non-symbol-defining op at module level.",
    .message_template =
        "'{op_name}' cannot appear at module level (only symbol-defining ops "
        "like func.def and func.decl are allowed here)",
    .fix_hint_template = "Move '{op_name}' inside a function body",
    .param_defs = loom_err_structure_011_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_dominance_001_params[] = {
    {"value_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_dominance_001 = {
    .domain = LOOM_ERROR_DOMAIN_DOMINANCE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Use of undefined value.",
    .message_template = "use of undefined value '{value_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_dominance_001_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_dominance_002_params[] = {
    {"value_name", LOOM_PARAM_STRING},
    {"consuming_op", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_dominance_002 = {
    .domain = LOOM_ERROR_DOMAIN_DOMINANCE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Use of consumed value.",
    .message_template =
        "use of consumed value '{value_name}' (consumed by tied result of "
        "'{consuming_op}')",
    .fix_hint_template =
        "Use the tied result of '{consuming_op}' instead of '{value_name}'",
    .param_defs = loom_err_dominance_002_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_dominance_003_params[] = {
    {"value_id", LOOM_PARAM_U32},
    {"max_id", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_dominance_003 = {
    .domain = LOOM_ERROR_DOMAIN_DOMINANCE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Value ID out of range.",
    .message_template = "value ID {value_id} is out of range (max {max_id})",
    .fix_hint_template = NULL,
    .param_defs = loom_err_dominance_003_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_dominance_004_params[] = {
    {"result_index", LOOM_PARAM_U32},
    {"op_name", LOOM_PARAM_STRING},
    {"result_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_dominance_004 = {
    .domain = LOOM_ERROR_DOMAIN_DOMINANCE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Tied result index out of range.",
    .message_template =
        "tied result index {result_index} is out of range for '{op_name}' "
        "which has {result_count} results",
    .fix_hint_template = NULL,
    .param_defs = loom_err_dominance_004_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_dominance_005_params[] = {
    {"operand_index", LOOM_PARAM_U32},
    {"op_name", LOOM_PARAM_STRING},
    {"operand_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_dominance_005 = {
    .domain = LOOM_ERROR_DOMAIN_DOMINANCE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Tied operand index out of range.",
    .message_template =
        "tied operand index {operand_index} is out of range for '{op_name}' "
        "which has {operand_count} operands",
    .fix_hint_template = NULL,
    .param_defs = loom_err_dominance_005_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_symbol_001_params[] = {
    {"symbol_index", LOOM_PARAM_U32},
    {"max_index", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_symbol_001 = {
    .domain = LOOM_ERROR_DOMAIN_SYMBOL,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Symbol reference out of range.",
    .message_template =
        "symbol reference index {symbol_index} is out of range (max "
        "{max_index})",
    .fix_hint_template = NULL,
    .param_defs = loom_err_symbol_001_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_parse_001_params[] = {
    {"value_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_001 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Undefined SSA value.",
    .message_template = "undefined SSA value '%{value_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_001_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_002_params[] = {
    {"value_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_002 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Duplicate SSA name.",
    .message_template = "SSA value '%{value_name}' is already defined",
    .fix_hint_template = "Each SSA value name must be unique within its scope",
    .param_defs = loom_err_parse_002_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_003_params[] = {
    {"actual_token", LOOM_PARAM_STRING},
    {"expected", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_003 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Unexpected token.",
    .message_template =
        "unexpected token '{actual_token}', expected {expected}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_003_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_parse_004_params[] = {
    {"text", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_004 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Invalid type syntax.",
    .message_template = "invalid type syntax: '{text}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_004_params,
    .param_count = 1,
};

const loom_error_def_t loom_err_parse_005 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Unterminated string literal.",
    .message_template = "unterminated string literal",
    .fix_hint_template = NULL,
    .param_defs = NULL,
    .param_count = 0,
};

static const loom_error_param_def_t loom_err_parse_006_params[] = {
    {"op_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_006 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 6,
    .summary = "Unknown op name.",
    .message_template = "unknown op '{op_name}'",
    .fix_hint_template =
        "Check that the dialect is registered and the op name is spelled "
        "correctly",
    .param_defs = loom_err_parse_006_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_007_params[] = {
    {"type_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_007 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 7,
    .summary = "Unknown type name.",
    .message_template = "unknown type '{type_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_007_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_008_params[] = {
    {"encoding_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_008 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 8,
    .summary = "Unknown encoding.",
    .message_template = "unknown encoding '{encoding_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_008_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_009_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"expected_count", LOOM_PARAM_U32},
    {"actual_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_parse_009 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 9,
    .summary = "Result count mismatch.",
    .message_template =
        "op '{op_name}' expects {expected_count} results, got {actual_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_009_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_parse_010_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"expected_count", LOOM_PARAM_U32},
    {"actual_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_parse_010 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 10,
    .summary = "Operand count mismatch.",
    .message_template =
        "op '{op_name}' expects {expected_count} operands, got {actual_count}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_010_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_parse_011_params[] = {
    {"detail", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_011 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 11,
    .summary = "Invalid location syntax.",
    .message_template = "malformed loc() annotation: {detail}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_011_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_012_params[] = {
    {"error_count", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_parse_012 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 12,
    .summary = "Too many errors.",
    .message_template = "too many errors ({error_count}), stopping",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_012_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_013_params[] = {
    {"predicate_name", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_013 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 13,
    .summary = "Unknown predicate kind.",
    .message_template = "unknown predicate '{predicate_name}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_013_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_014_params[] = {
    {"detail", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_014 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 14,
    .summary = "Invalid encoding alias.",
    .message_template = "invalid encoding alias definition: {detail}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_014_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_015_params[] = {
    {"text", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_015 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 15,
    .summary = "Invalid integer literal.",
    .message_template = "invalid integer literal '{text}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_015_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_016_params[] = {
    {"text", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_016 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 16,
    .summary = "Invalid float literal.",
    .message_template = "invalid float literal '{text}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_016_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_parse_017_params[] = {
    {"enum_name", LOOM_PARAM_STRING},
    {"value", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_017 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 17,
    .summary = "Unknown enum value.",
    .message_template = "unknown {enum_name} value '{value}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_017_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_parse_018_params[] = {
    {"context", LOOM_PARAM_STRING},
    {"value", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_parse_018 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 18,
    .summary = "Unknown flag or modifier.",
    .message_template = "unknown {context} '{value}'",
    .fix_hint_template = NULL,
    .param_defs = loom_err_parse_018_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_parse_019_params[] = {
    {"byte_offset", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_parse_019 = {
    .domain = LOOM_ERROR_DOMAIN_PARSE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 19,
    .summary = "Source contains invalid UTF-8.",
    .message_template = "invalid UTF-8 byte sequence at offset {byte_offset}",
    .fix_hint_template = "The source file must be valid UTF-8",
    .param_defs = loom_err_parse_019_params,
    .param_count = 1,
};

static const loom_error_param_def_t loom_err_bytecode_001_params[] = {
    {"expected_magic", LOOM_PARAM_STRING},
    {"actual_magic", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_bytecode_001 = {
    .domain = LOOM_ERROR_DOMAIN_BYTECODE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 1,
    .summary = "Invalid magic bytes.",
    .message_template =
        "invalid magic bytes: expected {expected_magic}, got {actual_magic}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_bytecode_001_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_bytecode_002_params[] = {
    {"actual_version", LOOM_PARAM_U32},
    {"expected_version", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_bytecode_002 = {
    .domain = LOOM_ERROR_DOMAIN_BYTECODE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 2,
    .summary = "Unsupported format version.",
    .message_template =
        "unsupported format version {actual_version}, expected "
        "{expected_version}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_bytecode_002_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_bytecode_003_params[] = {
    {"offset", LOOM_PARAM_U32},
    {"needed_bytes", LOOM_PARAM_U32},
    {"available_bytes", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_bytecode_003 = {
    .domain = LOOM_ERROR_DOMAIN_BYTECODE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 3,
    .summary = "Unexpected end of data.",
    .message_template =
        "unexpected end of data at offset {offset}, need {needed_bytes} bytes "
        "but only {available_bytes} remain",
    .fix_hint_template = NULL,
    .param_defs = loom_err_bytecode_003_params,
    .param_count = 3,
};

static const loom_error_param_def_t loom_err_bytecode_004_params[] = {
    {"type_kind", LOOM_PARAM_U32},
    {"offset", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_bytecode_004 = {
    .domain = LOOM_ERROR_DOMAIN_BYTECODE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 4,
    .summary = "Unknown type kind.",
    .message_template = "unknown type kind {type_kind} at offset {offset}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_bytecode_004_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_bytecode_005_params[] = {
    {"attr_kind", LOOM_PARAM_U32},
    {"offset", LOOM_PARAM_U32},
};
const loom_error_def_t loom_err_bytecode_005 = {
    .domain = LOOM_ERROR_DOMAIN_BYTECODE,
    .severity = LOOM_DIAGNOSTIC_ERROR,
    .code = 5,
    .summary = "Unknown attribute kind.",
    .message_template = "unknown attribute kind {attr_kind} at offset {offset}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_bytecode_005_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_fold_001_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"reason", LOOM_PARAM_STRING},
};
const loom_error_def_t loom_err_fold_001 = {
    .domain = LOOM_ERROR_DOMAIN_FOLD,
    .severity = LOOM_DIAGNOSTIC_REMARK,
    .code = 1,
    .summary = "Operation folded to poison.",
    .message_template = "'{op_name}' folded to poison: {reason}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_fold_001_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_fold_002_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"source_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_fold_002 = {
    .domain = LOOM_ERROR_DOMAIN_FOLD,
    .severity = LOOM_DIAGNOSTIC_REMARK,
    .code = 2,
    .summary = "Slice source operand is poison.",
    .message_template =
        "'{op_name}' folded to poison: source operand is poison",
    .fix_hint_template = NULL,
    .param_defs = loom_err_fold_002_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_fold_003_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"target_type", LOOM_PARAM_TYPE},
};
const loom_error_def_t loom_err_fold_003 = {
    .domain = LOOM_ERROR_DOMAIN_FOLD,
    .severity = LOOM_DIAGNOSTIC_REMARK,
    .code = 3,
    .summary = "Update target operand is poison.",
    .message_template =
        "'{op_name}' folded to poison: target operand is poison",
    .fix_hint_template = NULL,
    .param_defs = loom_err_fold_003_params,
    .param_count = 2,
};

static const loom_error_param_def_t loom_err_fold_004_params[] = {
    {"op_name", LOOM_PARAM_STRING}, {"dim_index", LOOM_PARAM_I64},
    {"offset", LOOM_PARAM_I64},     {"size", LOOM_PARAM_I64},
    {"total", LOOM_PARAM_I64},      {"bound", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_fold_004 = {
    .domain = LOOM_ERROR_DOMAIN_FOLD,
    .severity = LOOM_DIAGNOSTIC_REMARK,
    .code = 4,
    .summary = "Subrange access extends beyond bounds.",
    .message_template =
        "'{op_name}' folded to poison: dimension {dim_index} access at offset "
        "{offset} + size {size} = {total} exceeds bound {bound}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_fold_004_params,
    .param_count = 6,
};

static const loom_error_param_def_t loom_err_fold_005_params[] = {
    {"op_name", LOOM_PARAM_STRING},
    {"dim_index", LOOM_PARAM_I64},
    {"offset", LOOM_PARAM_I64},
};
const loom_error_def_t loom_err_fold_005 = {
    .domain = LOOM_ERROR_DOMAIN_FOLD,
    .severity = LOOM_DIAGNOSTIC_REMARK,
    .code = 5,
    .summary = "Subrange access has negative offset.",
    .message_template =
        "'{op_name}' folded to poison: dimension {dim_index} has negative "
        "offset {offset}",
    .fix_hint_template = NULL,
    .param_defs = loom_err_fold_005_params,
    .param_count = 3,
};

static const loom_error_def_t* const loom_all_error_defs[] = {
    &loom_err_type_001,      &loom_err_type_002,      &loom_err_type_003,
    &loom_err_type_004,      &loom_err_type_005,      &loom_err_type_006,
    &loom_err_type_007,      &loom_err_type_008,      &loom_err_type_009,
    &loom_err_shape_001,     &loom_err_shape_002,     &loom_err_shape_003,
    &loom_err_shape_004,     &loom_err_shape_005,     &loom_err_subrange_001,
    &loom_err_subrange_002,  &loom_err_subrange_003,  &loom_err_subrange_004,
    &loom_err_encoding_001,  &loom_err_encoding_002,  &loom_err_encoding_003,
    &loom_err_encoding_004,  &loom_err_encoding_005,  &loom_err_structure_001,
    &loom_err_structure_002, &loom_err_structure_003, &loom_err_structure_004,
    &loom_err_structure_005, &loom_err_structure_006, &loom_err_structure_007,
    &loom_err_structure_008, &loom_err_structure_009, &loom_err_structure_010,
    &loom_err_structure_011, &loom_err_dominance_001, &loom_err_dominance_002,
    &loom_err_dominance_003, &loom_err_dominance_004, &loom_err_dominance_005,
    &loom_err_symbol_001,    &loom_err_parse_001,     &loom_err_parse_002,
    &loom_err_parse_003,     &loom_err_parse_004,     &loom_err_parse_005,
    &loom_err_parse_006,     &loom_err_parse_007,     &loom_err_parse_008,
    &loom_err_parse_009,     &loom_err_parse_010,     &loom_err_parse_011,
    &loom_err_parse_012,     &loom_err_parse_013,     &loom_err_parse_014,
    &loom_err_parse_015,     &loom_err_parse_016,     &loom_err_parse_017,
    &loom_err_parse_018,     &loom_err_parse_019,     &loom_err_bytecode_001,
    &loom_err_bytecode_002,  &loom_err_bytecode_003,  &loom_err_bytecode_004,
    &loom_err_bytecode_005,  &loom_err_fold_001,      &loom_err_fold_002,
    &loom_err_fold_003,      &loom_err_fold_004,      &loom_err_fold_005,
};

const loom_error_def_t* loom_error_def_lookup(loom_error_domain_t domain,
                                              uint16_t code) {
  for (iree_host_size_t i = 0; i < IREE_ARRAYSIZE(loom_all_error_defs); ++i) {
    if (loom_all_error_defs[i]->domain == domain &&
        loom_all_error_defs[i]->code == code) {
      return loom_all_error_defs[i];
    }
  }
  return NULL;
}
