# Generated by loom/build_tools/amdgpu/target_config.py.
# Do not edit directly; edit Loom AMDGPU target-info rows and regenerate.
# Output: loom/build_tools/amdgpu/target_config.bzl

"""Generated Loom AMDGPU target configuration data."""

LOOM_AMDGPU_TARGET_SOURCE_LOOM_DEFAULTS = "loom_defaults"

LOOM_AMDGPU_TARGET_SOURCE_IREE_HAL = "iree_hal"

LOOM_AMDGPU_TARGET_SOURCE_SELECTORS = [
    "loom_defaults",
    "iree_hal",
]

LOOM_AMDGPU_DEFAULT_TARGET_SELECTORS = [
    "loom_defaults",
]

LOOM_AMDGPU_SUPPORTED_PROCESSORS = [
    "gfx942",
    "gfx950",
    "gfx1100",
    "gfx1200",
    "gfx1250",
]

LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITIES = [
    "descriptor_set_cdna3_core",
    "descriptor_set_cdna4_core",
    "descriptor_set_rdna3_core",
    "descriptor_set_rdna4_core",
    "descriptor_set_rdna4_gfx125x_core",
]

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITY_BY_KEY = {
    "amdgpu.cdna3.core": "descriptor_set_cdna3_core",
    "amdgpu.cdna4.core": "descriptor_set_cdna4_core",
    "amdgpu.rdna3.core": "descriptor_set_rdna3_core",
    "amdgpu.rdna4.core": "descriptor_set_rdna4_core",
    "amdgpu.rdna4.gfx125x.core": "descriptor_set_rdna4_gfx125x_core",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_PROCESSORS = {
    "descriptor_set_cdna3_core": ["gfx942"],
    "descriptor_set_cdna4_core": ["gfx950"],
    "descriptor_set_rdna3_core": ["gfx1100"],
    "descriptor_set_rdna4_core": ["gfx1200"],
    "descriptor_set_rdna4_gfx125x_core": ["gfx1250"],
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_GENERATOR_TARGETS = {
    "descriptor_set_cdna3_core": "cdna3",
    "descriptor_set_cdna4_core": "cdna4",
    "descriptor_set_rdna3_core": "rdna3",
    "descriptor_set_rdna4_core": "rdna4",
    "descriptor_set_rdna4_gfx125x_core": "rdna4_gfx125x",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_LOW_DESCRIPTOR_HEADERS = {
    "descriptor_set_cdna3_core": "loom/target/arch/amdgpu/descriptors/cdna3_descriptors.h",
    "descriptor_set_cdna4_core": "loom/target/arch/amdgpu/descriptors/cdna4_descriptors.h",
    "descriptor_set_rdna3_core": "loom/target/arch/amdgpu/descriptors/rdna3_descriptors.h",
    "descriptor_set_rdna4_core": "loom/target/arch/amdgpu/descriptors/rdna4_descriptors.h",
    "descriptor_set_rdna4_gfx125x_core": "loom/target/arch/amdgpu/descriptors/rdna4_gfx125x_descriptors.h",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_LOW_DESCRIPTOR_PROVIDER_SYMBOLS = {
    "descriptor_set_cdna3_core": "loom_amdgpu_cdna3_core_descriptor_set",
    "descriptor_set_cdna4_core": "loom_amdgpu_cdna4_core_descriptor_set",
    "descriptor_set_rdna3_core": "loom_amdgpu_rdna3_core_descriptor_set",
    "descriptor_set_rdna4_core": "loom_amdgpu_rdna4_core_descriptor_set",
    "descriptor_set_rdna4_gfx125x_core": "loom_amdgpu_rdna4_gfx125x_core_descriptor_set",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_DEFINES = {
    "descriptor_set_cdna3_core": "LOOM_AMDGPU_DESCRIPTOR_SET_CDNA3_CORE",
    "descriptor_set_cdna4_core": "LOOM_AMDGPU_DESCRIPTOR_SET_CDNA4_CORE",
    "descriptor_set_rdna3_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA3_CORE",
    "descriptor_set_rdna4_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA4_CORE",
    "descriptor_set_rdna4_gfx125x_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA4_GFX125X_CORE",
}
