// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_KERNEL_OPS_H_
#define LOOM_OPS_KERNEL_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_KERNEL_BARRIER = LOOM_OP_KIND(LOOM_DIALECT_KERNEL, 0),
  LOOM_OP_KERNEL_COUNT_ = 1,
};

// Target-independent memory space fenced by a kernel synchronization op.
typedef enum loom_kernel_barrier_memory_space_e {
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_UNKNOWN = 0,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_GLOBAL = 1,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_WORKGROUP = 2,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_PRIVATE = 3,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_CONSTANT = 4,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_HOST = 5,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_DESCRIPTOR = 6,
  LOOM_KERNEL_BARRIER_MEMORY_SPACE_COUNT_ = 7,
} loom_kernel_barrier_memory_space_t;

// Target-independent memory ordering for kernel synchronization ops.
typedef enum loom_kernel_barrier_ordering_e {
  LOOM_KERNEL_BARRIER_ORDERING_RELAXED = 0,
  LOOM_KERNEL_BARRIER_ORDERING_ACQUIRE = 1,
  LOOM_KERNEL_BARRIER_ORDERING_RELEASE = 2,
  LOOM_KERNEL_BARRIER_ORDERING_ACQ_REL = 3,
  LOOM_KERNEL_BARRIER_ORDERING_SEQ_CST = 4,
  LOOM_KERNEL_BARRIER_ORDERING_COUNT_ = 5,
} loom_kernel_barrier_ordering_t;

// Target-independent synchronization scope.
typedef enum loom_kernel_barrier_scope_e {
  LOOM_KERNEL_BARRIER_SCOPE_THREAD = 0,
  LOOM_KERNEL_BARRIER_SCOPE_SUBGROUP = 1,
  LOOM_KERNEL_BARRIER_SCOPE_WORKGROUP = 2,
  LOOM_KERNEL_BARRIER_SCOPE_DEVICE = 3,
  LOOM_KERNEL_BARRIER_SCOPE_SYSTEM = 4,
  LOOM_KERNEL_BARRIER_SCOPE_COUNT_ = 5,
} loom_kernel_barrier_scope_t;

// LOOM_OP_KERNEL_BARRIER: Synchronize invocations in an explicit execution scope and fence a named memory space with a required ordering. The initial supported form is a workgroup barrier over workgroup memory with acquire-release ordering; other enum cases are reserved until their lowering and legality rules are implemented.
// kernel.barrier {memory_space = workgroup, ordering = acq_rel, scope = workgroup}
LOOM_DEFINE_ISA(loom_kernel_barrier_isa, LOOM_OP_KERNEL_BARRIER)
LOOM_DEFINE_ATTR_ENUM(loom_kernel_barrier_memory_space, 0)
LOOM_DEFINE_ATTR_ENUM(loom_kernel_barrier_ordering, 1)
LOOM_DEFINE_ATTR_ENUM(loom_kernel_barrier_scope, 2)
iree_status_t loom_kernel_barrier_build(
    loom_builder_t* builder,
    uint8_t memory_space,
    uint8_t ordering,
    uint8_t scope,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_kernel_barrier_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the kernel dialect.
const loom_op_vtable_t* const* loom_kernel_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_KERNEL_OPS_H_
