// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_LOW_OPS_H_
#define LOOM_OPS_LOW_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_LOW_FUNC_DEF = LOOM_OP_KIND(LOOM_DIALECT_LOW, 0),
  LOOM_OP_LOW_FUNC_DECL = LOOM_OP_KIND(LOOM_DIALECT_LOW, 1),
  LOOM_OP_LOW_RETURN = LOOM_OP_KIND(LOOM_DIALECT_LOW, 2),
  LOOM_OP_LOW_OP = LOOM_OP_KIND(LOOM_DIALECT_LOW, 3),
  LOOM_OP_LOW_CONST = LOOM_OP_KIND(LOOM_DIALECT_LOW, 4),
  LOOM_OP_LOW_COPY = LOOM_OP_KIND(LOOM_DIALECT_LOW, 5),
  LOOM_OP_LOW_SLICE = LOOM_OP_KIND(LOOM_DIALECT_LOW, 6),
  LOOM_OP_LOW_CONCAT = LOOM_OP_KIND(LOOM_DIALECT_LOW, 7),
  LOOM_OP_LOW_INVOKE = LOOM_OP_KIND(LOOM_DIALECT_LOW, 8),
  LOOM_OP_LOW_ABI_ADAPTER = LOOM_OP_KIND(LOOM_DIALECT_LOW, 9),
  LOOM_OP_LOW_ABI_OPERAND = LOOM_OP_KIND(LOOM_DIALECT_LOW, 10),
  LOOM_OP_LOW_ABI_RESULT = LOOM_OP_KIND(LOOM_DIALECT_LOW, 11),
  LOOM_OP_LOW_ABI_EFFECT = LOOM_OP_KIND(LOOM_DIALECT_LOW, 12),
  LOOM_OP_LOW_ABI_CLOBBER = LOOM_OP_KIND(LOOM_DIALECT_LOW, 13),
  LOOM_OP_LOW_SLOT = LOOM_OP_KIND(LOOM_DIALECT_LOW, 14),
  LOOM_OP_LOW_SPILL = LOOM_OP_KIND(LOOM_DIALECT_LOW, 15),
  LOOM_OP_LOW_RELOAD = LOOM_OP_KIND(LOOM_DIALECT_LOW, 16),
  LOOM_OP_LOW_FRAME_INDEX = LOOM_OP_KIND(LOOM_DIALECT_LOW, 17),
  LOOM_OP_LOW_BR = LOOM_OP_KIND(LOOM_DIALECT_LOW, 18),
  LOOM_OP_LOW_COND_BR = LOOM_OP_KIND(LOOM_DIALECT_LOW, 19),
  LOOM_OP_LOW_RESOURCE = LOOM_OP_KIND(LOOM_DIALECT_LOW, 20),
  LOOM_OP_LOW_ABI_RESOURCE = LOOM_OP_KIND(LOOM_DIALECT_LOW, 21),
  LOOM_OP_LOW_LIVE_IN = LOOM_OP_KIND(LOOM_DIALECT_LOW, 22),
  LOOM_OP_LOW_COUNT_ = 23,
};

// Function visibility. Absent (0) means private (module-internal).
typedef enum loom_low_visibility_e {
  LOOM_LOW_VISIBILITY_PUBLIC = 1,
  LOOM_LOW_VISIBILITY_COUNT_ = 2,
} loom_low_visibility_t;

// Function calling convention. Absent (0) means host.
typedef enum loom_low_cc_e {
  LOOM_LOW_CC_HOST = 1,
  LOOM_LOW_CC_DEVICE = 2,
  LOOM_LOW_CC_INITIALIZER = 3,
  LOOM_LOW_CC_DEINITIALIZER = 4,
  LOOM_LOW_CC_COUNT_ = 5,
} loom_low_cc_t;

// Function purity. Absent (0) means unspecified (conservative).
typedef enum loom_low_purity_e {
  LOOM_LOW_PURITY_PURE = 1,
  LOOM_LOW_PURITY_COUNT_ = 2,
} loom_low_purity_t;

// Register allocation exactness mode for a low function. Absent means virtual.
typedef enum loom_low_allocation_e {
  LOOM_LOW_ALLOCATION_VIRTUAL = 1,
  LOOM_LOW_ALLOCATION_ASSIGNED = 2,
  LOOM_LOW_ALLOCATION_FIXED = 3,
  LOOM_LOW_ALLOCATION_COUNT_ = 4,
} loom_low_allocation_t;

// Instruction scheduling exactness mode for a low function. Absent means free.
typedef enum loom_low_schedule_e {
  LOOM_LOW_SCHEDULE_FREE = 1,
  LOOM_LOW_SCHEDULE_CONSTRAINED = 2,
  LOOM_LOW_SCHEDULE_LOCKED = 3,
  LOOM_LOW_SCHEDULE_COUNT_ = 4,
} loom_low_schedule_t;

// External code source kind for an imported low function declaration.
typedef enum loom_low_import_kind_e {
  LOOM_LOW_IMPORT_KIND_VM = 1,
  LOOM_LOW_IMPORT_KIND_NATIVE = 2,
  LOOM_LOW_IMPORT_KIND_ROCASM = 3,
  LOOM_LOW_IMPORT_KIND_OBJECT = 4,
  LOOM_LOW_IMPORT_KIND_COUNT_ = 5,
} loom_low_import_kind_t;

// Per-slot conversion rule used by low ABI adapter mapping records.
typedef enum loom_low_conversion_e {
  LOOM_LOW_CONVERSION_DIRECT = 0,
  LOOM_LOW_CONVERSION_SCALAR_TO_REGISTER = 1,
  LOOM_LOW_CONVERSION_REGISTER_TO_SCALAR = 2,
  LOOM_LOW_CONVERSION_VALUE_TO_REGISTER = 3,
  LOOM_LOW_CONVERSION_REGISTER_TO_VALUE = 4,
  LOOM_LOW_CONVERSION_COUNT_ = 5,
} loom_low_conversion_t;

// Semantic-to-low ABI conversion rule used by a low ABI adapter record.
typedef enum loom_low_abi_adapter_conversion_e {
  LOOM_LOW_ABI_ADAPTER_CONVERSION_DIRECT = 0,
  LOOM_LOW_ABI_ADAPTER_CONVERSION_MAPPED = 1,
  LOOM_LOW_ABI_ADAPTER_CONVERSION_COUNT_ = 2,
} loom_low_abi_adapter_conversion_t;

// Effect summary row attached to a low ABI adapter.
typedef enum loom_low_abi_effect_kind_e {
  LOOM_LOW_ABI_EFFECT_KIND_READ = 1,
  LOOM_LOW_ABI_EFFECT_KIND_WRITE = 2,
  LOOM_LOW_ABI_EFFECT_KIND_READWRITE = 3,
  LOOM_LOW_ABI_EFFECT_KIND_CALL = 4,
  LOOM_LOW_ABI_EFFECT_KIND_UNKNOWN = 5,
  LOOM_LOW_ABI_EFFECT_KIND_COUNT_ = 6,
} loom_low_abi_effect_kind_t;

// Storage space represented by a low slot record.
typedef enum loom_low_slot_space_e {
  LOOM_LOW_SLOT_SPACE_STACK = 1,
  LOOM_LOW_SLOT_SPACE_SCRATCH = 2,
  LOOM_LOW_SLOT_SPACE_PRIVATE = 3,
  LOOM_LOW_SLOT_SPACE_LDS = 4,
  LOOM_LOW_SLOT_SPACE_COUNT_ = 5,
} loom_low_slot_space_t;

// Target ABI resource imported into a low function body.
typedef enum loom_low_abi_resource_kind_e {
  LOOM_LOW_ABI_RESOURCE_KIND_NATIVE_POINTER = 1,
  LOOM_LOW_ABI_RESOURCE_KIND_VM_STATE = 2,
  LOOM_LOW_ABI_RESOURCE_KIND_VM_IMPORT = 3,
  LOOM_LOW_ABI_RESOURCE_KIND_HAL_BUFFER_RESOURCE = 4,
  LOOM_LOW_ABI_RESOURCE_KIND_COUNT_ = 5,
} loom_low_abi_resource_kind_t;

// LOOM_OP_LOW_FUNC_DEF: Target-bound low function definition with register-typed signature values.
// low.func.def target(@gfx1100) @add(%lhs: reg<amdgpu.vgpr x1>, %rhs: reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>) {
//   %sum = low.op<amdgpu.v_add_u32>(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> reg<amdgpu.vgpr x1>
//   low.return %sum : reg<amdgpu.vgpr x1>
// }
LOOM_DEFINE_ISA(loom_low_func_def_isa, LOOM_OP_LOW_FUNC_DEF)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_func_def_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_def_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_def_target, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_visibility, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_cc, 3)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_purity, 4)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_allocation, 5)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_schedule, 6)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_import_kind, 7)
LOOM_DEFINE_ATTR_STRING(loom_low_func_def_code_symbol, 8)
LOOM_DEFINE_REGION(loom_low_func_def_body, 0)
enum loom_low_func_def_build_flag_bits_e {
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_VISIBILITY = 1u << 0,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_CC = 1u << 1,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_PURITY = 1u << 2,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_ALLOCATION = 1u << 3,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_SCHEDULE = 1u << 4,
};
typedef uint32_t loom_low_func_def_build_flags_t;
iree_status_t loom_low_func_def_build(
    loom_builder_t* builder,
    loom_low_func_def_build_flags_t build_flags,
    loom_optional uint8_t visibility,
    loom_optional uint8_t cc,
    loom_optional uint8_t purity,
    loom_optional uint8_t allocation,
    loom_optional uint8_t schedule,
    loom_symbol_ref_t target,
    loom_symbol_ref_t callee,
    const loom_type_t* arg_types,
    iree_host_size_t arg_types_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_func_def_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_FUNC_DECL: Target-bound low function declaration with register-typed signature values.
// low.func.decl target(@gfx1100) @extern_add(%lhs: reg<amdgpu.vgpr x1>, %rhs: reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>)
LOOM_DEFINE_ISA(loom_low_func_decl_isa, LOOM_OP_LOW_FUNC_DECL)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_func_decl_args, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_func_decl_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_decl_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_decl_target, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_visibility, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_cc, 3)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_purity, 4)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_allocation, 5)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_schedule, 6)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_import_kind, 7)
LOOM_DEFINE_ATTR_STRING(loom_low_func_decl_code_symbol, 8)
enum loom_low_func_decl_build_flag_bits_e {
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_VISIBILITY = 1u << 0,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_CC = 1u << 1,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_PURITY = 1u << 2,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_ALLOCATION = 1u << 3,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_SCHEDULE = 1u << 4,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_IMPORT_KIND = 1u << 5,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_CODE_SYMBOL = 1u << 6,
};
typedef uint32_t loom_low_func_decl_build_flags_t;
iree_status_t loom_low_func_decl_build(
    loom_builder_t* builder,
    loom_low_func_decl_build_flags_t build_flags,
    loom_optional uint8_t visibility,
    loom_optional uint8_t cc,
    loom_optional uint8_t purity,
    loom_optional uint8_t allocation,
    loom_optional uint8_t schedule,
    loom_optional uint8_t import_kind,
    loom_optional loom_string_id_t code_symbol,
    loom_symbol_ref_t target,
    loom_symbol_ref_t callee,
    const loom_type_t* arg_types,
    iree_host_size_t arg_types_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_func_decl_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_RETURN: Return register values from a low function.
// low.return
LOOM_DEFINE_ISA(loom_low_return_isa, LOOM_OP_LOW_RETURN)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_return_values, 0)
iree_status_t loom_low_return_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_OP: Descriptor-backed target instruction over virtual registers.
// %sum = low.op<amdgpu.v_add_u32>(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> reg<amdgpu.vgpr x1>
LOOM_DEFINE_ISA(loom_low_op_isa, LOOM_OP_LOW_OP)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_op_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_op_results, 0)
LOOM_DEFINE_ATTR_STRING(loom_low_op_opcode, 0)
LOOM_DEFINE_ATTR_DICT(loom_low_op_attrs, 1)
iree_status_t loom_low_op_build(
    loom_builder_t* builder,
    loom_string_id_t opcode,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    loom_optional loom_named_attr_slice_t attrs,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_op_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_CONST: Descriptor-backed constant or immediate materialization into a register.
// %c0 = low.const<amdgpu.s_mov_b32> {imm = 0} : reg<amdgpu.sgpr x1>
LOOM_DEFINE_ISA(loom_low_const_isa, LOOM_OP_LOW_CONST)
LOOM_DEFINE_RESULT(loom_low_const_result, 0)
LOOM_DEFINE_ATTR_STRING(loom_low_const_opcode, 0)
LOOM_DEFINE_ATTR_DICT(loom_low_const_attrs, 1)
iree_status_t loom_low_const_build(
    loom_builder_t* builder,
    loom_string_id_t opcode,
    loom_optional loom_named_attr_slice_t attrs,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_const_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_COPY: Explicit virtual-register copy used by lowering and allocation.
// %copy = low.copy %value : reg<amdgpu.vgpr x1> -> reg<amdgpu.vgpr x1>
LOOM_DEFINE_ISA(loom_low_copy_isa, LOOM_OP_LOW_COPY)
LOOM_DEFINE_OPERAND(loom_low_copy_source, 0)
LOOM_DEFINE_RESULT(loom_low_copy_result, 0)
iree_status_t loom_low_copy_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_copy_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_SLICE: Project a contiguous subrange from a register-range value.
// %lane = low.slice %quad[2] : reg<amdgpu.vgpr x4> -> reg<amdgpu.vgpr>
LOOM_DEFINE_ISA(loom_low_slice_isa, LOOM_OP_LOW_SLICE)
LOOM_DEFINE_OPERAND(loom_low_slice_source, 0)
LOOM_DEFINE_RESULT(loom_low_slice_result, 0)
LOOM_DEFINE_ATTR_I64(loom_low_slice_offset, 0)
iree_status_t loom_low_slice_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    int64_t offset,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_slice_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_CONCAT: Compose one register-range value from ordered register subranges.
// %pair = low.concat(%lo, %hi) : (reg<amdgpu.sgpr>, reg<amdgpu.sgpr>) -> reg<amdgpu.sgpr x2>
LOOM_DEFINE_ISA(loom_low_concat_isa, LOOM_OP_LOW_CONCAT)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_concat_sources, 0)
LOOM_DEFINE_RESULT(loom_low_concat_result, 0)
iree_status_t loom_low_concat_build(
    loom_builder_t* builder,
    loom_may_consume const loom_value_id_t* sources,
    iree_host_size_t sources_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_INVOKE: Call or interop edge to a low function symbol.
// %result = low.invoke @extern_add(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>)
LOOM_DEFINE_ISA(loom_low_invoke_isa, LOOM_OP_LOW_INVOKE)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_invoke_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_invoke_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_invoke_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_invoke_adapter, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_invoke_purity, 2)
enum loom_low_invoke_build_flag_bits_e {
  LOOM_LOW_INVOKE_BUILD_FLAG_HAS_PURITY = 1u << 0,
  LOOM_LOW_INVOKE_BUILD_FLAG_HAS_ADAPTER = 1u << 1,
};
typedef uint32_t loom_low_invoke_build_flags_t;
iree_status_t loom_low_invoke_build(
    loom_builder_t* builder,
    loom_low_invoke_build_flags_t build_flags,
    loom_optional uint8_t purity,
    loom_symbol_ref_t callee,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    loom_optional loom_symbol_ref_t adapter,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
loom_trait_flags_t loom_low_invoke_effective_traits(const loom_op_t* op);
iree_status_t loom_low_invoke_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_ADAPTER: Explicit adapter record for calls crossing from semantic Loom values into a low function register ABI.
// low.abi.adapter @extern_add_direct {callee = @extern_add, conversion = direct, operand_count = 2, result_count = 1}
LOOM_DEFINE_ISA(loom_low_abi_adapter_isa, LOOM_OP_LOW_ABI_ADAPTER)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_adapter_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_adapter_callee, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_adapter_conversion, 2)
LOOM_DEFINE_ATTR_I64(loom_low_abi_adapter_operand_count, 3)
LOOM_DEFINE_ATTR_I64(loom_low_abi_adapter_result_count, 4)
iree_status_t loom_low_abi_adapter_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t callee,
    uint8_t conversion,
    int64_t operand_count,
    int64_t result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_adapter_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_OPERAND: Mapped low ABI adapter operand slot from semantic value type to callee register ABI type.
// low.abi.operand @extern_add_i32_lhs {adapter = @extern_add_i32, index = 0, conversion = scalar_to_register, semantic_type = i32, abi_type = reg<vm.i32>}
LOOM_DEFINE_ISA(loom_low_abi_operand_isa, LOOM_OP_LOW_ABI_OPERAND)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_operand_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_operand_adapter, 1)
LOOM_DEFINE_ATTR_I64(loom_low_abi_operand_index, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_operand_conversion, 3)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_operand_semantic_type, 4)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_operand_abi_type, 5)
iree_status_t loom_low_abi_operand_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    int64_t index,
    uint8_t conversion,
    uint32_t semantic_type,
    uint32_t abi_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_operand_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_RESULT: Mapped low ABI adapter result slot from callee register ABI type to semantic value type.
// low.abi.result @extern_add_i32_result {adapter = @extern_add_i32, index = 0, conversion = register_to_scalar, semantic_type = i32, abi_type = reg<vm.i32>}
LOOM_DEFINE_ISA(loom_low_abi_result_isa, LOOM_OP_LOW_ABI_RESULT)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_result_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_result_adapter, 1)
LOOM_DEFINE_ATTR_I64(loom_low_abi_result_index, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_result_conversion, 3)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_result_semantic_type, 4)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_result_abi_type, 5)
iree_status_t loom_low_abi_result_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    int64_t index,
    uint8_t conversion,
    uint32_t semantic_type,
    uint32_t abi_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_result_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_EFFECT: Resource effect exposed by a low ABI adapter to semantic callers.
// low.abi.effect @extern_add_call {adapter = @extern_add_i32, kind = call, resource = "vm.import"}
LOOM_DEFINE_ISA(loom_low_abi_effect_isa, LOOM_OP_LOW_ABI_EFFECT)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_effect_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_effect_adapter, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_effect_kind, 2)
LOOM_DEFINE_ATTR_STRING(loom_low_abi_effect_resource, 3)
enum loom_low_abi_effect_build_flag_bits_e {
  LOOM_LOW_ABI_EFFECT_BUILD_FLAG_HAS_RESOURCE = 1u << 0,
};
typedef uint32_t loom_low_abi_effect_build_flags_t;
iree_status_t loom_low_abi_effect_build(
    loom_builder_t* builder,
    loom_low_abi_effect_build_flags_t build_flags,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    uint8_t kind,
    loom_optional loom_string_id_t resource,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_effect_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_CLOBBER: Resource or register class clobbered by a low ABI adapter.
// low.abi.clobber @extern_add_vm_state {adapter = @extern_add_i32, resource = "vm.state"}
LOOM_DEFINE_ISA(loom_low_abi_clobber_isa, LOOM_OP_LOW_ABI_CLOBBER)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_clobber_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_clobber_adapter, 1)
LOOM_DEFINE_ATTR_STRING(loom_low_abi_clobber_resource, 2)
iree_status_t loom_low_abi_clobber_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    loom_string_id_t resource,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_clobber_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_SLOT: Explicit function-owned stack, scratch, private, or LDS storage slot.
// low.slot @spill0 {function = @kernel, space = scratch, size = 16, align = 4}
LOOM_DEFINE_ISA(loom_low_slot_isa, LOOM_OP_LOW_SLOT)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_slot_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_slot_function, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_slot_space, 2)
LOOM_DEFINE_ATTR_I64(loom_low_slot_size, 3)
LOOM_DEFINE_ATTR_I64(loom_low_slot_align, 4)
iree_status_t loom_low_slot_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t function,
    uint8_t space,
    int64_t size,
    int64_t align,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_slot_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_SPILL: Explicit spill store from a register value into a low slot.
// low.spill %value, @spill0 {offset = 0} : reg<amdgpu.vgpr x4>
LOOM_DEFINE_ISA(loom_low_spill_isa, LOOM_OP_LOW_SPILL)
LOOM_DEFINE_OPERAND(loom_low_spill_value, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_spill_slot, 0)
LOOM_DEFINE_ATTR_I64(loom_low_spill_offset, 1)
iree_status_t loom_low_spill_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_symbol_ref_t slot,
    int64_t offset,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_spill_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_RELOAD: Explicit reload from a low slot into a register value.
// %reload = low.reload @spill0 {offset = 0} : reg<amdgpu.vgpr x4>
LOOM_DEFINE_ISA(loom_low_reload_isa, LOOM_OP_LOW_RELOAD)
LOOM_DEFINE_RESULT(loom_low_reload_result, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_reload_slot, 0)
LOOM_DEFINE_ATTR_I64(loom_low_reload_offset, 1)
iree_status_t loom_low_reload_build(
    loom_builder_t* builder,
    loom_symbol_ref_t slot,
    int64_t offset,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_reload_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_FRAME_INDEX: Symbolic address calculation for a low slot before target frame layout.
// %addr = low.frame_index @spill0 {offset = 0} : reg<x86.gpr>
LOOM_DEFINE_ISA(loom_low_frame_index_isa, LOOM_OP_LOW_FRAME_INDEX)
LOOM_DEFINE_RESULT(loom_low_frame_index_result, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_frame_index_slot, 0)
LOOM_DEFINE_ATTR_I64(loom_low_frame_index_offset, 1)
iree_status_t loom_low_frame_index_build(
    loom_builder_t* builder,
    loom_symbol_ref_t slot,
    int64_t offset,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_frame_index_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_BR: Unconditional branch to a low successor block, forwarding register values.
// low.br ^done
LOOM_DEFINE_ISA(loom_low_br_isa, LOOM_OP_LOW_BR)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_br_args, 0)
LOOM_DEFINE_SUCCESSOR(loom_low_br_dest, 0)
iree_status_t loom_low_br_build(
    loom_builder_t* builder,
    loom_block_t* dest,
    const loom_value_id_t* args,
    iree_host_size_t args_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_br_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_COND_BR: Conditional branch to one of two low successor blocks based on a register predicate.
// low.cond_br %condition, ^then, ^else : reg<vm.i32>
LOOM_DEFINE_ISA(loom_low_cond_br_isa, LOOM_OP_LOW_COND_BR)
LOOM_DEFINE_OPERAND(loom_low_cond_br_condition, 0)
LOOM_DEFINE_SUCCESSOR(loom_low_cond_br_true_dest, 0)
LOOM_DEFINE_SUCCESSOR(loom_low_cond_br_false_dest, 1)
iree_status_t loom_low_cond_br_build(
    loom_builder_t* builder,
    loom_value_id_t condition,
    loom_block_t* true_dest,
    loom_block_t* false_dest,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_cond_br_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_RESOURCE: Import a function-owned target ABI resource into a low register value.
// %state = low.resource @vm_state : reg<vm.i64>
LOOM_DEFINE_ISA(loom_low_resource_isa, LOOM_OP_LOW_RESOURCE)
LOOM_DEFINE_RESULT(loom_low_resource_result, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_resource_resource, 0)
iree_status_t loom_low_resource_build(
    loom_builder_t* builder,
    loom_symbol_ref_t resource,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_resource_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_RESOURCE: Function-owned target ABI resource imported by low.resource.
// low.abi.resource @vm_state {function = @vm_func, kind = vm_state, index = 0, semantic_type = i64, abi_type = reg<vm.i64>}
LOOM_DEFINE_ISA(loom_low_abi_resource_isa, LOOM_OP_LOW_ABI_RESOURCE)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_resource_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_resource_function, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_resource_kind, 2)
LOOM_DEFINE_ATTR_I64(loom_low_abi_resource_index, 3)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_resource_semantic_type, 4)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_resource_abi_type, 5)
iree_status_t loom_low_abi_resource_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t function,
    uint8_t kind,
    int64_t index,
    uint32_t semantic_type,
    uint32_t abi_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_resource_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_LIVE_IN: Import a target-provided ABI live-in register value at low-function entry.
// %kernarg = low.live_in<amdgpu.kernarg_segment_ptr> : reg<amdgpu.sgpr x2>
LOOM_DEFINE_ISA(loom_low_live_in_isa, LOOM_OP_LOW_LIVE_IN)
LOOM_DEFINE_RESULT(loom_low_live_in_result, 0)
LOOM_DEFINE_ATTR_STRING(loom_low_live_in_source, 0)
LOOM_DEFINE_ATTR_DICT(loom_low_live_in_attrs, 1)
iree_status_t loom_low_live_in_build(
    loom_builder_t* builder,
    loom_string_id_t source,
    loom_optional loom_named_attr_slice_t attrs,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_live_in_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the low dialect.
const loom_op_vtable_t* const* loom_low_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_LOW_OPS_H_
