// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_LOW_OPS_H_
#define LOOM_OPS_LOW_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_LOW_FUNC_DEF = LOOM_OP_KIND(LOOM_DIALECT_LOW, 0),
  LOOM_OP_LOW_FUNC_DECL = LOOM_OP_KIND(LOOM_DIALECT_LOW, 1),
  LOOM_OP_LOW_RETURN = LOOM_OP_KIND(LOOM_DIALECT_LOW, 2),
  LOOM_OP_LOW_OP = LOOM_OP_KIND(LOOM_DIALECT_LOW, 3),
  LOOM_OP_LOW_CONST = LOOM_OP_KIND(LOOM_DIALECT_LOW, 4),
  LOOM_OP_LOW_COPY = LOOM_OP_KIND(LOOM_DIALECT_LOW, 5),
  LOOM_OP_LOW_INVOKE = LOOM_OP_KIND(LOOM_DIALECT_LOW, 6),
  LOOM_OP_LOW_ABI_ADAPTER = LOOM_OP_KIND(LOOM_DIALECT_LOW, 7),
  LOOM_OP_LOW_ABI_OPERAND = LOOM_OP_KIND(LOOM_DIALECT_LOW, 8),
  LOOM_OP_LOW_ABI_RESULT = LOOM_OP_KIND(LOOM_DIALECT_LOW, 9),
  LOOM_OP_LOW_COUNT_ = 10,
};

// Function visibility. Absent (0) means private (module-internal).
typedef enum loom_low_visibility_e {
  LOOM_LOW_VISIBILITY_PUBLIC = 1,
  LOOM_LOW_VISIBILITY_COUNT_ = 2,
} loom_low_visibility_t;

// Function calling convention. Absent (0) means host.
typedef enum loom_low_cc_e {
  LOOM_LOW_CC_HOST = 1,
  LOOM_LOW_CC_DEVICE = 2,
  LOOM_LOW_CC_INITIALIZER = 3,
  LOOM_LOW_CC_DEINITIALIZER = 4,
  LOOM_LOW_CC_COUNT_ = 5,
} loom_low_cc_t;

// Function purity. Absent (0) means unspecified (conservative).
typedef enum loom_low_purity_e {
  LOOM_LOW_PURITY_PURE = 1,
  LOOM_LOW_PURITY_COUNT_ = 2,
} loom_low_purity_t;

// Per-slot conversion rule used by low ABI adapter mapping records.
typedef enum loom_low_conversion_e {
  LOOM_LOW_CONVERSION_DIRECT = 0,
  LOOM_LOW_CONVERSION_SCALAR_TO_REGISTER = 1,
  LOOM_LOW_CONVERSION_REGISTER_TO_SCALAR = 2,
  LOOM_LOW_CONVERSION_COUNT_ = 3,
} loom_low_conversion_t;

// Semantic-to-low ABI conversion rule used by a low ABI adapter record.
typedef enum loom_low_abi_adapter_conversion_e {
  LOOM_LOW_ABI_ADAPTER_CONVERSION_DIRECT = 0,
  LOOM_LOW_ABI_ADAPTER_CONVERSION_MAPPED = 1,
  LOOM_LOW_ABI_ADAPTER_CONVERSION_COUNT_ = 2,
} loom_low_abi_adapter_conversion_t;

// LOOM_OP_LOW_FUNC_DEF: Target-bound low function definition with register-typed signature values.
// low.func.def target(@gfx1100) @add(%lhs: reg<amdgpu.vgpr x1>, %rhs: reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>) {
//   %sum = low.op<amdgpu.v_add_u32>(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> reg<amdgpu.vgpr x1>
//   low.return %sum : reg<amdgpu.vgpr x1>
// }
LOOM_DEFINE_ISA(loom_low_func_def_isa, LOOM_OP_LOW_FUNC_DEF)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_func_def_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_def_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_def_target, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_visibility, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_cc, 3)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_def_purity, 4)
LOOM_DEFINE_REGION(loom_low_func_def_body, 0)
enum loom_low_func_def_build_flag_bits_e {
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_VISIBILITY = 1u << 0,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_CC = 1u << 1,
  LOOM_LOW_FUNC_DEF_BUILD_FLAG_HAS_PURITY = 1u << 2,
};
typedef uint32_t loom_low_func_def_build_flags_t;
iree_status_t loom_low_func_def_build(
    loom_builder_t* builder,
    loom_low_func_def_build_flags_t build_flags,
    loom_optional uint8_t visibility,
    loom_optional uint8_t cc,
    loom_optional uint8_t purity,
    loom_symbol_ref_t target,
    loom_symbol_ref_t callee,
    const loom_type_t* arg_types,
    iree_host_size_t arg_types_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_FUNC_DECL: Target-bound low function declaration with register-typed signature values.
// low.func.decl target(@gfx1100) @extern_add(%lhs: reg<amdgpu.vgpr x1>, %rhs: reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>)
LOOM_DEFINE_ISA(loom_low_func_decl_isa, LOOM_OP_LOW_FUNC_DECL)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_func_decl_args, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_func_decl_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_decl_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_func_decl_target, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_visibility, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_cc, 3)
LOOM_DEFINE_ATTR_ENUM(loom_low_func_decl_purity, 4)
enum loom_low_func_decl_build_flag_bits_e {
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_VISIBILITY = 1u << 0,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_CC = 1u << 1,
  LOOM_LOW_FUNC_DECL_BUILD_FLAG_HAS_PURITY = 1u << 2,
};
typedef uint32_t loom_low_func_decl_build_flags_t;
iree_status_t loom_low_func_decl_build(
    loom_builder_t* builder,
    loom_low_func_decl_build_flags_t build_flags,
    loom_optional uint8_t visibility,
    loom_optional uint8_t cc,
    loom_optional uint8_t purity,
    loom_symbol_ref_t target,
    loom_symbol_ref_t callee,
    const loom_type_t* arg_types,
    iree_host_size_t arg_types_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_optional const loom_predicate_t* predicates,
    iree_host_size_t predicates_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_RETURN: Return register values from a low function.
// low.return
LOOM_DEFINE_ISA(loom_low_return_isa, LOOM_OP_LOW_RETURN)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_return_values, 0)
iree_status_t loom_low_return_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_OP: Descriptor-backed target instruction over virtual registers.
// %sum = low.op<amdgpu.v_add_u32>(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> reg<amdgpu.vgpr x1>
LOOM_DEFINE_ISA(loom_low_op_isa, LOOM_OP_LOW_OP)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_op_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_op_results, 0)
LOOM_DEFINE_ATTR_STRING(loom_low_op_opcode, 0)
LOOM_DEFINE_ATTR_DICT(loom_low_op_attrs, 1)
iree_status_t loom_low_op_build(
    loom_builder_t* builder,
    loom_string_id_t opcode,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    loom_optional loom_named_attr_slice_t attrs,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_op_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_CONST: Descriptor-backed constant or immediate materialization into a register.
// %c0 = low.const<amdgpu.s_mov_b32> {imm = 0} : reg<amdgpu.sgpr x1>
LOOM_DEFINE_ISA(loom_low_const_isa, LOOM_OP_LOW_CONST)
LOOM_DEFINE_RESULT(loom_low_const_result, 0)
LOOM_DEFINE_ATTR_STRING(loom_low_const_opcode, 0)
LOOM_DEFINE_ATTR_DICT(loom_low_const_attrs, 1)
iree_status_t loom_low_const_build(
    loom_builder_t* builder,
    loom_string_id_t opcode,
    loom_optional loom_named_attr_slice_t attrs,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_const_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_COPY: Explicit virtual-register copy used by lowering and allocation.
// %copy = low.copy %value : reg<amdgpu.vgpr x1> -> reg<amdgpu.vgpr x1>
LOOM_DEFINE_ISA(loom_low_copy_isa, LOOM_OP_LOW_COPY)
LOOM_DEFINE_OPERAND(loom_low_copy_source, 0)
LOOM_DEFINE_RESULT(loom_low_copy_result, 0)
iree_status_t loom_low_copy_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);

// LOOM_OP_LOW_INVOKE: Call or interop edge to a low function symbol.
// %result = low.invoke @extern_add(%lhs, %rhs) : (reg<amdgpu.vgpr x1>, reg<amdgpu.vgpr x1>) -> (reg<amdgpu.vgpr x1>)
LOOM_DEFINE_ISA(loom_low_invoke_isa, LOOM_OP_LOW_INVOKE)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_low_invoke_operands, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_low_invoke_results, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_invoke_callee, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_invoke_adapter, 1)
enum loom_low_invoke_build_flag_bits_e {
  LOOM_LOW_INVOKE_BUILD_FLAG_HAS_ADAPTER = 1u << 0,
};
typedef uint32_t loom_low_invoke_build_flags_t;
iree_status_t loom_low_invoke_build(
    loom_builder_t* builder,
    loom_low_invoke_build_flags_t build_flags,
    loom_symbol_ref_t callee,
    loom_may_consume const loom_value_id_t* operands,
    iree_host_size_t operands_count,
    loom_optional loom_symbol_ref_t adapter,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_invoke_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_ADAPTER: Explicit adapter record for calls crossing from semantic Loom values into a low function register ABI.
// low.abi.adapter @extern_add_direct {callee = @extern_add, conversion = direct, operand_count = 2, result_count = 1}
LOOM_DEFINE_ISA(loom_low_abi_adapter_isa, LOOM_OP_LOW_ABI_ADAPTER)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_adapter_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_adapter_callee, 1)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_adapter_conversion, 2)
LOOM_DEFINE_ATTR_I64(loom_low_abi_adapter_operand_count, 3)
LOOM_DEFINE_ATTR_I64(loom_low_abi_adapter_result_count, 4)
iree_status_t loom_low_abi_adapter_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t callee,
    uint8_t conversion,
    int64_t operand_count,
    int64_t result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_adapter_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_OPERAND: Mapped low ABI adapter operand slot from semantic value type to callee register ABI type.
// low.abi.operand @extern_add_i32_lhs {adapter = @extern_add_i32, index = 0, conversion = scalar_to_register, semantic_type = i32, abi_type = reg<vm.i32>}
LOOM_DEFINE_ISA(loom_low_abi_operand_isa, LOOM_OP_LOW_ABI_OPERAND)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_operand_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_operand_adapter, 1)
LOOM_DEFINE_ATTR_I64(loom_low_abi_operand_index, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_operand_conversion, 3)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_operand_semantic_type, 4)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_operand_abi_type, 5)
iree_status_t loom_low_abi_operand_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    int64_t index,
    uint8_t conversion,
    uint32_t semantic_type,
    uint32_t abi_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_operand_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_LOW_ABI_RESULT: Mapped low ABI adapter result slot from callee register ABI type to semantic value type.
// low.abi.result @extern_add_i32_result {adapter = @extern_add_i32, index = 0, conversion = register_to_scalar, semantic_type = i32, abi_type = reg<vm.i32>}
LOOM_DEFINE_ISA(loom_low_abi_result_isa, LOOM_OP_LOW_ABI_RESULT)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_result_symbol, 0)
LOOM_DEFINE_ATTR_SYMBOL(loom_low_abi_result_adapter, 1)
LOOM_DEFINE_ATTR_I64(loom_low_abi_result_index, 2)
LOOM_DEFINE_ATTR_ENUM(loom_low_abi_result_conversion, 3)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_result_semantic_type, 4)
LOOM_DEFINE_ATTR_TYPE(loom_low_abi_result_abi_type, 5)
iree_status_t loom_low_abi_result_build(
    loom_builder_t* builder,
    loom_symbol_ref_t symbol,
    loom_symbol_ref_t adapter,
    int64_t index,
    uint8_t conversion,
    uint32_t semantic_type,
    uint32_t abi_type,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_low_abi_result_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the low dialect.
const loom_op_vtable_t* const* loom_low_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_LOW_OPS_H_
