// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_SCF_OPS_H_
#define LOOM_OPS_SCF_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_SCF_FOR = LOOM_OP_KIND(LOOM_DIALECT_SCF, 0),
  LOOM_OP_SCF_IF = LOOM_OP_KIND(LOOM_DIALECT_SCF, 1),
  LOOM_OP_SCF_YIELD = LOOM_OP_KIND(LOOM_DIALECT_SCF, 2),
  LOOM_OP_SCF_COUNT_ = 3,
};

// LOOM_OP_SCF_FOR: Bounded counted loop with optional loop-carried state.
// scf.for %iv = [%c0 to %n step %c1] {
LOOM_DEFINE_ISA(loom_scf_for_isa, LOOM_OP_SCF_FOR)
LOOM_DEFINE_OPERAND(loom_scf_for_lower_bound, 0)
LOOM_DEFINE_OPERAND(loom_scf_for_upper_bound, 1)
LOOM_DEFINE_OPERAND(loom_scf_for_step, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_scf_for_iter_args, 3)
LOOM_DEFINE_VARIADIC_RESULTS(loom_scf_for_results, 0)
LOOM_DEFINE_REGION(loom_scf_for_body, 0)
iree_status_t loom_scf_for_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t lower_bound,
    loom_may_consume loom_value_id_t upper_bound,
    loom_may_consume loom_value_id_t step,
    loom_may_consume const loom_value_id_t* iter_args,
    iree_host_size_t iter_args_count,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_scf_for_canonicalize(loom_op_t* op, loom_rewriter_t* rewriter);

// LOOM_OP_SCF_IF: Conditional execution with required else region.
// scf.if %cond {
LOOM_DEFINE_ISA(loom_scf_if_isa, LOOM_OP_SCF_IF)
LOOM_DEFINE_OPERAND(loom_scf_if_condition, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_scf_if_results, 0)
LOOM_DEFINE_REGION(loom_scf_if_then_region, 0)
LOOM_DEFINE_REGION(loom_scf_if_else_region, 1)
iree_status_t loom_scf_if_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t condition,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
iree_status_t loom_scf_if_canonicalize(loom_op_t* op, loom_rewriter_t* rewriter);

// LOOM_OP_SCF_YIELD: Region terminator forwarding values to the parent scf op.
// scf.yield
LOOM_DEFINE_ISA(loom_scf_yield_isa, LOOM_OP_SCF_YIELD)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_scf_yield_values, 0)
iree_status_t loom_scf_yield_build(
    loom_builder_t* builder,
    const loom_value_id_t* values,
    iree_host_size_t values_count,
    loom_location_id_t location,
    loom_op_t** out_op);

// Returns the vtable array for the scf dialect.
const loom_op_vtable_t* const* loom_scf_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_SCF_OPS_H_
