// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_BUFFER_OPS_H_
#define LOOM_OPS_BUFFER_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_BUFFER_VIEW = LOOM_OP_KIND(LOOM_DIALECT_BUFFER, 0),
  LOOM_OP_BUFFER_COUNT_ = 1,
};

// LOOM_OP_BUFFER_VIEW: Form a typed non-owning view from an opaque buffer root and base byte offset. The result view type carries the address layout.
// %view = buffer.view %buffer[%offset] : buffer -> view<[%M]xf32, %layout>
LOOM_DEFINE_ISA(loom_buffer_view_isa, LOOM_OP_BUFFER_VIEW)
LOOM_DEFINE_OPERAND(loom_buffer_view_buffer, 0)
LOOM_DEFINE_OPERAND(loom_buffer_view_byte_offset, 1)
LOOM_DEFINE_RESULT(loom_buffer_view_result, 0)
iree_status_t loom_buffer_view_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t buffer,
    loom_may_consume loom_value_id_t byte_offset,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_buffer_view_vtable;
iree_status_t loom_buffer_view_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the buffer dialect.
const loom_op_vtable_t* const* loom_buffer_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_BUFFER_OPS_H_
