// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_VIEW_OPS_H_
#define LOOM_OPS_VIEW_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_VIEW_SUBVIEW = LOOM_OP_KIND(LOOM_DIALECT_VIEW, 0),
  LOOM_OP_VIEW_COUNT_ = 1,
};

// LOOM_OP_VIEW_SUBVIEW: Form a logical subview from an existing view. Offsets select the logical origin; result type dimensions provide the subview extents.
// %sub = view.subview %source[%row, 0] : view<[%M]x[%N]xf32, %layout> -> view<16x[%N]xf32, %layout>
LOOM_DEFINE_ISA(loom_view_subview_isa, LOOM_OP_VIEW_SUBVIEW)
LOOM_DEFINE_OPERAND(loom_view_subview_source, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_view_subview_offsets, 1)
LOOM_DEFINE_RESULT(loom_view_subview_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_view_subview_static_offsets, 0)
iree_status_t loom_view_subview_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    const loom_value_id_t* offsets,
    iree_host_size_t offsets_count,
    const int64_t* static_offsets,
    iree_host_size_t static_offsets_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_view_subview_vtable;
iree_status_t loom_view_subview_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the view dialect.
const loom_op_vtable_t* const* loom_view_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_VIEW_OPS_H_
