# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, ValueRef
from loom.ir import Predicate, Region, Type


class ScalarBuilders:
    """Typed builder methods for scalar ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def addi(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer addition.

        Example::
            %result = scalar.addi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.addi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def subi(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer subtraction.

        Example::
            %result = scalar.subi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.subi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def muli(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer multiplication.

        Example::
            %result = scalar.muli %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.muli", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def divsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer division (rounds toward zero).

        Example::
            %result = scalar.divsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.divsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def divui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer division.

        Example::
            %result = scalar.divui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.divui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def remsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer remainder.

        Example::
            %result = scalar.remsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.remsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def remui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer remainder.

        Example::
            %result = scalar.remui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.remui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ceildivsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer division, rounding toward positive infinity.

        Example::
            %result = scalar.ceildivsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.ceildivsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ceildivui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer division, rounding toward positive infinity.

        Example::
            %result = scalar.ceildivui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.ceildivui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def floordivsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer division, rounding toward negative infinity.

        Example::
            %result = scalar.floordivsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.floordivsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def negi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer negation.

        Example::
            %result = scalar.negi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.negi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def absi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer absolute value.

        Example::
            %result = scalar.absi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.absi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def minsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer minimum.

        Example::
            %result = scalar.minsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.minsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def maxsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer maximum.

        Example::
            %result = scalar.maxsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.maxsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def minui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer minimum.

        Example::
            %result = scalar.minui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.minui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def maxui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer maximum.

        Example::
            %result = scalar.maxui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.maxui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fmai(self, *, overflow: str | None = None, a: ValueRef, b: ValueRef, c: ValueRef, result_types: list[Type]) -> ValueRef:
        """Fused integer multiply-add: a*b + c with no intermediate overflow check.

        Example::
            %result = scalar.fmai %a, %b, %c : i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(a)
        _operands.append(b)
        _operands.append(c)
        return cast(ValueRef, self._b.build("scalar.fmai", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def addf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point addition.

        Example::
            %result = scalar.addf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.addf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def subf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point subtraction.

        Example::
            %result = scalar.subf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.subf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def mulf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point multiplication.

        Example::
            %result = scalar.mulf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.mulf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def divf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point division.

        Example::
            %result = scalar.divf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.divf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def remf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point remainder (C fmod semantics).

        Example::
            %result = scalar.remf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.remf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def negf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point negation.

        Example::
            %result = scalar.negf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.negf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def absf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point absolute value.

        Example::
            %result = scalar.absf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.absf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def minimumf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """IEEE 754 minimum (NaN propagates).

        Example::
            %result = scalar.minimumf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.minimumf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def maximumf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """IEEE 754 maximum (NaN propagates).

        Example::
            %result = scalar.maximumf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.maximumf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def minnumf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """C99 fmin (NaN ignored, returns the non-NaN operand).

        Example::
            %result = scalar.minnumf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.minnumf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def maxnumf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """C99 fmax (NaN ignored, returns the non-NaN operand).

        Example::
            %result = scalar.maxnumf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.maxnumf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def copysignf(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Copy sign of rhs onto magnitude of lhs.

        Example::
            %result = scalar.copysignf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.copysignf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def expf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Exponential: e^x.

        Example::
            %result = scalar.expf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.expf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def exp2f(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Base-2 exponential: 2^x.

        Example::
            %result = scalar.exp2f %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.exp2f", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def expm1f(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Exponential minus one: e^x - 1 (numerically stable near 0).

        Example::
            %result = scalar.expm1f %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.expm1f", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def logf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Natural logarithm: ln(x).

        Example::
            %result = scalar.logf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.logf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def log2f(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Base-2 logarithm.

        Example::
            %result = scalar.log2f %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.log2f", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def log10f(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Base-10 logarithm.

        Example::
            %result = scalar.log10f %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.log10f", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def log1pf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Natural logarithm of 1+x: ln(1+x) (numerically stable near 0).

        Example::
            %result = scalar.log1pf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.log1pf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def powf(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Power: x^y.

        Example::
            %result = scalar.powf %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.powf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sqrtf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Square root.

        Example::
            %result = scalar.sqrtf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.sqrtf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def rsqrtf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Reciprocal square root: 1/sqrt(x).

        Example::
            %result = scalar.rsqrtf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.rsqrtf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cbrtf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Cube root.

        Example::
            %result = scalar.cbrtf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.cbrtf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sinf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Sine.

        Example::
            %result = scalar.sinf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.sinf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cosf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Cosine.

        Example::
            %result = scalar.cosf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.cosf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def tanf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Tangent.

        Example::
            %result = scalar.tanf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.tanf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def asinf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Arcsine.

        Example::
            %result = scalar.asinf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.asinf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def acosf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Arccosine.

        Example::
            %result = scalar.acosf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.acosf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def atanf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Arctangent.

        Example::
            %result = scalar.atanf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.atanf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def atan2f(self, *, fastmath: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Two-argument arctangent: atan2(y, x).

        Example::
            %result = scalar.atan2f %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.atan2f", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sinhf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Hyperbolic sine.

        Example::
            %result = scalar.sinhf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.sinhf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def coshf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Hyperbolic cosine.

        Example::
            %result = scalar.coshf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.coshf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def tanhf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Hyperbolic tangent.

        Example::
            %result = scalar.tanhf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.tanhf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def asinhf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Inverse hyperbolic sine.

        Example::
            %result = scalar.asinhf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.asinhf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def acoshf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Inverse hyperbolic cosine.

        Example::
            %result = scalar.acoshf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.acoshf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def atanhf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Inverse hyperbolic tangent.

        Example::
            %result = scalar.atanhf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.atanhf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def erff(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Error function (used in GeLU activation).

        Example::
            %result = scalar.erff %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.erff", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def erfcf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Complementary error function: 1 - erf(x).

        Example::
            %result = scalar.erfcf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.erfcf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fmaf(self, *, fastmath: str | None = None, a: ValueRef, b: ValueRef, c: ValueRef, result_types: list[Type]) -> ValueRef:
        """Fused multiply-add: a*b + c with single rounding.

        Example::
            %result = scalar.fmaf %a, %b, %c : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(a)
        _operands.append(b)
        _operands.append(c)
        return cast(ValueRef, self._b.build("scalar.fmaf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ceilf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Round toward positive infinity.

        Example::
            %result = scalar.ceilf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.ceilf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def floorf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Round toward negative infinity.

        Example::
            %result = scalar.floorf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.floorf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def roundf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Round to nearest, ties away from zero.

        Example::
            %result = scalar.roundf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.roundf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def roundevenf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Round to nearest, ties to even (IEEE 754 default rounding).

        Example::
            %result = scalar.roundevenf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.roundevenf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def truncf(self, *, fastmath: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Round toward zero (C trunc).

        Example::
            %result = scalar.truncf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.truncf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cmpi(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer comparison.

        Example::
            %result = scalar.cmpi eq, %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.cmpi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cmpf(self, *, fastmath: str | None = None, predicate: str, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point comparison.

        Example::
            %result = scalar.cmpf olt, %lhs, %rhs : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if fastmath is not None:
            _attributes["fastmath"] = fastmath
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.cmpf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def select(self, *, condition: ValueRef, true_value: ValueRef, false_value: ValueRef, result_types: list[Type]) -> ValueRef:
        """Conditional select: returns true_value if condition is true, else false_value.

        Example::
            %result = scalar.select %cond, %t, %f : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(condition)
        _operands.append(true_value)
        _operands.append(false_value)
        return cast(ValueRef, self._b.build("scalar.select", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def isnanf(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Returns true (i1) if the operand is NaN.

        Example::
            %result = scalar.isnanf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.isnanf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def isinff(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Returns true (i1) if the operand is positive or negative infinity.

        Example::
            %result = scalar.isinff %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.isinff", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def isfinitef(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Returns true (i1) if the operand is finite (not NaN and not infinity).

        Example::
            %result = scalar.isfinitef %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.isfinitef", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def signf(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point sign: returns -1.0, 0.0, or 1.0.

        Example::
            %result = scalar.signf %input : f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.signf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def signi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer sign: returns -1, 0, or 1.

        Example::
            %result = scalar.signi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.signi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer to floating-point.

        Example::
            %result = scalar.sitofp %input : i32 to f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.sitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def uitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer to floating-point.

        Example::
            %result = scalar.uitofp %input : i32 to f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.uitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptosi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point to signed integer (rounds toward zero).

        Example::
            %result = scalar.fptosi %input : f32 to i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.fptosi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptoui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Floating-point to unsigned integer (rounds toward zero).

        Example::
            %result = scalar.fptoui %input : f32 to i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.fptoui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extf(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Float precision extension (widen): e.g. f16 to f32.

        Example::
            %result = scalar.extf %input : f16 to f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.extf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptrunc(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Float precision truncation (narrow): e.g. f32 to f16.

        Example::
            %result = scalar.fptrunc %input : f32 to f16
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.fptrunc", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extsi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Signed integer extension (sign-extend): e.g. i8 to i32.

        Example::
            %result = scalar.extsi %input : i8 to i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.extsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Unsigned integer extension (zero-extend): e.g. i8 to i32.

        Example::
            %result = scalar.extui %input : i8 to i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.extui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def trunci(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Integer truncation (narrow): e.g. i32 to i8.

        Example::
            %result = scalar.trunci %input : i32 to i8
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.trunci", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def index_cast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Index/offset to integer or integer to index/offset conversion.

        Example::
            %result = scalar.index_cast %input : index to i64
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.index_cast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def bitcast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Bitwise reinterpretation: same bits, different type. No conversion.

        Example::
            %result = scalar.bitcast %input : f32 to i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.bitcast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def constant(self, *, value: Any, result_types: list[Type]) -> ValueRef:
        """Materialize a compile-time constant scalar value.

        Example::
            %c42 = scalar.constant 42 : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("scalar.constant", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def andi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Bitwise AND.

        Example::
            %result = scalar.andi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.andi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ori(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Bitwise OR.

        Example::
            %result = scalar.ori %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.ori", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def xori(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Bitwise XOR.

        Example::
            %result = scalar.xori %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.xori", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def shli(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Left shift.

        Example::
            %result = scalar.shli %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.shli", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def shrsi(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Arithmetic right shift (sign-extending).

        Example::
            %result = scalar.shrsi %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.shrsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def shrui(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Logical right shift (zero-extending).

        Example::
            %result = scalar.shrui %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.shrui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def rotli(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Left rotate.

        Example::
            %result = scalar.rotli %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.rotli", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def rotri(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Right rotate.

        Example::
            %result = scalar.rotri %lhs, %rhs : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("scalar.rotri", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ctlzi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Count leading zeros.

        Example::
            %result = scalar.ctlzi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.ctlzi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cttzi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Count trailing zeros.

        Example::
            %result = scalar.cttzi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.cttzi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def ctpopi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Population count (number of set bits).

        Example::
            %result = scalar.ctpopi %input : i32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("scalar.ctpopi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def assume(self, *, values: list[ValueRef], predicates: list[Predicate], result_types: list[Type]) -> list[ValueRef]:
        """Identity with predicate constraints on results.

        Example::
            %M2 = scalar.assume %M [mul(%M, 16)] : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicates"] = predicates
        _operands.extend(values)
        return cast(list[ValueRef], self._b.build("scalar.assume", _operands, results=result_types, attributes=_attributes, regions=_regions))
