// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "loom/tools/iree-tune-loom/help.h"

#include "iree/base/tooling/flags.h"

void iree_tune_loom_print_agents_md(FILE* file) {
  fprintf(file,
          "## iree-tune-loom\n"
          "\n"
          "Use `iree-tune-loom` when a `.loom` file declares "
          "`check.benchmark` records and you need correctness-gated timing, "
          "compile diagnostics, or HAL dispatch evidence for kernel tuning. "
          "The tool emits JSONL: every row has `row` and `run_id`; selected "
          "benchmarks also have `candidate_id` so rows can be joined across "
          "large sweeps. Rows are written and flushed as each lifecycle step "
          "finishes, so `tail -f results.jsonl` is useful while a long run is "
          "still active. The final `summary` row carries both flat totals and "
          "a nested `summary` object with planned/failure/correctness/artifact "
          "counts for agent consumers. Use "
          "`--profile_final_batch=true` for dispatch timing evidence outside "
          "the measured window; add "
          "`--profile_artifacts_dir=DIR` when you need the raw HAL profile "
          "bundle for counters or traces. Parameterized cases report "
          "`shape_id`, `shape_index`, and a concrete `shape.parameters` map on "
          "sample/benchmark/profile rows. For dispatch benchmarks, "
          "`--shape_specialization=dynamic` compiles once, "
          "`--shape_specialization=per_sample` compiles each selected shape "
          "with concrete parameter facts, and `--shape_specialization=both` "
          "emits both result sets. `check.file.read.npy` paths resolve "
          "relative to the `.loom` file; `check.file.write.npy` paths are "
          "relative to `--file_output_dir`, which defaults under "
          "`$TMPDIR/iree-loom-tune`. Dispatch benchmarks materialize valid "
          "check-op inputs into a device-buffer binding ring; "
          "`--input_ring_min_bytes=33554432` is the default cache-thwarting "
          "target and `--input_ring_count=1` forces hot-reuse timing when "
          "that is the experiment. Benchmark rows report `data_cache` with "
          "the effective ring count and bytes. "
          "Use `--compare=@baseline,@variant --interleave=ABABA` for a fair "
          "two-candidate dispatch comparison; `--interleave=round_robin` "
          "supports ABCD-style rotation. Comparison mode runs full benchmark "
          "windows for one concrete shape per candidate and emits "
          "`benchmark.repetition` plus `comparison` rows; selected candidates "
          "must have the same concrete parameter layout and values, so use "
          "`--sample=` when a case has multiple shape samples. "
          "When `--profile_data` includes "
          "`counters` or `counter-ranges`, decoded rows are emitted as "
          "`profile_counter` JSONL after the normal `profile` row. Each "
          "decode emits a `counter_decode_status` row carrying the requested "
          "families/sets and decoded row counts; raw-artifact-only and "
          "unavailable profiles use the same status row shape instead of "
          "failing the timing run. Raw `.irpf` profile bundles also emit "
          "`profile_summary` rows with bundle/device summaries, executable "
          "trace byte counts, device metric counts, and decode status. Use "
          "`--artifact_bundle_dir=DIR` to collect `results.jsonl`, "
          "`manifest.json`, file outputs, and profile artifacts under one "
          "directory; `--artifact_bundle_policy=debug|full` also writes "
          "per-candidate compile report sidecars under `compile_reports/`, "
          "target-native artifacts under `target_artifacts/`, target-owned "
          "assembly/listing text under `target_listings/`, and HAL executable "
          "packages under `hal_executables/`; compile and benchmark rows link "
          "them from `compile_report_path`, `target_artifact_path`, "
          "`target_listing_path`, and `hal_executable_path`. The manifest "
          "records command/path/source identity, path/size/mtime metadata "
          "for observed fixture/output/profile/compile-report/executable "
          "files, selected environment variables, and HAL device identity "
          "when a dispatch benchmark selected a backend. Source, fixture, "
          "and artifact files are identified by path/size/mtime; this CLI "
          "does not content-hash large files or act as a CAS. "
          "Benchmark attrs named `family`, `phase`, `strategy`, "
          "`knobs`, `problem`, or `reference_id` are copied into a "
          "`metadata` object on candidate rows. Compile rows and benchmark "
          "payloads with reports also carry `static_summary` for code size, "
          "instruction count, descriptor instruction mix, spills, memory, "
          "pressure, source-low counts, and move-cause totals.\n"
          "\n"
          "Examples:\n"
          "\n"
          "```bash\n"
          "iree-bazel-run //loom/src/loom/tools/iree-tune-loom -- "
          "path/to/file.loom --benchmark=@kernel_latency --dry_run "
          "--output=plan.jsonl\n"
          "```\n"
          "\n"
          "```bash\n"
          "iree-bazel-run //loom/src/loom/tools/iree-tune-loom -- "
          "path/to/file.loom --device=amdgpu --benchmark=@kernel_latency "
          "--batch_size=64 --iterations=16 --warmup_iterations=4 "
          "--min_time_ms=100 --profile_final_batch=true "
          "--input_ring_min_bytes=33554432 "
          "--shape_specialization=both "
          "--output=results.jsonl\n"
          "```\n"
          "\n"
          "```bash\n"
          "iree-bazel-run //loom/src/loom/tools/iree-tune-loom -- "
          "path/to/file.loom --device=amdgpu --benchmark=@kernel_latency "
          "--profile_data=counter-ranges --profile_counter=SQ_WAVES "
          "--artifact_bundle_dir=/tmp/loom-run\n"
          "```\n"
          "\n"
          "```bash\n"
          "iree-bazel-run //loom/src/loom/tools/iree-tune-loom -- "
          "path/to/file.loom --device=amdgpu "
          "--compare=@baseline_latency,@variant_latency --interleave=ABABA "
          "--repetitions=2 --sample=0 --profile_final_batch=false "
          "--output=ababa.jsonl\n"
          "```\n"
          "\n"
          "```bash\n"
          "jq 'select(.row==\"benchmark\") | .benchmark_result | "
          "{benchmark,status,p50:.dispatch_timing_ns.p50,stop_reason}' "
          "results.jsonl\n"
          "jq 'select(.row==\"compile\" and .status!=\"ok\") | "
          ".diagnostics[]?' results.jsonl\n"
          "jq 'select(.row==\"compile\" and .static_summary) | "
          "{candidate_id,code:.static_summary.code_byte_count,"
          "valu:.static_summary.vector_alu_count,"
          "spills:.static_summary.allocation_spill_count}' results.jsonl\n"
          "jq 'select(.row==\"compile\" and .compile_report_path) | "
          "{candidate_id,path:.compile_report_path}' results.jsonl\n"
          "jq 'select(.row==\"compile\" and .target_artifact_path) | "
          "{candidate_id,target:.target_artifact_path,"
          "listing:.target_listing_path,hal:.hal_executable_path}' "
          "results.jsonl\n"
          "jq 'select(.row==\"benchmark\" and .shape) | "
          "{candidate_id,shape_id,shape:.shape.parameters,"
          "p50:.benchmark_result.dispatch_timing_ns.p50}' results.jsonl\n"
          "jq 'select(.row==\"benchmark\") | .benchmark_result | "
          "{benchmark,p50:.dispatch_timing_ns.p50,"
          "data_cache}' results.jsonl\n"
          "jq 'select(.row==\"benchmark.repetition\") | "
          "{candidate_id,order_index,token:.schedule_token,"
          "p50:.benchmark_result.dispatch_timing_ns.p50}' results.jsonl\n"
          "jq 'select(.row==\"comparison\") | "
          "{candidate_id,baseline_candidate_id,ratio_p50,speedup_p50,"
          "ratio_p90,speedup_p90,candidate_p50_spread_ppm}' "
          "results.jsonl\n"
          "jq 'select(.row==\"profile_counter\") | .counter | "
          "select(.type==\"counter_group\") | {key,counter,avg,sum}' "
          "results.jsonl\n"
          "jq 'select(.row==\"profile_counter\" and "
          ".counter.type==\"counter_decode_status\") | "
          "{candidate_id,status:.counter.status,reason:.counter.reason,"
          "decoded:.counter.decoded_rows}' "
          "results.jsonl\n"
          "jq 'select(.row==\"profile_summary\" and "
          ".profile_summary.type==\"summary\") | "
          "{candidate_id,traces:.profile_summary.executable_trace_records,"
          "trace_bytes:.profile_summary.executable_trace_data_bytes,"
          "metric_values:.profile_summary.device_metric_values}' "
          "results.jsonl\n"
          "jq 'select(.row==\"profile_summary\" and "
          ".profile_summary.type==\"profile_summary_status\") | "
          "{candidate_id,status:.profile_summary.status,"
          "reason:.profile_summary.reason,"
          "decoded:.profile_summary.decoded_rows}' "
          "results.jsonl\n"
          "tail -f results.jsonl | jq -c 'select(.row==\"compile\" or "
          ".row==\"benchmark\" or .row==\"comparison\" or "
          ".row==\"summary\")'\n"
          "```\n"
          "\n"
          "Use `iree-tune-loom --help` for the full flag list, JSONL row "
          "schema notes, and more `jq` recipes.\n");
}

void iree_tune_loom_set_usage(const char* tool_name) {
  iree_flags_set_usage(
      tool_name,
      "Runs correctness-gated check.benchmark records from a Loom module.\n"
      "\n"
      "Usage:\n"
      "  iree-tune-loom file.loom --benchmark=@smoke_latency\n"
      "  iree-tune-loom file.loom --benchmark=@smoke_latency --dry_run "
      "--output=plan.jsonl\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--benchmark=@kernel_latency --batch_size=64 "
      "--profile_final_batch=true --output=results.jsonl\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--benchmark=@kernel_latency --profile_final_batch=true "
      "--profile_artifacts_dir=/tmp/loom-profiles --output=results.jsonl\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--benchmark=@kernel_latency --profile_data=counter-ranges "
      "--profile_counter=SQ_WAVES --file_output_dir=/tmp/loom-run "
      "--output=results.jsonl\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--benchmark=@kernel_latency --artifact_bundle_dir=/tmp/loom-run\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--benchmark=@kernel_latency "
      "--shape_specialization=dynamic|per_sample|both\n"
      "  iree-tune-loom file.loom --device=amdgpu "
      "--compare=@baseline,@variant --interleave=ABABA "
      "--repetitions=2 --profile_final_batch=false\n"
      "  cat module.loom | iree-tune-loom -\n"
      "  iree-tune-loom --agents_md\n"
      "\n"
      "JSONL rows:\n"
      "  run       first row; source path and process-local run_id\n"
      "  plan      selected benchmark/case, effective policy, CLI overrides\n"
      "  device    selected --device/driver/backend and cheap HAL identity\n"
      "  compile   per-candidate diagnostics and compile report payload\n"
      "  sample    correctness sample result from the testbench executor\n"
      "  benchmark timing/failure evidence; dispatch_timing_ns is the score\n"
      "  benchmark.repetition one interleaved comparison timing window\n"
      "  comparison aggregate baseline/candidate timing ratio\n"
      "  profile   optional final profiled-batch evidence outside timing\n"
      "  profile_summary decoded raw profile bundle summary/device rows\n"
      "  profile_counter decoded counter status/summary/set/group rows\n"
      "  failure   parse/verify/planning failure diagnostics\n"
      "  summary   final totals row\n"
      "\n"
      "Rows are written and flushed as evidence becomes available, so an agent "
      "can `tail -f` an --output file during long sweeps. Every row carries "
      "run_id. Selected benchmark rows also carry "
      "candidate_id/candidate_index so agents can join plan, compile, sample, "
      "benchmark, and profile evidence across large JSONL sweeps. "
      "When --artifact_bundle_dir is set and --output is empty, results are "
      "written to results.jsonl in the bundle and manifest.json records "
      "command line, source identity, output, profile, file-output paths, "
      "path/size/mtime metadata for observed fixture/output/profile files, "
      "selected environment variables, and HAL device identity when a dispatch "
      "benchmark selected a backend. With --artifact_bundle_policy=debug|full, "
      "per-candidate compile report sidecars are written under "
      "compile_reports/, target-native artifacts under target_artifacts/, "
      "target-owned assembly/listing text under target_listings/, and HAL "
      "executable packages under hal_executables/; compile and benchmark rows "
      "link them from compile_report_path, target_artifact_path, "
      "target_listing_path, and hal_executable_path. Source, fixture, and "
      "artifact files are identified by path/size/mtime; this CLI does not "
      "content-hash large files or act as a CAS. "
      "`--shape_specialization=dynamic` compiles once, "
      "`--shape_specialization=per_sample` compiles each selected shape with "
      "concrete parameter facts, and `--shape_specialization=both` emits both "
      "views for comparing generic-vs-specialized kernels. "
      "Parameterized cases also carry shape_id/shape_index and a "
      "shape.parameters map on sample, benchmark, and profile rows so "
      "multi-size runs can be joined without filename conventions. Compile "
      "diagnostics are data: a compile row with status!='ok' is a candidate "
      "rejection, not a tool infrastructure failure. Profile rows are emitted "
      "only when --profile_final_batch=true or a benchmark attr requests it; "
      "their profile.rows array contains HAL statistics rows such as "
      "dispatch_export, dispatch_command_buffer, and "
      "dispatch_command_operation when the backend provides them. "
      "Dispatch benchmarks materialize device-buffer bindings from check ops "
      "into an input ring before recording command buffers; dispatch slot i "
      "uses a different physical binding set while the ring has capacity. "
      "The default auto ring targets at least 32MiB of bindings and at least "
      "one binding set per dispatch in the batch. Set --input_ring_count=1 "
      "for deliberate hot-reuse measurements. Benchmark rows include "
      "benchmark_result.data_cache with the effective ring shape and bytes. "
      "`--compare=@baseline,@variant` runs selected dispatch_complete "
      "benchmarks as prepared candidates in an interleaved schedule. ABABA "
      "requires exactly two benchmarks and runs A followed by --repetitions "
      "BA pairs; round_robin supports ABCD-style rotation. Comparison mode "
      "requires one concrete shape per candidate, so use --sample= when a "
      "case has multiple shape samples; selected candidates must have the "
      "same concrete parameter layout and values. Measured comparison windows "
      "suppress final profiling and report that as "
      "profile_suppressed_for_interleave so profiling evidence does not "
      "perturb interleaved timing. "
      "check.file.read.npy paths resolve relative to the input .loom file. "
      "check.file.write.npy paths must be relative and are rooted under "
      "--file_output_dir, which defaults under $TMPDIR/iree-loom-tune. "
      "Compile rows and benchmark payloads with reports also carry "
      "static_summary, a compact projection of static compile evidence such "
      "as instruction count, code bytes, descriptor instruction mix, spill "
      "counts, memory, pressure, source-low counts, and move-cause totals. "
      "--profile_data selects final-batch HAL profiling families and "
      "--profile_artifacts_dir writes raw .irpf bundles for heavyweight "
      "families such as counters, device metrics, and executable traces. Raw "
      "bundles emit profile_summary JSONL rows with bundle/device summaries, "
      "executable trace byte counts, device metric counts, and a "
      "profile_summary_status row. Counter families also emit "
      "profile_counter JSONL rows decoded from the raw profile bundle; each "
      "decode emits a counter_decode_status row with requested families/sets "
      "and decoded row counts, and decode failures or unavailable counter "
      "evidence use the same status row shape instead of failing the timing "
      "run. Without an explicit --profile_artifacts_dir, heavyweight bundles "
      "are staged under the run file_output_dir.\n"
      "Benchmark attrs named family, phase, strategy, knobs, problem, or "
      "reference_id are copied into a metadata object on candidate rows. "
      "The final summary row keeps the existing flat count fields and also "
      "carries a nested summary object grouping planned, failure, correctness, "
      "and artifact totals for compact agent consumption.\n"
      "\n"
      "jq recipes:\n"
      "  jq 'select(.row==\"run\" or .row==\"summary\")' results.jsonl\n"
      "  jq 'select(.row==\"summary\")' results.jsonl\n"
      "  jq 'select(.row==\"failure\" or .row==\"compile\") | "
      "select(.status!=\"ok\" or .row==\"failure\")' results.jsonl\n"
      "  jq 'select(.row==\"compile\") | .diagnostics[]?' results.jsonl\n"
      "  jq 'select(.row==\"benchmark\") | .benchmark_result | "
      "{benchmark,status,p50:.dispatch_timing_ns.p50}' results.jsonl\n"
      "  jq 'select(.row==\"benchmark\") | .benchmark_result | "
      "{benchmark,p50:.dispatch_timing_ns.p50,data_cache}' results.jsonl\n"
      "  jq 'select(.row==\"benchmark\" and .shape) | "
      "{candidate_id,shape_id,shape:.shape.parameters,"
      "p50:.benchmark_result.dispatch_timing_ns.p50}' results.jsonl\n"
      "  jq 'select(.row==\"benchmark.repetition\") | "
      "{candidate_id,order_index,token:.schedule_token,"
      "p50:.benchmark_result.dispatch_timing_ns.p50}' results.jsonl\n"
      "  jq 'select(.row==\"comparison\") | "
      "{candidate_id,baseline_candidate_id,ratio_p50,speedup_p50,"
      "ratio_p90,speedup_p90,candidate_p50_spread_ppm}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"plan\" and .metadata) | "
      "{candidate_id,metadata}' results.jsonl\n"
      "  jq 'select(.row==\"compile\" and .static_summary) | "
      "{candidate_id,code:.static_summary.code_byte_count,"
      "spills:.static_summary.allocation_spill_count,"
      "valu:.static_summary.vector_alu_count,"
      "local:.static_summary.local_memory_bytes}' results.jsonl\n"
      "  jq 'select(.row==\"compile\" and .compile_report_path) | "
      "{candidate_id,path:.compile_report_path}' results.jsonl\n"
      "  jq 'select(.row==\"compile\" and .target_artifact_path) | "
      "{candidate_id,target:.target_artifact_path,"
      "listing:.target_listing_path,hal:.hal_executable_path}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"profile\") as $r | $r.profile.rows[]? | "
      "select(.type|startswith(\"dispatch_\")) | "
      "{candidate_id:$r.candidate_id,type,export_name,"
      "timing:.timing.mean_ns}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"profile_counter\") | .counter | "
      "select(.type==\"counter_group\") | {key,counter,avg,sum}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"profile_counter\" and "
      ".counter.type==\"counter_decode_status\") | "
      "{candidate_id,status:.counter.status,reason:.counter.reason,"
      "decoded:.counter.decoded_rows,error:.counter.error.status}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"profile_summary\" and "
      ".profile_summary.type==\"summary\") | "
      "{candidate_id,traces:.profile_summary.executable_trace_records,"
      "trace_bytes:.profile_summary.executable_trace_data_bytes,"
      "metric_values:.profile_summary.device_metric_values}' "
      "results.jsonl\n"
      "  jq 'select(.row==\"profile_summary\" and "
      ".profile_summary.type==\"profile_summary_status\") | "
      "{candidate_id,status:.profile_summary.status,"
      "reason:.profile_summary.reason,"
      "decoded:.profile_summary.decoded_rows}' results.jsonl\n"
      "  tail -f results.jsonl | jq -c 'select(.row==\"compile\" or "
      ".row==\"benchmark\" or .row==\"comparison\" or .row==\"summary\")'\n");
}
