// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_VECTOR_OPS_H_
#define LOOM_OPS_VECTOR_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_VECTOR_CONSTANT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 0),
  LOOM_OP_VECTOR_SPLAT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 1),
  LOOM_OP_VECTOR_BROADCAST = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 2),
  LOOM_OP_VECTOR_FROM_ELEMENTS = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 3),
  LOOM_OP_VECTOR_EXTRACT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 4),
  LOOM_OP_VECTOR_INSERT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 5),
  LOOM_OP_VECTOR_LOAD = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 6),
  LOOM_OP_VECTOR_STORE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 7),
  LOOM_OP_VECTOR_LOAD_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 8),
  LOOM_OP_VECTOR_STORE_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 9),
  LOOM_OP_VECTOR_SELECT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 10),
  LOOM_OP_VECTOR_CMPI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 11),
  LOOM_OP_VECTOR_CMPF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 12),
  LOOM_OP_VECTOR_ADDF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 13),
  LOOM_OP_VECTOR_MULF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 14),
  LOOM_OP_VECTOR_FMAF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 15),
  LOOM_OP_VECTOR_ADDI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 16),
  LOOM_OP_VECTOR_MULI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 17),
  LOOM_OP_VECTOR_SQRTF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 18),
  LOOM_OP_VECTOR_EXTF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 19),
  LOOM_OP_VECTOR_FPTRUNC = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 20),
  LOOM_OP_VECTOR_EXTSI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 21),
  LOOM_OP_VECTOR_EXTUI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 22),
  LOOM_OP_VECTOR_TRUNCI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 23),
  LOOM_OP_VECTOR_SITOFP = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 24),
  LOOM_OP_VECTOR_UITOFP = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 25),
  LOOM_OP_VECTOR_FPTOSI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 26),
  LOOM_OP_VECTOR_FPTOUI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 27),
  LOOM_OP_VECTOR_BITCAST = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 28),
  LOOM_OP_VECTOR_REDUCE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 29),
  LOOM_OP_VECTOR_COUNT_ = 30,
};

// Floating-point value-domain assumptions for vector operations.
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NNAN ((uint8_t)1)
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NINF ((uint8_t)2)
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NSZ ((uint8_t)4)

// Integer overflow behavior flags.
#define LOOM_VECTOR_INTOVERFLOWFLAGS_NSW ((uint8_t)1)
#define LOOM_VECTOR_INTOVERFLOWFLAGS_NUW ((uint8_t)2)

// Integer comparison predicates.
typedef enum loom_vector_cmpi_predicate_e {
  LOOM_VECTOR_CMPI_PREDICATE_EQ = 0,
  LOOM_VECTOR_CMPI_PREDICATE_NE = 1,
  LOOM_VECTOR_CMPI_PREDICATE_SLT = 2,
  LOOM_VECTOR_CMPI_PREDICATE_SLE = 3,
  LOOM_VECTOR_CMPI_PREDICATE_SGT = 4,
  LOOM_VECTOR_CMPI_PREDICATE_SGE = 5,
  LOOM_VECTOR_CMPI_PREDICATE_ULT = 6,
  LOOM_VECTOR_CMPI_PREDICATE_ULE = 7,
  LOOM_VECTOR_CMPI_PREDICATE_UGT = 8,
  LOOM_VECTOR_CMPI_PREDICATE_UGE = 9,
  LOOM_VECTOR_CMPI_PREDICATE_COUNT_ = 10,
} loom_vector_cmpi_predicate_t;

// Floating-point comparison predicates (IEEE 754 total order).
typedef enum loom_vector_cmpf_predicate_e {
  LOOM_VECTOR_CMPF_PREDICATE_OEQ = 0,
  LOOM_VECTOR_CMPF_PREDICATE_OGT = 1,
  LOOM_VECTOR_CMPF_PREDICATE_OGE = 2,
  LOOM_VECTOR_CMPF_PREDICATE_OLT = 3,
  LOOM_VECTOR_CMPF_PREDICATE_OLE = 4,
  LOOM_VECTOR_CMPF_PREDICATE_ONE = 5,
  LOOM_VECTOR_CMPF_PREDICATE_ORD = 6,
  LOOM_VECTOR_CMPF_PREDICATE_UEQ = 7,
  LOOM_VECTOR_CMPF_PREDICATE_UGT = 8,
  LOOM_VECTOR_CMPF_PREDICATE_UGE = 9,
  LOOM_VECTOR_CMPF_PREDICATE_ULT = 10,
  LOOM_VECTOR_CMPF_PREDICATE_ULE = 11,
  LOOM_VECTOR_CMPF_PREDICATE_UNE = 12,
  LOOM_VECTOR_CMPF_PREDICATE_UNO = 13,
  LOOM_VECTOR_CMPF_PREDICATE_COUNT_ = 14,
} loom_vector_cmpf_predicate_t;

// Combining operations for vector reductions.
typedef enum loom_vector_reduce_kind_e {
  LOOM_VECTOR_REDUCE_KIND_ADDI = 0,
  LOOM_VECTOR_REDUCE_KIND_ADDF = 1,
  LOOM_VECTOR_REDUCE_KIND_MULI = 2,
  LOOM_VECTOR_REDUCE_KIND_MULF = 3,
  LOOM_VECTOR_REDUCE_KIND_MINSI = 4,
  LOOM_VECTOR_REDUCE_KIND_MAXSI = 5,
  LOOM_VECTOR_REDUCE_KIND_MINUI = 6,
  LOOM_VECTOR_REDUCE_KIND_MAXUI = 7,
  LOOM_VECTOR_REDUCE_KIND_ANDI = 8,
  LOOM_VECTOR_REDUCE_KIND_ORI = 9,
  LOOM_VECTOR_REDUCE_KIND_XORI = 10,
  LOOM_VECTOR_REDUCE_KIND_MINIMUMF = 11,
  LOOM_VECTOR_REDUCE_KIND_MAXIMUMF = 12,
  LOOM_VECTOR_REDUCE_KIND_MINNUMF = 13,
  LOOM_VECTOR_REDUCE_KIND_MAXNUMF = 14,
  LOOM_VECTOR_REDUCE_KIND_COUNT_ = 15,
} loom_vector_reduce_kind_t;

// LOOM_OP_VECTOR_CONSTANT: Materialize a compile-time splat constant vector value.
// %v = vector.constant 0.0 : vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_constant_isa, LOOM_OP_VECTOR_CONSTANT)
LOOM_DEFINE_RESULT(loom_vector_constant_result, 0)
LOOM_DEFINE_ATTR_ANY(loom_vector_constant_value, 0)
iree_status_t loom_vector_constant_build(
    loom_builder_t* builder,
    loom_attribute_t value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_constant_vtable;
iree_status_t loom_vector_constant_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SPLAT: Replicate one scalar value to every lane of a vector result.
// %vec = vector.splat %scalar : f32 -> vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_splat_isa, LOOM_OP_VECTOR_SPLAT)
LOOM_DEFINE_OPERAND(loom_vector_splat_scalar, 0)
LOOM_DEFINE_RESULT(loom_vector_splat_result, 0)
iree_status_t loom_vector_splat_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_splat_vtable;

// LOOM_OP_VECTOR_BROADCAST: Broadcast a vector value to a vector result with a compatible shape.
// %wide = vector.broadcast %v : vector<4xf32> -> vector<16x4xf32>
LOOM_DEFINE_ISA(loom_vector_broadcast_isa, LOOM_OP_VECTOR_BROADCAST)
LOOM_DEFINE_OPERAND(loom_vector_broadcast_source, 0)
LOOM_DEFINE_RESULT(loom_vector_broadcast_result, 0)
iree_status_t loom_vector_broadcast_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_broadcast_vtable;
iree_status_t loom_vector_broadcast_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_FROM_ELEMENTS: Build a vector from scalar element operands in lane order.
// %v = vector.from_elements %a, %b, %c, %d : f32, f32, f32, f32 -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_from_elements_isa, LOOM_OP_VECTOR_FROM_ELEMENTS)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_from_elements_elements, 0)
LOOM_DEFINE_RESULT(loom_vector_from_elements_result, 0)
iree_status_t loom_vector_from_elements_build(
    loom_builder_t* builder,
    loom_may_consume const loom_value_id_t* elements,
    iree_host_size_t elements_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_from_elements_vtable;
iree_status_t loom_vector_from_elements_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTRACT: Extract a scalar or subvector from a vector at explicit indices.
// %x = vector.extract %v[%i] : vector<[%n]xf32> -> f32
LOOM_DEFINE_ISA(loom_vector_extract_isa, LOOM_OP_VECTOR_EXTRACT)
LOOM_DEFINE_OPERAND(loom_vector_extract_source, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_extract_indices, 1)
LOOM_DEFINE_RESULT(loom_vector_extract_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_extract_static_indices, 0)
iree_status_t loom_vector_extract_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extract_vtable;
iree_status_t loom_vector_extract_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_INSERT: Insert a scalar or subvector into a vector at explicit indices.
// %r = vector.insert %x into %v[%i] : f32, vector<[%n]xf32> -> vector<[%n]xf32>
LOOM_DEFINE_ISA(loom_vector_insert_isa, LOOM_OP_VECTOR_INSERT)
LOOM_DEFINE_OPERAND(loom_vector_insert_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_insert_dest, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_insert_indices, 2)
LOOM_DEFINE_RESULT(loom_vector_insert_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_insert_static_indices, 0)
iree_status_t loom_vector_insert_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t value,
    loom_may_consume loom_value_id_t dest,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_insert_vtable;
iree_status_t loom_vector_insert_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_LOAD: Load a vector footprint from a typed view at a full-rank logical origin.
// %v = vector.load %view[%row, %col] : view<[%m]x[%n]xf32, %layout> -> vector<4x8xf32>
LOOM_DEFINE_ISA(loom_vector_load_isa, LOOM_OP_VECTOR_LOAD)
LOOM_DEFINE_OPERAND(loom_vector_load_view, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_load_indices, 1)
LOOM_DEFINE_RESULT(loom_vector_load_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_load_static_indices, 0)
iree_status_t loom_vector_load_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_load_vtable;
iree_status_t loom_vector_load_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_STORE: Store a vector footprint into a typed view at a full-rank logical origin.
// vector.store %v, %view[%row, %col] : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>
LOOM_DEFINE_ISA(loom_vector_store_isa, LOOM_OP_VECTOR_STORE)
LOOM_DEFINE_OPERAND(loom_vector_store_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_store_view, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_store_indices, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_store_static_indices, 0)
iree_status_t loom_vector_store_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_store_vtable;
iree_status_t loom_vector_store_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_LOAD_MASK: Masked vector load from a typed view; masked-off lanes take the passthrough value.
// %v = vector.load.mask %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>, vector<4x8xf32> -> vector<4x8xf32>
LOOM_DEFINE_ISA(loom_vector_load_mask_isa, LOOM_OP_VECTOR_LOAD_MASK)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_view, 0)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_mask, 1)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_passthrough, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_load_mask_indices, 3)
LOOM_DEFINE_RESULT(loom_vector_load_mask_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_load_mask_static_indices, 0)
iree_status_t loom_vector_load_mask_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t mask,
    loom_may_consume loom_value_id_t passthrough,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_load_mask_vtable;
iree_status_t loom_vector_load_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_STORE_MASK: Masked vector store into a typed view; masked-off lanes leave memory unchanged.
// vector.store.mask %v, %view[%row, %col], %mask : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>
LOOM_DEFINE_ISA(loom_vector_store_mask_isa, LOOM_OP_VECTOR_STORE_MASK)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_mask, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_store_mask_indices, 3)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_store_mask_static_indices, 0)
iree_status_t loom_vector_store_mask_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t mask,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_store_mask_vtable;
iree_status_t loom_vector_store_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SELECT: Lanewise select from two same-typed vector values using an i1 mask vector.
// %r = vector.select %mask, %a, %b : vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_select_isa, LOOM_OP_VECTOR_SELECT)
LOOM_DEFINE_OPERAND(loom_vector_select_condition, 0)
LOOM_DEFINE_OPERAND(loom_vector_select_true_value, 1)
LOOM_DEFINE_OPERAND(loom_vector_select_false_value, 2)
LOOM_DEFINE_RESULT(loom_vector_select_result, 0)
iree_status_t loom_vector_select_build(
    loom_builder_t* builder,
    loom_value_id_t condition,
    loom_value_id_t true_value,
    loom_value_id_t false_value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_select_vtable;

// LOOM_OP_VECTOR_CMPI: Lanewise integer comparison producing an i1 mask vector.
// %m = vector.cmpi slt, %lhs, %rhs : vector<16xi32> -> vector<16xi1>
LOOM_DEFINE_ISA(loom_vector_cmpi_isa, LOOM_OP_VECTOR_CMPI)
LOOM_DEFINE_OPERAND(loom_vector_cmpi_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_cmpi_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_cmpi_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_cmpi_predicate, 0)
iree_status_t loom_vector_cmpi_build(
    loom_builder_t* builder, uint8_t predicate,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t operand_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_cmpi_vtable;

// LOOM_OP_VECTOR_CMPF: Lanewise floating-point comparison producing an i1 mask vector.
// %m = vector.cmpf olt, %lhs, %rhs : vector<16xf32> -> vector<16xi1>
LOOM_DEFINE_ISA(loom_vector_cmpf_isa, LOOM_OP_VECTOR_CMPF)
LOOM_DEFINE_OPERAND(loom_vector_cmpf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_cmpf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_cmpf_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_cmpf_predicate, 0)
iree_status_t loom_vector_cmpf_build(
    loom_builder_t* builder, uint8_t predicate,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t operand_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_cmpf_vtable;

// LOOM_OP_VECTOR_ADDF: Lanewise floating-point addition.
// vector.addf
LOOM_DEFINE_ISA(loom_vector_addf_isa, LOOM_OP_VECTOR_ADDF)
LOOM_DEFINE_OPERAND(loom_vector_addf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_addf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_addf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_addf_assumptions)
iree_status_t loom_vector_addf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_addf_vtable;

// LOOM_OP_VECTOR_MULF: Lanewise floating-point multiplication.
// vector.mulf
LOOM_DEFINE_ISA(loom_vector_mulf_isa, LOOM_OP_VECTOR_MULF)
LOOM_DEFINE_OPERAND(loom_vector_mulf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_mulf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_mulf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_mulf_assumptions)
iree_status_t loom_vector_mulf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_mulf_vtable;

// LOOM_OP_VECTOR_FMAF: Lanewise fused multiply-add: a*b + c with single rounding.
// %r = vector.fmaf %a, %b, %c : vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_fmaf_isa, LOOM_OP_VECTOR_FMAF)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_a, 0)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_b, 1)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_c, 2)
LOOM_DEFINE_RESULT(loom_vector_fmaf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_fmaf_assumptions)
iree_status_t loom_vector_fmaf_build(
    loom_builder_t* builder,
    uint8_t instance_flags,
    loom_value_id_t a,
    loom_value_id_t b,
    loom_value_id_t c,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fmaf_vtable;

// LOOM_OP_VECTOR_ADDI: Lanewise integer addition.
// vector.addi
LOOM_DEFINE_ISA(loom_vector_addi_isa, LOOM_OP_VECTOR_ADDI)
LOOM_DEFINE_OPERAND(loom_vector_addi_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_addi_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_addi_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_addi_overflow)
iree_status_t loom_vector_addi_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_addi_vtable;

// LOOM_OP_VECTOR_MULI: Lanewise integer multiplication.
// vector.muli
LOOM_DEFINE_ISA(loom_vector_muli_isa, LOOM_OP_VECTOR_MULI)
LOOM_DEFINE_OPERAND(loom_vector_muli_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_muli_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_muli_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_muli_overflow)
iree_status_t loom_vector_muli_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_muli_vtable;

// LOOM_OP_VECTOR_SQRTF: Lanewise square root.
// vector.sqrtf
LOOM_DEFINE_ISA(loom_vector_sqrtf_isa, LOOM_OP_VECTOR_SQRTF)
LOOM_DEFINE_OPERAND(loom_vector_sqrtf_input, 0)
LOOM_DEFINE_RESULT(loom_vector_sqrtf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_sqrtf_assumptions)
iree_status_t loom_vector_sqrtf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t input, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_sqrtf_vtable;

// LOOM_OP_VECTOR_EXTF: Lanewise floating-point precision extension.
// vector.extf
LOOM_DEFINE_ISA(loom_vector_extf_isa, LOOM_OP_VECTOR_EXTF)
LOOM_DEFINE_OPERAND(loom_vector_extf_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extf_result, 0)
iree_status_t loom_vector_extf_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extf_vtable;
iree_status_t loom_vector_extf_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_FPTRUNC: Lanewise floating-point precision truncation.
// vector.fptrunc
LOOM_DEFINE_ISA(loom_vector_fptrunc_isa, LOOM_OP_VECTOR_FPTRUNC)
LOOM_DEFINE_OPERAND(loom_vector_fptrunc_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptrunc_result, 0)
iree_status_t loom_vector_fptrunc_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptrunc_vtable;
iree_status_t loom_vector_fptrunc_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTSI: Lanewise signed integer extension.
// vector.extsi
LOOM_DEFINE_ISA(loom_vector_extsi_isa, LOOM_OP_VECTOR_EXTSI)
LOOM_DEFINE_OPERAND(loom_vector_extsi_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extsi_result, 0)
iree_status_t loom_vector_extsi_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extsi_vtable;
iree_status_t loom_vector_extsi_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTUI: Lanewise unsigned integer extension.
// vector.extui
LOOM_DEFINE_ISA(loom_vector_extui_isa, LOOM_OP_VECTOR_EXTUI)
LOOM_DEFINE_OPERAND(loom_vector_extui_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extui_result, 0)
iree_status_t loom_vector_extui_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extui_vtable;
iree_status_t loom_vector_extui_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_TRUNCI: Lanewise integer truncation.
// vector.trunci
LOOM_DEFINE_ISA(loom_vector_trunci_isa, LOOM_OP_VECTOR_TRUNCI)
LOOM_DEFINE_OPERAND(loom_vector_trunci_input, 0)
LOOM_DEFINE_RESULT(loom_vector_trunci_result, 0)
iree_status_t loom_vector_trunci_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_trunci_vtable;
iree_status_t loom_vector_trunci_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SITOFP: Lanewise signed integer to floating-point conversion.
// vector.sitofp
LOOM_DEFINE_ISA(loom_vector_sitofp_isa, LOOM_OP_VECTOR_SITOFP)
LOOM_DEFINE_OPERAND(loom_vector_sitofp_input, 0)
LOOM_DEFINE_RESULT(loom_vector_sitofp_result, 0)
iree_status_t loom_vector_sitofp_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_sitofp_vtable;

// LOOM_OP_VECTOR_UITOFP: Lanewise unsigned integer to floating-point conversion.
// vector.uitofp
LOOM_DEFINE_ISA(loom_vector_uitofp_isa, LOOM_OP_VECTOR_UITOFP)
LOOM_DEFINE_OPERAND(loom_vector_uitofp_input, 0)
LOOM_DEFINE_RESULT(loom_vector_uitofp_result, 0)
iree_status_t loom_vector_uitofp_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_uitofp_vtable;

// LOOM_OP_VECTOR_FPTOSI: Lanewise floating-point to signed integer conversion.
// vector.fptosi
LOOM_DEFINE_ISA(loom_vector_fptosi_isa, LOOM_OP_VECTOR_FPTOSI)
LOOM_DEFINE_OPERAND(loom_vector_fptosi_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptosi_result, 0)
iree_status_t loom_vector_fptosi_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptosi_vtable;

// LOOM_OP_VECTOR_FPTOUI: Lanewise floating-point to unsigned integer conversion.
// vector.fptoui
LOOM_DEFINE_ISA(loom_vector_fptoui_isa, LOOM_OP_VECTOR_FPTOUI)
LOOM_DEFINE_OPERAND(loom_vector_fptoui_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptoui_result, 0)
iree_status_t loom_vector_fptoui_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptoui_vtable;

// LOOM_OP_VECTOR_BITCAST: Lanewise bit reinterpretation between same-shaped vector types.
// %r = vector.bitcast %input : vector<16xf32> to vector<16xi32>
LOOM_DEFINE_ISA(loom_vector_bitcast_isa, LOOM_OP_VECTOR_BITCAST)
LOOM_DEFINE_OPERAND(loom_vector_bitcast_input, 0)
LOOM_DEFINE_RESULT(loom_vector_bitcast_result, 0)
iree_status_t loom_vector_bitcast_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitcast_vtable;
iree_status_t loom_vector_bitcast_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_REDUCE: Reduce all lanes of a vector into a scalar accumulator/result.
// %sum = vector.reduce<addf> %v, %zero : vector<16xf32> -> f32
LOOM_DEFINE_ISA(loom_vector_reduce_isa, LOOM_OP_VECTOR_REDUCE)
LOOM_DEFINE_OPERAND(loom_vector_reduce_input, 0)
LOOM_DEFINE_OPERAND(loom_vector_reduce_init, 1)
LOOM_DEFINE_RESULT(loom_vector_reduce_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_reduce_kind, 0)
iree_status_t loom_vector_reduce_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_may_consume loom_value_id_t input,
    loom_may_consume loom_value_id_t init,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_reduce_vtable;
iree_status_t loom_vector_reduce_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the vector dialect.
const loom_op_vtable_t* const* loom_vector_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_VECTOR_OPS_H_
