// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED by loom.gen.c_tables — do not edit.
// Regenerate: python3 loom/py/loom/gen/run.py c_tables
// clang-format off

#ifndef LOOM_OPS_VECTOR_OPS_H_
#define LOOM_OPS_VECTOR_OPS_H_

#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
  LOOM_OP_VECTOR_CONSTANT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 0),
  LOOM_OP_VECTOR_SPLAT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 1),
  LOOM_OP_VECTOR_BROADCAST = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 2),
  LOOM_OP_VECTOR_FROM_ELEMENTS = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 3),
  LOOM_OP_VECTOR_EXTRACT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 4),
  LOOM_OP_VECTOR_INSERT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 5),
  LOOM_OP_VECTOR_SLICE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 6),
  LOOM_OP_VECTOR_CONCAT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 7),
  LOOM_OP_VECTOR_TRANSPOSE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 8),
  LOOM_OP_VECTOR_SHUFFLE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 9),
  LOOM_OP_VECTOR_INTERLEAVE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 10),
  LOOM_OP_VECTOR_DEINTERLEAVE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 11),
  LOOM_OP_VECTOR_TABLE_LOOKUP = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 12),
  LOOM_OP_VECTOR_TRANSFORM = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 13),
  LOOM_OP_VECTOR_LOAD = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 14),
  LOOM_OP_VECTOR_STORE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 15),
  LOOM_OP_VECTOR_LOAD_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 16),
  LOOM_OP_VECTOR_STORE_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 17),
  LOOM_OP_VECTOR_LOAD_EXPAND = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 18),
  LOOM_OP_VECTOR_STORE_COMPRESS = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 19),
  LOOM_OP_VECTOR_GATHER = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 20),
  LOOM_OP_VECTOR_SCATTER = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 21),
  LOOM_OP_VECTOR_GATHER_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 22),
  LOOM_OP_VECTOR_SCATTER_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 23),
  LOOM_OP_VECTOR_ATOMIC_REDUCE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 24),
  LOOM_OP_VECTOR_ATOMIC_REDUCE_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 25),
  LOOM_OP_VECTOR_ATOMIC_RMW = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 26),
  LOOM_OP_VECTOR_ATOMIC_RMW_MASK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 27),
  LOOM_OP_VECTOR_SELECT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 28),
  LOOM_OP_VECTOR_CMPI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 29),
  LOOM_OP_VECTOR_CMPF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 30),
  LOOM_OP_VECTOR_ADDF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 31),
  LOOM_OP_VECTOR_MULF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 32),
  LOOM_OP_VECTOR_FMAF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 33),
  LOOM_OP_VECTOR_ADDI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 34),
  LOOM_OP_VECTOR_MULI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 35),
  LOOM_OP_VECTOR_SQRTF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 36),
  LOOM_OP_VECTOR_EXTF = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 37),
  LOOM_OP_VECTOR_FPTRUNC = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 38),
  LOOM_OP_VECTOR_EXTSI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 39),
  LOOM_OP_VECTOR_EXTUI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 40),
  LOOM_OP_VECTOR_TRUNCI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 41),
  LOOM_OP_VECTOR_SITOFP = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 42),
  LOOM_OP_VECTOR_UITOFP = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 43),
  LOOM_OP_VECTOR_FPTOSI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 44),
  LOOM_OP_VECTOR_FPTOUI = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 45),
  LOOM_OP_VECTOR_BITCAST = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 46),
  LOOM_OP_VECTOR_BITFIELD_EXTRACTU = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 47),
  LOOM_OP_VECTOR_BITFIELD_EXTRACTS = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 48),
  LOOM_OP_VECTOR_BITFIELD_INSERT = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 49),
  LOOM_OP_VECTOR_BITPACK = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 50),
  LOOM_OP_VECTOR_BITUNPACKU = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 51),
  LOOM_OP_VECTOR_BITUNPACKS = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 52),
  LOOM_OP_VECTOR_DOT4I = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 53),
  LOOM_OP_VECTOR_REDUCE = LOOM_OP_KIND(LOOM_DIALECT_VECTOR, 54),
  LOOM_OP_VECTOR_COUNT_ = 55,
};

// Floating-point value-domain assumptions for vector operations.
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NNAN ((uint8_t)1)
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NINF ((uint8_t)2)
#define LOOM_VECTOR_FLOATASSUMPTIONFLAGS_NSZ ((uint8_t)4)

// Integer overflow behavior flags.
#define LOOM_VECTOR_INTOVERFLOWFLAGS_NSW ((uint8_t)1)
#define LOOM_VECTOR_INTOVERFLOWFLAGS_NUW ((uint8_t)2)

// Read-modify-write operations supported by vector atomics.
typedef enum loom_vector_kind_e {
  LOOM_VECTOR_KIND_XCHGI = 0,
  LOOM_VECTOR_KIND_XCHGF = 1,
  LOOM_VECTOR_KIND_ADDI = 2,
  LOOM_VECTOR_KIND_ADDF = 3,
  LOOM_VECTOR_KIND_SUBI = 4,
  LOOM_VECTOR_KIND_ANDI = 5,
  LOOM_VECTOR_KIND_ORI = 6,
  LOOM_VECTOR_KIND_XORI = 7,
  LOOM_VECTOR_KIND_MINSI = 8,
  LOOM_VECTOR_KIND_MAXSI = 9,
  LOOM_VECTOR_KIND_MINUI = 10,
  LOOM_VECTOR_KIND_MAXUI = 11,
  LOOM_VECTOR_KIND_MINIMUMF = 12,
  LOOM_VECTOR_KIND_MAXIMUMF = 13,
  LOOM_VECTOR_KIND_MINNUMF = 14,
  LOOM_VECTOR_KIND_MAXNUMF = 15,
  LOOM_VECTOR_KIND_COUNT_ = 16,
} loom_vector_kind_t;

// Atomic memory ordering. The relaxed case lowers to LLVM monotonic RMW ordering.
typedef enum loom_vector_ordering_e {
  LOOM_VECTOR_ORDERING_RELAXED = 0,
  LOOM_VECTOR_ORDERING_ACQUIRE = 1,
  LOOM_VECTOR_ORDERING_RELEASE = 2,
  LOOM_VECTOR_ORDERING_ACQ_REL = 3,
  LOOM_VECTOR_ORDERING_SEQ_CST = 4,
  LOOM_VECTOR_ORDERING_COUNT_ = 5,
} loom_vector_ordering_t;

// Synchronization scope for atomic memory effects.
typedef enum loom_vector_scope_e {
  LOOM_VECTOR_SCOPE_THREAD = 0,
  LOOM_VECTOR_SCOPE_SUBGROUP = 1,
  LOOM_VECTOR_SCOPE_WORKGROUP = 2,
  LOOM_VECTOR_SCOPE_DEVICE = 3,
  LOOM_VECTOR_SCOPE_SYSTEM = 4,
  LOOM_VECTOR_SCOPE_COUNT_ = 5,
} loom_vector_scope_t;

// Integer comparison predicates.
typedef enum loom_vector_cmpi_predicate_e {
  LOOM_VECTOR_CMPI_PREDICATE_EQ = 0,
  LOOM_VECTOR_CMPI_PREDICATE_NE = 1,
  LOOM_VECTOR_CMPI_PREDICATE_SLT = 2,
  LOOM_VECTOR_CMPI_PREDICATE_SLE = 3,
  LOOM_VECTOR_CMPI_PREDICATE_SGT = 4,
  LOOM_VECTOR_CMPI_PREDICATE_SGE = 5,
  LOOM_VECTOR_CMPI_PREDICATE_ULT = 6,
  LOOM_VECTOR_CMPI_PREDICATE_ULE = 7,
  LOOM_VECTOR_CMPI_PREDICATE_UGT = 8,
  LOOM_VECTOR_CMPI_PREDICATE_UGE = 9,
  LOOM_VECTOR_CMPI_PREDICATE_COUNT_ = 10,
} loom_vector_cmpi_predicate_t;

// Floating-point comparison predicates (IEEE 754 total order).
typedef enum loom_vector_cmpf_predicate_e {
  LOOM_VECTOR_CMPF_PREDICATE_OEQ = 0,
  LOOM_VECTOR_CMPF_PREDICATE_OGT = 1,
  LOOM_VECTOR_CMPF_PREDICATE_OGE = 2,
  LOOM_VECTOR_CMPF_PREDICATE_OLT = 3,
  LOOM_VECTOR_CMPF_PREDICATE_OLE = 4,
  LOOM_VECTOR_CMPF_PREDICATE_ONE = 5,
  LOOM_VECTOR_CMPF_PREDICATE_ORD = 6,
  LOOM_VECTOR_CMPF_PREDICATE_UEQ = 7,
  LOOM_VECTOR_CMPF_PREDICATE_UGT = 8,
  LOOM_VECTOR_CMPF_PREDICATE_UGE = 9,
  LOOM_VECTOR_CMPF_PREDICATE_ULT = 10,
  LOOM_VECTOR_CMPF_PREDICATE_ULE = 11,
  LOOM_VECTOR_CMPF_PREDICATE_UNE = 12,
  LOOM_VECTOR_CMPF_PREDICATE_UNO = 13,
  LOOM_VECTOR_CMPF_PREDICATE_COUNT_ = 14,
} loom_vector_cmpf_predicate_t;

// Signedness variants for four-lane i8 dot products accumulated into i32 lanes.
typedef enum loom_vector_dot4i_kind_e {
  LOOM_VECTOR_DOT4I_KIND_S8S8 = 0,
  LOOM_VECTOR_DOT4I_KIND_U8S8 = 1,
  LOOM_VECTOR_DOT4I_KIND_S8U8 = 2,
  LOOM_VECTOR_DOT4I_KIND_U8U8 = 3,
  LOOM_VECTOR_DOT4I_KIND_COUNT_ = 4,
} loom_vector_dot4i_kind_t;

// Combining operations for vector reductions.
typedef enum loom_vector_reduce_kind_e {
  LOOM_VECTOR_REDUCE_KIND_ADDI = 0,
  LOOM_VECTOR_REDUCE_KIND_ADDF = 1,
  LOOM_VECTOR_REDUCE_KIND_MULI = 2,
  LOOM_VECTOR_REDUCE_KIND_MULF = 3,
  LOOM_VECTOR_REDUCE_KIND_MINSI = 4,
  LOOM_VECTOR_REDUCE_KIND_MAXSI = 5,
  LOOM_VECTOR_REDUCE_KIND_MINUI = 6,
  LOOM_VECTOR_REDUCE_KIND_MAXUI = 7,
  LOOM_VECTOR_REDUCE_KIND_ANDI = 8,
  LOOM_VECTOR_REDUCE_KIND_ORI = 9,
  LOOM_VECTOR_REDUCE_KIND_XORI = 10,
  LOOM_VECTOR_REDUCE_KIND_MINIMUMF = 11,
  LOOM_VECTOR_REDUCE_KIND_MAXIMUMF = 12,
  LOOM_VECTOR_REDUCE_KIND_MINNUMF = 13,
  LOOM_VECTOR_REDUCE_KIND_MAXNUMF = 14,
  LOOM_VECTOR_REDUCE_KIND_COUNT_ = 15,
} loom_vector_reduce_kind_t;

// LOOM_OP_VECTOR_CONSTANT: Materialize a compile-time splat constant vector value.
// %v = vector.constant 0.0 : vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_constant_isa, LOOM_OP_VECTOR_CONSTANT)
LOOM_DEFINE_RESULT(loom_vector_constant_result, 0)
LOOM_DEFINE_ATTR_ANY(loom_vector_constant_value, 0)
iree_status_t loom_vector_constant_build(
    loom_builder_t* builder,
    loom_attribute_t value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_constant_vtable;
iree_status_t loom_vector_constant_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SPLAT: Replicate one scalar value to every lane of a vector result.
// %vec = vector.splat %scalar : f32 -> vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_splat_isa, LOOM_OP_VECTOR_SPLAT)
LOOM_DEFINE_OPERAND(loom_vector_splat_scalar, 0)
LOOM_DEFINE_RESULT(loom_vector_splat_result, 0)
iree_status_t loom_vector_splat_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t scalar,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_splat_vtable;

// LOOM_OP_VECTOR_BROADCAST: Broadcast a vector value to a vector result with a compatible shape.
// %wide = vector.broadcast %v : vector<4xf32> -> vector<16x4xf32>
LOOM_DEFINE_ISA(loom_vector_broadcast_isa, LOOM_OP_VECTOR_BROADCAST)
LOOM_DEFINE_OPERAND(loom_vector_broadcast_source, 0)
LOOM_DEFINE_RESULT(loom_vector_broadcast_result, 0)
iree_status_t loom_vector_broadcast_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_broadcast_vtable;
iree_status_t loom_vector_broadcast_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_FROM_ELEMENTS: Build a vector from scalar element operands in lane order.
// %v = vector.from_elements %a, %b, %c, %d : f32, f32, f32, f32 -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_from_elements_isa, LOOM_OP_VECTOR_FROM_ELEMENTS)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_from_elements_elements, 0)
LOOM_DEFINE_RESULT(loom_vector_from_elements_result, 0)
iree_status_t loom_vector_from_elements_build(
    loom_builder_t* builder,
    loom_may_consume const loom_value_id_t* elements,
    iree_host_size_t elements_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_from_elements_vtable;
iree_status_t loom_vector_from_elements_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTRACT: Extract a scalar or subvector from a vector at explicit indices.
// %x = vector.extract %v[%i] : vector<[%n]xf32> -> f32
LOOM_DEFINE_ISA(loom_vector_extract_isa, LOOM_OP_VECTOR_EXTRACT)
LOOM_DEFINE_OPERAND(loom_vector_extract_source, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_extract_indices, 1)
LOOM_DEFINE_RESULT(loom_vector_extract_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_extract_static_indices, 0)
iree_status_t loom_vector_extract_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extract_vtable;
iree_status_t loom_vector_extract_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_INSERT: Insert a scalar or subvector into a vector at explicit indices.
// %r = vector.insert %x into %v[%i] : f32, vector<[%n]xf32> -> vector<[%n]xf32>
LOOM_DEFINE_ISA(loom_vector_insert_isa, LOOM_OP_VECTOR_INSERT)
LOOM_DEFINE_OPERAND(loom_vector_insert_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_insert_dest, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_insert_indices, 2)
LOOM_DEFINE_RESULT(loom_vector_insert_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_insert_static_indices, 0)
iree_status_t loom_vector_insert_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t value,
    loom_may_consume loom_value_id_t dest,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_insert_vtable;
iree_status_t loom_vector_insert_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SLICE: Extract a rank-preserving contiguous register subvector at explicit offsets.
// %tail = vector.slice %v[%i] : vector<[%n]xf32> -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_slice_isa, LOOM_OP_VECTOR_SLICE)
LOOM_DEFINE_OPERAND(loom_vector_slice_source, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_slice_offsets, 1)
LOOM_DEFINE_RESULT(loom_vector_slice_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_slice_static_offsets, 0)
iree_status_t loom_vector_slice_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    const loom_value_id_t* offsets,
    iree_host_size_t offsets_count,
    const int64_t* static_offsets,
    iree_host_size_t static_offsets_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_slice_vtable;
iree_status_t loom_vector_slice_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_CONCAT: Concatenate same-rank vectors along one explicit result axis.
// %wide = vector.concat<0> %a, %b : vector<4xf32>, vector<4xf32> -> vector<8xf32>
LOOM_DEFINE_ISA(loom_vector_concat_isa, LOOM_OP_VECTOR_CONCAT)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_concat_inputs, 0)
LOOM_DEFINE_RESULT(loom_vector_concat_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_concat_axis, 0)
iree_status_t loom_vector_concat_build(
    loom_builder_t* builder,
    int64_t axis,
    loom_may_consume const loom_value_id_t* inputs,
    iree_host_size_t inputs_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_concat_vtable;
iree_status_t loom_vector_concat_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_TRANSPOSE: Reorder vector register axes using an explicit result-axis to source-axis permutation.
// %t = vector.transpose<[1, 0]> %v : vector<4x8xf32> -> vector<8x4xf32>
LOOM_DEFINE_ISA(loom_vector_transpose_isa, LOOM_OP_VECTOR_TRANSPOSE)
LOOM_DEFINE_OPERAND(loom_vector_transpose_source, 0)
LOOM_DEFINE_RESULT(loom_vector_transpose_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_transpose_permutation, 0)
iree_status_t loom_vector_transpose_build(
    loom_builder_t* builder,
    const int64_t* permutation,
    iree_host_size_t permutation_count,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_transpose_vtable;
iree_status_t loom_vector_transpose_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SHUFFLE: Build a same-typed rank-1 vector by selecting source register lanes with a static lane map; duplicate lanes are allowed.
// %rev = vector.shuffle<[3, 2, 1, 0]> %v : vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_shuffle_isa, LOOM_OP_VECTOR_SHUFFLE)
LOOM_DEFINE_OPERAND(loom_vector_shuffle_source, 0)
LOOM_DEFINE_RESULT(loom_vector_shuffle_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_shuffle_source_lanes, 0)
iree_status_t loom_vector_shuffle_build(
    loom_builder_t* builder,
    const int64_t* source_lanes,
    iree_host_size_t source_lanes_count,
    loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_shuffle_vtable;
iree_status_t loom_vector_shuffle_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_INTERLEAVE: Interleave two same-typed vectors along one axis; even lanes come from the first operand and odd lanes come from the second operand.
// %r = vector.interleave<0> %lo, %hi : vector<16xi8>, vector<16xi8> -> vector<32xi8>
LOOM_DEFINE_ISA(loom_vector_interleave_isa, LOOM_OP_VECTOR_INTERLEAVE)
LOOM_DEFINE_OPERAND(loom_vector_interleave_even, 0)
LOOM_DEFINE_OPERAND(loom_vector_interleave_odd, 1)
LOOM_DEFINE_RESULT(loom_vector_interleave_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_interleave_axis, 0)
iree_status_t loom_vector_interleave_build(
    loom_builder_t* builder,
    int64_t axis,
    loom_may_consume loom_value_id_t even,
    loom_may_consume loom_value_id_t odd,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_interleave_vtable;
iree_status_t loom_vector_interleave_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_DEINTERLEAVE: Split one vector along an axis into even-position and odd-position vectors of the same type.
// %lo, %hi = vector.deinterleave<0> %r : vector<32xi8> -> vector<16xi8>, vector<16xi8>
LOOM_DEFINE_ISA(loom_vector_deinterleave_isa, LOOM_OP_VECTOR_DEINTERLEAVE)
LOOM_DEFINE_OPERAND(loom_vector_deinterleave_source, 0)
LOOM_DEFINE_VARIADIC_RESULTS(loom_vector_deinterleave_results, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_deinterleave_axis, 0)
iree_status_t loom_vector_deinterleave_build(
    loom_builder_t* builder,
    int64_t axis,
    loom_may_consume loom_value_id_t source,
    const loom_type_t* result_types,
    iree_host_size_t result_count,
    const loom_tied_result_t* tied_results,
    iree_host_size_t tied_result_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_deinterleave_vtable;
iree_status_t loom_vector_deinterleave_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_TABLE_LOOKUP: Select table vector lanes using explicit integer index lanes; every index lane must be within the table extent.
// %values = vector.table.lookup %grid[%codes] : vector<16xf16>, vector<32xi8> -> vector<32xf16>
LOOM_DEFINE_ISA(loom_vector_table_lookup_isa, LOOM_OP_VECTOR_TABLE_LOOKUP)
LOOM_DEFINE_OPERAND(loom_vector_table_lookup_table, 0)
LOOM_DEFINE_OPERAND(loom_vector_table_lookup_indices, 1)
LOOM_DEFINE_RESULT(loom_vector_table_lookup_result, 0)
iree_status_t loom_vector_table_lookup_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t table,
    loom_may_consume loom_value_id_t indices,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_table_lookup_vtable;
iree_status_t loom_vector_table_lookup_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_TRANSFORM: Apply an explicit numeric transform descriptor to vector register lanes.
// %r = vector.transform %v, %xf : vector<128xf32>, encoding -> vector<128xf32>
LOOM_DEFINE_ISA(loom_vector_transform_isa, LOOM_OP_VECTOR_TRANSFORM)
LOOM_DEFINE_OPERAND(loom_vector_transform_source, 0)
LOOM_DEFINE_OPERAND(loom_vector_transform_transform, 1)
LOOM_DEFINE_RESULT(loom_vector_transform_result, 0)
iree_status_t loom_vector_transform_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    loom_may_consume loom_value_id_t transform,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_transform_vtable;
iree_status_t loom_vector_transform_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_LOAD: Load a vector footprint from a typed view at a full-rank logical origin.
// %v = vector.load %view[%row, %col] : view<[%m]x[%n]xf32, %layout> -> vector<4x8xf32>
LOOM_DEFINE_ISA(loom_vector_load_isa, LOOM_OP_VECTOR_LOAD)
LOOM_DEFINE_OPERAND(loom_vector_load_view, 0)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_load_indices, 1)
LOOM_DEFINE_RESULT(loom_vector_load_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_load_static_indices, 0)
iree_status_t loom_vector_load_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_load_vtable;
iree_status_t loom_vector_load_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_STORE: Store a vector footprint into a typed view at a full-rank logical origin.
// vector.store %v, %view[%row, %col] : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>
LOOM_DEFINE_ISA(loom_vector_store_isa, LOOM_OP_VECTOR_STORE)
LOOM_DEFINE_OPERAND(loom_vector_store_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_store_view, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_store_indices, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_store_static_indices, 0)
iree_status_t loom_vector_store_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_store_vtable;
iree_status_t loom_vector_store_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_LOAD_MASK: Masked vector load from a typed view; masked-off lanes take the passthrough value.
// %v = vector.load.mask %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>, vector<4x8xf32> -> vector<4x8xf32>
LOOM_DEFINE_ISA(loom_vector_load_mask_isa, LOOM_OP_VECTOR_LOAD_MASK)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_view, 0)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_mask, 1)
LOOM_DEFINE_OPERAND(loom_vector_load_mask_passthrough, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_load_mask_indices, 3)
LOOM_DEFINE_RESULT(loom_vector_load_mask_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_load_mask_static_indices, 0)
iree_status_t loom_vector_load_mask_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t mask,
    loom_may_consume loom_value_id_t passthrough,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_load_mask_vtable;
iree_status_t loom_vector_load_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_STORE_MASK: Masked vector store into a typed view; masked-off lanes leave memory unchanged.
// vector.store.mask %v, %view[%row, %col], %mask : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>
LOOM_DEFINE_ISA(loom_vector_store_mask_isa, LOOM_OP_VECTOR_STORE_MASK)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_store_mask_mask, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_store_mask_indices, 3)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_store_mask_static_indices, 0)
iree_status_t loom_vector_store_mask_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t mask,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_store_mask_vtable;
iree_status_t loom_vector_store_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_LOAD_EXPAND: Rank-1 masked expand load from consecutive view elements; active lanes consume memory in increasing lane order and inactive lanes take the passthrough value.
// %v = vector.load.expand %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_load_expand_isa, LOOM_OP_VECTOR_LOAD_EXPAND)
LOOM_DEFINE_OPERAND(loom_vector_load_expand_view, 0)
LOOM_DEFINE_OPERAND(loom_vector_load_expand_mask, 1)
LOOM_DEFINE_OPERAND(loom_vector_load_expand_passthrough, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_load_expand_indices, 3)
LOOM_DEFINE_RESULT(loom_vector_load_expand_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_load_expand_static_indices, 0)
iree_status_t loom_vector_load_expand_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t mask,
    loom_may_consume loom_value_id_t passthrough,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_load_expand_vtable;
iree_status_t loom_vector_load_expand_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_STORE_COMPRESS: Rank-1 masked compress store to consecutive view elements; active lanes produce memory in increasing lane order and inactive lanes do not write.
// vector.store.compress %v, %view[%row, %col], %mask : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xi1>
LOOM_DEFINE_ISA(loom_vector_store_compress_isa, LOOM_OP_VECTOR_STORE_COMPRESS)
LOOM_DEFINE_OPERAND(loom_vector_store_compress_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_store_compress_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_store_compress_mask, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_store_compress_indices, 3)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_store_compress_static_indices, 0)
iree_status_t loom_vector_store_compress_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t mask,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_store_compress_vtable;
iree_status_t loom_vector_store_compress_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_GATHER: Gather a vector from per-lane signed element offsets relative to a full-rank view origin.
// %v = vector.gather %view[%row, %col][%offsets] : view<[%m]x[%n]xf32, %layout>, vector<4xindex> -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_gather_isa, LOOM_OP_VECTOR_GATHER)
LOOM_DEFINE_OPERAND(loom_vector_gather_view, 0)
LOOM_DEFINE_OPERAND(loom_vector_gather_offsets, 1)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_gather_indices, 2)
LOOM_DEFINE_RESULT(loom_vector_gather_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_gather_static_indices, 0)
iree_status_t loom_vector_gather_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t offsets,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_gather_vtable;
iree_status_t loom_vector_gather_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SCATTER: Non-atomic scatter of a vector to per-lane signed element offsets relative to a full-rank view origin; active lane addresses must be distinct.
// vector.scatter %v, %view[%row, %col][%offsets] : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>
LOOM_DEFINE_ISA(loom_vector_scatter_isa, LOOM_OP_VECTOR_SCATTER)
LOOM_DEFINE_OPERAND(loom_vector_scatter_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_scatter_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_scatter_offsets, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_scatter_indices, 3)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_scatter_static_indices, 0)
iree_status_t loom_vector_scatter_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t offsets,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_scatter_vtable;
iree_status_t loom_vector_scatter_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_GATHER_MASK: Masked vector gather from per-lane signed element offsets; masked-off lanes take the passthrough value.
// %v = vector.gather.mask %view[%row, %col][%offsets], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_gather_mask_isa, LOOM_OP_VECTOR_GATHER_MASK)
LOOM_DEFINE_OPERAND(loom_vector_gather_mask_view, 0)
LOOM_DEFINE_OPERAND(loom_vector_gather_mask_offsets, 1)
LOOM_DEFINE_OPERAND(loom_vector_gather_mask_mask, 2)
LOOM_DEFINE_OPERAND(loom_vector_gather_mask_passthrough, 3)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_gather_mask_indices, 4)
LOOM_DEFINE_RESULT(loom_vector_gather_mask_result, 0)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_gather_mask_static_indices, 0)
iree_status_t loom_vector_gather_mask_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t offsets,
    loom_may_consume loom_value_id_t mask,
    loom_may_consume loom_value_id_t passthrough,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_gather_mask_vtable;
iree_status_t loom_vector_gather_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SCATTER_MASK: Masked non-atomic scatter; masked-off lanes leave memory unchanged and active lane addresses must be distinct.
// vector.scatter.mask %v, %view[%row, %col][%offsets], %mask : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>
LOOM_DEFINE_ISA(loom_vector_scatter_mask_isa, LOOM_OP_VECTOR_SCATTER_MASK)
LOOM_DEFINE_OPERAND(loom_vector_scatter_mask_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_scatter_mask_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_scatter_mask_offsets, 2)
LOOM_DEFINE_OPERAND(loom_vector_scatter_mask_mask, 3)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_scatter_mask_indices, 4)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_scatter_mask_static_indices, 0)
iree_status_t loom_vector_scatter_mask_build(
    loom_builder_t* builder,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t offsets,
    loom_value_id_t mask,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_scatter_mask_vtable;
iree_status_t loom_vector_scatter_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_ATOMIC_REDUCE: Atomic no-result scatter reduction/update into per-lane signed element offsets. Duplicate active lane addresses are allowed and are serialized by the atomic memory contract.
// vector.atomic.reduce<addi> %v, %view[%row, %col][%offsets] {ordering = relaxed, scope = workgroup} : vector<4xi32>, view<[%m]x[%n]xi32, %layout>, vector<4xindex>
LOOM_DEFINE_ISA(loom_vector_atomic_reduce_isa, LOOM_OP_VECTOR_ATOMIC_REDUCE)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_offsets, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_atomic_reduce_indices, 3)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_kind, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_ordering, 1)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_scope, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_atomic_reduce_static_indices, 3)
iree_status_t loom_vector_atomic_reduce_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t offsets,
    uint8_t ordering,
    uint8_t scope,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_atomic_reduce_vtable;
iree_status_t loom_vector_atomic_reduce_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_ATOMIC_REDUCE_MASK: Masked atomic no-result scatter reduction/update; masked-off lanes do not access memory.
// vector.atomic.reduce.mask<addf> %v, %view[%row, %col][%offsets], %mask {ordering = relaxed, scope = device} : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>
LOOM_DEFINE_ISA(loom_vector_atomic_reduce_mask_isa, LOOM_OP_VECTOR_ATOMIC_REDUCE_MASK)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_mask_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_mask_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_mask_offsets, 2)
LOOM_DEFINE_OPERAND(loom_vector_atomic_reduce_mask_mask, 3)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_atomic_reduce_mask_indices, 4)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_mask_kind, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_mask_ordering, 1)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_reduce_mask_scope, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_atomic_reduce_mask_static_indices, 3)
iree_status_t loom_vector_atomic_reduce_mask_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_value_id_t value,
    loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_value_id_t offsets,
    loom_value_id_t mask,
    uint8_t ordering,
    uint8_t scope,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_atomic_reduce_mask_vtable;
iree_status_t loom_vector_atomic_reduce_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_ATOMIC_RMW: Atomic read-modify-write at per-lane signed element offsets, returning the old memory value for each lane.
// %old = vector.atomic.rmw<addi> %v, %view[%row, %col][%offsets] {ordering = relaxed, scope = workgroup} : vector<4xi32>, view<[%m]x[%n]xi32, %layout>, vector<4xindex> -> vector<4xi32>
LOOM_DEFINE_ISA(loom_vector_atomic_rmw_isa, LOOM_OP_VECTOR_ATOMIC_RMW)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_offsets, 2)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_atomic_rmw_indices, 3)
LOOM_DEFINE_RESULT(loom_vector_atomic_rmw_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_kind, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_ordering, 1)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_scope, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_atomic_rmw_static_indices, 3)
iree_status_t loom_vector_atomic_rmw_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_may_consume loom_value_id_t value,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t offsets,
    uint8_t ordering,
    uint8_t scope,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_atomic_rmw_vtable;
iree_status_t loom_vector_atomic_rmw_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_ATOMIC_RMW_MASK: Masked atomic read-modify-write. Masked-off result lanes take the explicit passthrough value.
// %old = vector.atomic.rmw.mask<addf> %v, %view[%row, %col][%offsets], %mask, %passthrough {ordering = relaxed, scope = device} : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
LOOM_DEFINE_ISA(loom_vector_atomic_rmw_mask_isa, LOOM_OP_VECTOR_ATOMIC_RMW_MASK)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_mask_value, 0)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_mask_view, 1)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_mask_offsets, 2)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_mask_mask, 3)
LOOM_DEFINE_OPERAND(loom_vector_atomic_rmw_mask_passthrough, 4)
LOOM_DEFINE_VARIADIC_OPERANDS(loom_vector_atomic_rmw_mask_indices, 5)
LOOM_DEFINE_RESULT(loom_vector_atomic_rmw_mask_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_mask_kind, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_mask_ordering, 1)
LOOM_DEFINE_ATTR_ENUM(loom_vector_atomic_rmw_mask_scope, 2)
LOOM_DEFINE_ATTR_I64_ARRAY(loom_vector_atomic_rmw_mask_static_indices, 3)
iree_status_t loom_vector_atomic_rmw_mask_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_may_consume loom_value_id_t value,
    loom_may_consume loom_value_id_t view,
    const loom_value_id_t* indices,
    iree_host_size_t indices_count,
    const int64_t* static_indices,
    iree_host_size_t static_indices_count,
    loom_may_consume loom_value_id_t offsets,
    loom_may_consume loom_value_id_t mask,
    loom_may_consume loom_value_id_t passthrough,
    uint8_t ordering,
    uint8_t scope,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_atomic_rmw_mask_vtable;
iree_status_t loom_vector_atomic_rmw_mask_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SELECT: Lanewise select from two same-typed vector values using an i1 mask vector.
// %r = vector.select %mask, %a, %b : vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_select_isa, LOOM_OP_VECTOR_SELECT)
LOOM_DEFINE_OPERAND(loom_vector_select_condition, 0)
LOOM_DEFINE_OPERAND(loom_vector_select_true_value, 1)
LOOM_DEFINE_OPERAND(loom_vector_select_false_value, 2)
LOOM_DEFINE_RESULT(loom_vector_select_result, 0)
iree_status_t loom_vector_select_build(
    loom_builder_t* builder,
    loom_value_id_t condition,
    loom_value_id_t true_value,
    loom_value_id_t false_value,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_select_vtable;

// LOOM_OP_VECTOR_CMPI: Lanewise integer comparison producing an i1 mask vector.
// %m = vector.cmpi slt, %lhs, %rhs : vector<16xi32> -> vector<16xi1>
LOOM_DEFINE_ISA(loom_vector_cmpi_isa, LOOM_OP_VECTOR_CMPI)
LOOM_DEFINE_OPERAND(loom_vector_cmpi_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_cmpi_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_cmpi_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_cmpi_predicate, 0)
iree_status_t loom_vector_cmpi_build(
    loom_builder_t* builder, uint8_t predicate,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t operand_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_cmpi_vtable;

// LOOM_OP_VECTOR_CMPF: Lanewise floating-point comparison producing an i1 mask vector.
// %m = vector.cmpf olt, %lhs, %rhs : vector<16xf32> -> vector<16xi1>
LOOM_DEFINE_ISA(loom_vector_cmpf_isa, LOOM_OP_VECTOR_CMPF)
LOOM_DEFINE_OPERAND(loom_vector_cmpf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_cmpf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_cmpf_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_cmpf_predicate, 0)
iree_status_t loom_vector_cmpf_build(
    loom_builder_t* builder, uint8_t predicate,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t operand_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_cmpf_vtable;

// LOOM_OP_VECTOR_ADDF: Lanewise floating-point addition.
// vector.addf
LOOM_DEFINE_ISA(loom_vector_addf_isa, LOOM_OP_VECTOR_ADDF)
LOOM_DEFINE_OPERAND(loom_vector_addf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_addf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_addf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_addf_assumptions)
iree_status_t loom_vector_addf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_addf_vtable;

// LOOM_OP_VECTOR_MULF: Lanewise floating-point multiplication.
// vector.mulf
LOOM_DEFINE_ISA(loom_vector_mulf_isa, LOOM_OP_VECTOR_MULF)
LOOM_DEFINE_OPERAND(loom_vector_mulf_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_mulf_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_mulf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_mulf_assumptions)
iree_status_t loom_vector_mulf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_mulf_vtable;

// LOOM_OP_VECTOR_FMAF: Lanewise fused multiply-add: a*b + c with single rounding.
// %r = vector.fmaf %a, %b, %c : vector<16xf32>
LOOM_DEFINE_ISA(loom_vector_fmaf_isa, LOOM_OP_VECTOR_FMAF)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_a, 0)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_b, 1)
LOOM_DEFINE_OPERAND(loom_vector_fmaf_c, 2)
LOOM_DEFINE_RESULT(loom_vector_fmaf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_fmaf_assumptions)
iree_status_t loom_vector_fmaf_build(
    loom_builder_t* builder,
    uint8_t instance_flags,
    loom_value_id_t a,
    loom_value_id_t b,
    loom_value_id_t c,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fmaf_vtable;

// LOOM_OP_VECTOR_ADDI: Lanewise integer addition.
// vector.addi
LOOM_DEFINE_ISA(loom_vector_addi_isa, LOOM_OP_VECTOR_ADDI)
LOOM_DEFINE_OPERAND(loom_vector_addi_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_addi_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_addi_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_addi_overflow)
iree_status_t loom_vector_addi_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_addi_vtable;

// LOOM_OP_VECTOR_MULI: Lanewise integer multiplication.
// vector.muli
LOOM_DEFINE_ISA(loom_vector_muli_isa, LOOM_OP_VECTOR_MULI)
LOOM_DEFINE_OPERAND(loom_vector_muli_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_muli_rhs, 1)
LOOM_DEFINE_RESULT(loom_vector_muli_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_muli_overflow)
iree_status_t loom_vector_muli_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t lhs, loom_value_id_t rhs,
    loom_type_t result_type, loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_muli_vtable;

// LOOM_OP_VECTOR_SQRTF: Lanewise square root.
// vector.sqrtf
LOOM_DEFINE_ISA(loom_vector_sqrtf_isa, LOOM_OP_VECTOR_SQRTF)
LOOM_DEFINE_OPERAND(loom_vector_sqrtf_input, 0)
LOOM_DEFINE_RESULT(loom_vector_sqrtf_result, 0)
LOOM_DEFINE_INSTANCE_FLAGS(loom_vector_sqrtf_assumptions)
iree_status_t loom_vector_sqrtf_build(
    loom_builder_t* builder, uint8_t instance_flags,
    loom_value_id_t input, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_sqrtf_vtable;

// LOOM_OP_VECTOR_EXTF: Lanewise floating-point precision extension.
// vector.extf
LOOM_DEFINE_ISA(loom_vector_extf_isa, LOOM_OP_VECTOR_EXTF)
LOOM_DEFINE_OPERAND(loom_vector_extf_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extf_result, 0)
iree_status_t loom_vector_extf_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extf_vtable;
iree_status_t loom_vector_extf_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_FPTRUNC: Lanewise floating-point precision truncation.
// vector.fptrunc
LOOM_DEFINE_ISA(loom_vector_fptrunc_isa, LOOM_OP_VECTOR_FPTRUNC)
LOOM_DEFINE_OPERAND(loom_vector_fptrunc_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptrunc_result, 0)
iree_status_t loom_vector_fptrunc_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptrunc_vtable;
iree_status_t loom_vector_fptrunc_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTSI: Lanewise signed integer extension.
// vector.extsi
LOOM_DEFINE_ISA(loom_vector_extsi_isa, LOOM_OP_VECTOR_EXTSI)
LOOM_DEFINE_OPERAND(loom_vector_extsi_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extsi_result, 0)
iree_status_t loom_vector_extsi_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extsi_vtable;
iree_status_t loom_vector_extsi_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_EXTUI: Lanewise unsigned integer extension.
// vector.extui
LOOM_DEFINE_ISA(loom_vector_extui_isa, LOOM_OP_VECTOR_EXTUI)
LOOM_DEFINE_OPERAND(loom_vector_extui_input, 0)
LOOM_DEFINE_RESULT(loom_vector_extui_result, 0)
iree_status_t loom_vector_extui_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_extui_vtable;
iree_status_t loom_vector_extui_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_TRUNCI: Lanewise integer truncation.
// vector.trunci
LOOM_DEFINE_ISA(loom_vector_trunci_isa, LOOM_OP_VECTOR_TRUNCI)
LOOM_DEFINE_OPERAND(loom_vector_trunci_input, 0)
LOOM_DEFINE_RESULT(loom_vector_trunci_result, 0)
iree_status_t loom_vector_trunci_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_trunci_vtable;
iree_status_t loom_vector_trunci_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_SITOFP: Lanewise signed integer to floating-point conversion.
// vector.sitofp
LOOM_DEFINE_ISA(loom_vector_sitofp_isa, LOOM_OP_VECTOR_SITOFP)
LOOM_DEFINE_OPERAND(loom_vector_sitofp_input, 0)
LOOM_DEFINE_RESULT(loom_vector_sitofp_result, 0)
iree_status_t loom_vector_sitofp_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_sitofp_vtable;

// LOOM_OP_VECTOR_UITOFP: Lanewise unsigned integer to floating-point conversion.
// vector.uitofp
LOOM_DEFINE_ISA(loom_vector_uitofp_isa, LOOM_OP_VECTOR_UITOFP)
LOOM_DEFINE_OPERAND(loom_vector_uitofp_input, 0)
LOOM_DEFINE_RESULT(loom_vector_uitofp_result, 0)
iree_status_t loom_vector_uitofp_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_uitofp_vtable;

// LOOM_OP_VECTOR_FPTOSI: Lanewise floating-point to signed integer conversion.
// vector.fptosi
LOOM_DEFINE_ISA(loom_vector_fptosi_isa, LOOM_OP_VECTOR_FPTOSI)
LOOM_DEFINE_OPERAND(loom_vector_fptosi_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptosi_result, 0)
iree_status_t loom_vector_fptosi_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptosi_vtable;

// LOOM_OP_VECTOR_FPTOUI: Lanewise floating-point to unsigned integer conversion.
// vector.fptoui
LOOM_DEFINE_ISA(loom_vector_fptoui_isa, LOOM_OP_VECTOR_FPTOUI)
LOOM_DEFINE_OPERAND(loom_vector_fptoui_input, 0)
LOOM_DEFINE_RESULT(loom_vector_fptoui_result, 0)
iree_status_t loom_vector_fptoui_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_fptoui_vtable;

// LOOM_OP_VECTOR_BITCAST: Bitwise reinterpretation between vector register types with the same total bit count.
// %r = vector.bitcast %input : vector<16xf32> to vector<16xi32>
LOOM_DEFINE_ISA(loom_vector_bitcast_isa, LOOM_OP_VECTOR_BITCAST)
LOOM_DEFINE_OPERAND(loom_vector_bitcast_input, 0)
LOOM_DEFINE_RESULT(loom_vector_bitcast_result, 0)
iree_status_t loom_vector_bitcast_build(
    loom_builder_t* builder, loom_value_id_t input,
    loom_type_t input_type, loom_type_t result_type,
    loom_location_id_t location, loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitcast_vtable;
iree_status_t loom_vector_bitcast_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITFIELD_EXTRACTU: Extract and zero-extend one fixed bitfield from each integer source lane.
// %lo = vector.bitfield.extractu %bytes {offset = 0, width = 4} : vector<16xi8> -> vector<16xi32>
LOOM_DEFINE_ISA(loom_vector_bitfield_extractu_isa, LOOM_OP_VECTOR_BITFIELD_EXTRACTU)
LOOM_DEFINE_OPERAND(loom_vector_bitfield_extractu_source, 0)
LOOM_DEFINE_RESULT(loom_vector_bitfield_extractu_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_extractu_offset, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_extractu_width, 1)
iree_status_t loom_vector_bitfield_extractu_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    int64_t offset,
    int64_t width,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitfield_extractu_vtable;
iree_status_t loom_vector_bitfield_extractu_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITFIELD_EXTRACTS: Extract and sign-extend one fixed bitfield from each integer source lane.
// %signed = vector.bitfield.extracts %bytes {offset = 4, width = 4} : vector<16xi8> -> vector<16xi32>
LOOM_DEFINE_ISA(loom_vector_bitfield_extracts_isa, LOOM_OP_VECTOR_BITFIELD_EXTRACTS)
LOOM_DEFINE_OPERAND(loom_vector_bitfield_extracts_source, 0)
LOOM_DEFINE_RESULT(loom_vector_bitfield_extracts_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_extracts_offset, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_extracts_width, 1)
iree_status_t loom_vector_bitfield_extracts_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t source,
    int64_t offset,
    int64_t width,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitfield_extracts_vtable;
iree_status_t loom_vector_bitfield_extracts_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITFIELD_INSERT: Insert the low bits of each integer field lane into a fixed bitfield of each integer base lane.
// %packed = vector.bitfield.insert %lo into %zero {offset = 0, width = 4} : vector<16xi32>, vector<16xi8> -> vector<16xi8>
LOOM_DEFINE_ISA(loom_vector_bitfield_insert_isa, LOOM_OP_VECTOR_BITFIELD_INSERT)
LOOM_DEFINE_OPERAND(loom_vector_bitfield_insert_field, 0)
LOOM_DEFINE_OPERAND(loom_vector_bitfield_insert_base, 1)
LOOM_DEFINE_RESULT(loom_vector_bitfield_insert_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_insert_offset, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitfield_insert_width, 1)
iree_status_t loom_vector_bitfield_insert_build(
    loom_builder_t* builder,
    loom_may_consume loom_value_id_t field,
    loom_may_consume loom_value_id_t base,
    int64_t offset,
    int64_t width,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitfield_insert_vtable;
iree_status_t loom_vector_bitfield_insert_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITPACK: Pack the low bits of each integer source lane into a contiguous little-endian bitstream stored in integer result lanes.
// %packed = vector.bitpack<4> %codes : vector<32xi8> -> vector<16xi8>
LOOM_DEFINE_ISA(loom_vector_bitpack_isa, LOOM_OP_VECTOR_BITPACK)
LOOM_DEFINE_OPERAND(loom_vector_bitpack_source, 0)
LOOM_DEFINE_RESULT(loom_vector_bitpack_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitpack_width, 0)
iree_status_t loom_vector_bitpack_build(
    loom_builder_t* builder,
    int64_t width,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitpack_vtable;
iree_status_t loom_vector_bitpack_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITUNPACKU: Unpack unsigned fixed-width fields from a contiguous little-endian integer bitstream into zero-extended integer result lanes.
// %codes = vector.bitunpacku<4> %packed : vector<16xi8> -> vector<32xi8>
LOOM_DEFINE_ISA(loom_vector_bitunpacku_isa, LOOM_OP_VECTOR_BITUNPACKU)
LOOM_DEFINE_OPERAND(loom_vector_bitunpacku_source, 0)
LOOM_DEFINE_RESULT(loom_vector_bitunpacku_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitunpacku_width, 0)
iree_status_t loom_vector_bitunpacku_build(
    loom_builder_t* builder,
    int64_t width,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitunpacku_vtable;
iree_status_t loom_vector_bitunpacku_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_BITUNPACKS: Unpack signed fixed-width fields from a contiguous little-endian integer bitstream into sign-extended integer result lanes.
// %deltas = vector.bitunpacks<3> %packed : vector<12xi8> -> vector<32xi8>
LOOM_DEFINE_ISA(loom_vector_bitunpacks_isa, LOOM_OP_VECTOR_BITUNPACKS)
LOOM_DEFINE_OPERAND(loom_vector_bitunpacks_source, 0)
LOOM_DEFINE_RESULT(loom_vector_bitunpacks_result, 0)
LOOM_DEFINE_ATTR_I64(loom_vector_bitunpacks_width, 0)
iree_status_t loom_vector_bitunpacks_build(
    loom_builder_t* builder,
    int64_t width,
    loom_may_consume loom_value_id_t source,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_bitunpacks_vtable;
iree_status_t loom_vector_bitunpacks_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_DOT4I: Group adjacent four-lane i8 products into i32 accumulator lanes.
// %r = vector.dot4i<s8s8> %lhs, %rhs, %acc : vector<16xi8>, vector<16xi8>, vector<4xi32>
LOOM_DEFINE_ISA(loom_vector_dot4i_isa, LOOM_OP_VECTOR_DOT4I)
LOOM_DEFINE_OPERAND(loom_vector_dot4i_lhs, 0)
LOOM_DEFINE_OPERAND(loom_vector_dot4i_rhs, 1)
LOOM_DEFINE_OPERAND(loom_vector_dot4i_acc, 2)
LOOM_DEFINE_RESULT(loom_vector_dot4i_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_dot4i_kind, 0)
iree_status_t loom_vector_dot4i_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_value_id_t lhs,
    loom_value_id_t rhs,
    loom_value_id_t acc,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_dot4i_vtable;
iree_status_t loom_vector_dot4i_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// LOOM_OP_VECTOR_REDUCE: Reduce all lanes of a vector into a scalar accumulator/result.
// %sum = vector.reduce<addf> %v, %zero : vector<16xf32> -> f32
LOOM_DEFINE_ISA(loom_vector_reduce_isa, LOOM_OP_VECTOR_REDUCE)
LOOM_DEFINE_OPERAND(loom_vector_reduce_input, 0)
LOOM_DEFINE_OPERAND(loom_vector_reduce_init, 1)
LOOM_DEFINE_RESULT(loom_vector_reduce_result, 0)
LOOM_DEFINE_ATTR_ENUM(loom_vector_reduce_kind, 0)
iree_status_t loom_vector_reduce_build(
    loom_builder_t* builder,
    uint8_t kind,
    loom_may_consume loom_value_id_t input,
    loom_may_consume loom_value_id_t init,
    loom_type_t result_type,
    loom_location_id_t location,
    loom_op_t** out_op);
extern const loom_op_vtable_t loom_vector_reduce_vtable;
iree_status_t loom_vector_reduce_verify(
    const loom_module_t* module, const loom_op_t* op,
    iree_diagnostic_emitter_t emitter);

// Returns the vtable array for the vector dialect.
const loom_op_vtable_t* const* loom_vector_dialect_vtables(
    iree_host_size_t* out_count);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_VECTOR_OPS_H_
