# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Region, Type


class ViewBuilders:
    """Typed builder methods for view ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def dense(self, *, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Construct a dense row-major address layout. The consuming view type provides the rank and logical extents.

        Example::
            %layout = view.layout.dense : encoding
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        return cast(ValueRef, self._b.build("view.layout.dense", _operands, results=results, attributes=_attributes, regions=_regions))

    def strided(self, *, strides: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Construct an address layout from per-dimension element strides. Static and dynamic stride values are interleaved in one bracket list.

        Example::
            %layout = view.layout.strided [%row_stride, 1] : encoding
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _sentinel = -(2**63)
        _static = []
        for _idx in strides:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_strides"] = _static
        return cast(ValueRef, self._b.build("view.layout.strided", _operands, results=results, attributes=_attributes, regions=_regions))

    def subview(self, *, source: ValueRef, offsets: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Form a logical subview from an existing view. Offsets select the logical origin; result type dimensions provide the subview extents.

        Example::
            %sub = view.subview %source[%row, 0] : view<[%M]x[%N]xf32, %layout> -> view<16x[%N]xf32, %layout>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _sentinel = -(2**63)
        _static = []
        for _idx in offsets:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_offsets"] = _static
        return cast(ValueRef, self._b.build("view.subview", _operands, results=results, attributes=_attributes, regions=_regions))
