// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// clang-format off

    [LOOM_KW_COMMA] = (const uint8_t*)"\x01" ",",
    [LOOM_KW_COLON] = (const uint8_t*)"\x01" ":",
    [LOOM_KW_ARROW] = (const uint8_t*)"\x02" "->",
    [LOOM_KW_EQUALS] = (const uint8_t*)"\x01" "=",
    [LOOM_KW_LPAREN] = (const uint8_t*)"\x01" "(",
    [LOOM_KW_RPAREN] = (const uint8_t*)"\x01" ")",
    [LOOM_KW_LBRACKET] = (const uint8_t*)"\x01" "[",
    [LOOM_KW_RBRACKET] = (const uint8_t*)"\x01" "]",
    [LOOM_KW_LBRACE] = (const uint8_t*)"\x01" "{",
    [LOOM_KW_RBRACE] = (const uint8_t*)"\x01" "}",
    [LOOM_KW_TO] = (const uint8_t*)"\x02" "to",
    [LOOM_KW_STEP] = (const uint8_t*)"\x04" "step",
    [LOOM_KW_ELSE] = (const uint8_t*)"\x04" "else",
    [LOOM_KW_ITER_ARGS] = (const uint8_t*)"\x09" "iter_args",
    [LOOM_KW_WHERE] = (const uint8_t*)"\x05" "where",
    [LOOM_KW_AS] = (const uint8_t*)"\x02" "as",
    [LOOM_KW_PUBLIC] = (const uint8_t*)"\x06" "public",
    [LOOM_KW_HOST] = (const uint8_t*)"\x04" "host",
    [LOOM_KW_DEVICE] = (const uint8_t*)"\x06" "device",
    [LOOM_KW_PRIORITY] = (const uint8_t*)"\x08" "priority",
    [LOOM_KW_X] = (const uint8_t*)"\x01" "x",
    [LOOM_KW_IMPORT] = (const uint8_t*)"\x06" "import",
    [LOOM_KW_LAYOUT] = (const uint8_t*)"\x06" "layout",
    [LOOM_KW_INTO] = (const uint8_t*)"\x04" "into",
    [LOOM_KW_DEFAULT] = (const uint8_t*)"\x07" "default",
    [LOOM_KW_CASE] = (const uint8_t*)"\x04" "case",
    [LOOM_KW_DO] = (const uint8_t*)"\x02" "do",
    [LOOM_KW_USING] = (const uint8_t*)"\x05" "using",
    [LOOM_KW_DGROUPS] = (const uint8_t*)"\x07" "dgroups",
