// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// clang-format off

  LOOM_KW_COMMA = 0,  // ","
  LOOM_KW_COLON = 1,  // ":"
  LOOM_KW_ARROW = 2,  // "->"
  LOOM_KW_EQUALS = 3,  // "="
  LOOM_KW_LPAREN = 4,  // "("
  LOOM_KW_RPAREN = 5,  // ")"
  LOOM_KW_LBRACKET = 6,  // "["
  LOOM_KW_RBRACKET = 7,  // "]"
  LOOM_KW_LBRACE = 8,  // "{"
  LOOM_KW_RBRACE = 9,  // "}"
  LOOM_KW_TO = 10,  // "to"
  LOOM_KW_STEP = 11,  // "step"
  LOOM_KW_ELSE = 12,  // "else"
  LOOM_KW_ITER_ARGS = 13,  // "iter_args"
  LOOM_KW_WHERE = 14,  // "where"
  LOOM_KW_AS = 15,  // "as"
  LOOM_KW_PUBLIC = 16,  // "public"
  LOOM_KW_HOST = 17,  // "host"
  LOOM_KW_DEVICE = 18,  // "device"
  LOOM_KW_PRIORITY = 19,  // "priority"
  LOOM_KW_X = 20,  // "x"
  LOOM_KW_IMPORT = 21,  // "import"
  LOOM_KW_LAYOUT = 22,  // "layout"
  LOOM_KW_INTO = 23,  // "into"
