// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// GENERATED by loom.gen.c_tables — do not edit.
// clang-format off
#ifndef LOOM_OPS_OP_REGISTRY_H_
#define LOOM_OPS_OP_REGISTRY_H_

#include "iree/base/api.h"
#include "loom/ops/op_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

// Entry in the sorted op registry. Each entry maps a dotted name
// (e.g., "test.addi") to its op kind (enum value). The array is
// sorted lexicographically by name at code generation time so
// lookup is a binary search — no runtime sorting needed.
typedef struct loom_op_registry_entry_t {
  iree_string_view_t name;
  loom_op_kind_t kind;
} loom_op_registry_entry_t;

// Returns the number of entries in the global op registry.
iree_host_size_t loom_op_registry_count(void);

// Returns the sorted registry array (for iteration/testing).
const loom_op_registry_entry_t* loom_op_registry_entries(void);

// Looks up an op kind by dotted name (e.g., "test.addi").
// Returns true and sets *out_kind on success, false if not found.
bool loom_op_registry_lookup(iree_string_view_t name,
                             loom_op_kind_t* out_kind);

#ifdef __cplusplus
}
#endif

#endif  // LOOM_OPS_OP_REGISTRY_H_
