# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Region, Type


class VectorBuilders:
    """Typed builder methods for vector ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def constant(self, *, value: Any, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Materialize a compile-time splat constant vector value.

        Example::
            %v = vector.constant 0.0 : vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("vector.constant", _operands, results=results, attributes=_attributes, regions=_regions))

    def splat(self, *, scalar: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Replicate one scalar value to every lane of a vector result.

        Example::
            %vec = vector.splat %scalar : f32 -> vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(scalar)
        return cast(ValueRef, self._b.build("vector.splat", _operands, results=results, attributes=_attributes, regions=_regions))

    def broadcast(self, *, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Broadcast a vector value to a vector result with a compatible shape.

        Example::
            %wide = vector.broadcast %v : vector<4xf32> -> vector<16x4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.broadcast", _operands, results=results, attributes=_attributes, regions=_regions))

    def from_elements(self, *, elements: list[ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Build a vector from scalar element operands in lane order.

        Example::
            %v = vector.from_elements %a, %b, %c, %d : f32, f32, f32, f32 -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(elements)
        return cast(ValueRef, self._b.build("vector.from_elements", _operands, results=results, attributes=_attributes, regions=_regions))

    def extract(self, *, source: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract a scalar or subvector from a vector at explicit indices.

        Example::
            %x = vector.extract %v[%i] : vector<[%n]xf32> -> f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.extract", _operands, results=results, attributes=_attributes, regions=_regions))

    def insert(self, *, value: ValueRef, dest: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Insert a scalar or subvector into a vector at explicit indices.

        Example::
            %r = vector.insert %x into %v[%i] : f32, vector<[%n]xf32> -> vector<[%n]xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(dest)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.insert", _operands, results=results, attributes=_attributes, regions=_regions))

    def load(self, *, view: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Load a vector footprint from a typed view at a full-rank logical origin.

        Example::
            %v = vector.load %view[%row, %col] : view<[%m]x[%n]xf32, %layout> -> vector<4x8xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.load", _operands, results=results, attributes=_attributes, regions=_regions))

    def store(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef]) -> None:
        """Store a vector footprint into a typed view at a full-rank logical origin.

        Example::
            vector.store %v, %view[%row, %col] : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.store", _operands, attributes=_attributes, regions=_regions)

    def load_mask(self, *, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef, passthrough: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Masked vector load from a typed view; masked-off lanes take the passthrough value.

        Example::
            %v = vector.load.mask %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>, vector<4x8xf32> -> vector<4x8xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _operands.append(mask)
        _operands.append(passthrough)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.load.mask", _operands, results=results, attributes=_attributes, regions=_regions))

    def store_mask(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef) -> None:
        """Masked vector store into a typed view; masked-off lanes leave memory unchanged.

        Example::
            vector.store.mask %v, %view[%row, %col], %mask : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _operands.append(mask)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.store.mask", _operands, attributes=_attributes, regions=_regions)

    def select(self, *, condition: ValueRef, true_value: ValueRef, false_value: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise select from two same-typed vector values using an i1 mask vector.

        Example::
            %r = vector.select %mask, %a, %b : vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(condition)
        _operands.append(true_value)
        _operands.append(false_value)
        return cast(ValueRef, self._b.build("vector.select", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cmpi(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Lanewise integer comparison producing an i1 mask vector.

        Example::
            %m = vector.cmpi slt, %lhs, %rhs : vector<16xi32> -> vector<16xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.cmpi", _operands, results=results, attributes=_attributes, regions=_regions))

    def cmpf(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Lanewise floating-point comparison producing an i1 mask vector.

        Example::
            %m = vector.cmpf olt, %lhs, %rhs : vector<16xf32> -> vector<16xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.cmpf", _operands, results=results, attributes=_attributes, regions=_regions))

    def addf(self, *, assumptions: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point addition."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.addf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def mulf(self, *, assumptions: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point multiplication."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.mulf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fmaf(self, *, assumptions: str | None = None, a: ValueRef, b: ValueRef, c: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise fused multiply-add: a*b + c with single rounding.

        Example::
            %r = vector.fmaf %a, %b, %c : vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(a)
        _operands.append(b)
        _operands.append(c)
        return cast(ValueRef, self._b.build("vector.fmaf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def addi(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer addition."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.addi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def muli(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer multiplication."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.muli", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sqrtf(self, *, assumptions: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise square root."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.sqrtf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extf(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point precision extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptrunc(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point precision truncation."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptrunc", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extsi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise signed integer extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise unsigned integer extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def trunci(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer truncation."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.trunci", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise signed integer to floating-point conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.sitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def uitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise unsigned integer to floating-point conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.uitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptosi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point to signed integer conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptosi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptoui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point to unsigned integer conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptoui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def bitcast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise bit reinterpretation between same-shaped vector types.

        Example::
            %r = vector.bitcast %input : vector<16xf32> to vector<16xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.bitcast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def reduce(self, *, kind: str, input: ValueRef, init: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Reduce all lanes of a vector into a scalar accumulator/result.

        Example::
            %sum = vector.reduce<addf> %v, %zero : vector<16xf32> -> f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _operands.append(input)
        _operands.append(init)
        return cast(ValueRef, self._b.build("vector.reduce", _operands, results=results, attributes=_attributes, regions=_regions))
