# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, TiedResultSpec, ValueRef
from loom.ir import Region, Type


class VectorBuilders:
    """Typed builder methods for vector ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def constant(self, *, value: Any, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Materialize a compile-time splat constant vector value.

        Example::
            %v = vector.constant 0.0 : vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("vector.constant", _operands, results=results, attributes=_attributes, regions=_regions))

    def splat(self, *, scalar: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Replicate one scalar value to every lane of a vector result.

        Example::
            %vec = vector.splat %scalar : f32 -> vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(scalar)
        return cast(ValueRef, self._b.build("vector.splat", _operands, results=results, attributes=_attributes, regions=_regions))

    def broadcast(self, *, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Broadcast a vector value to a vector result with a compatible shape.

        Example::
            %wide = vector.broadcast %v : vector<4xf32> -> vector<16x4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.broadcast", _operands, results=results, attributes=_attributes, regions=_regions))

    def from_elements(self, *, elements: list[ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Build a vector from scalar element operands in lane order.

        Example::
            %v = vector.from_elements %a, %b, %c, %d : f32, f32, f32, f32 -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.extend(elements)
        return cast(ValueRef, self._b.build("vector.from_elements", _operands, results=results, attributes=_attributes, regions=_regions))

    def extract(self, *, source: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract a scalar or subvector from a vector at explicit indices.

        Example::
            %x = vector.extract %v[%i] : vector<[%n]xf32> -> f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.extract", _operands, results=results, attributes=_attributes, regions=_regions))

    def insert(self, *, value: ValueRef, dest: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Insert a scalar or subvector into a vector at explicit indices.

        Example::
            %r = vector.insert %x into %v[%i] : f32, vector<[%n]xf32> -> vector<[%n]xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(dest)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.insert", _operands, results=results, attributes=_attributes, regions=_regions))

    def slice(self, *, source: ValueRef, offsets: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract a rank-preserving contiguous register subvector at explicit offsets.

        Example::
            %tail = vector.slice %v[%i] : vector<[%n]xf32> -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(source)
        _sentinel = -(2**63)
        _static = []
        for _idx in offsets:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_offsets"] = _static
        return cast(ValueRef, self._b.build("vector.slice", _operands, results=results, attributes=_attributes, regions=_regions))

    def concat(self, *, axis: int, inputs: list[ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Concatenate same-rank vectors along one explicit result axis.

        Example::
            %wide = vector.concat<0> %a, %b : vector<4xf32>, vector<4xf32> -> vector<8xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["axis"] = axis
        _operands.extend(inputs)
        return cast(ValueRef, self._b.build("vector.concat", _operands, results=results, attributes=_attributes, regions=_regions))

    def transpose(self, *, permutation: list[int], source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Reorder vector register axes using an explicit result-axis to source-axis permutation.

        Example::
            %t = vector.transpose<[1, 0]> %v : vector<4x8xf32> -> vector<8x4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["permutation"] = permutation
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.transpose", _operands, results=results, attributes=_attributes, regions=_regions))

    def shuffle(self, *, source_lanes: list[int], source: ValueRef, result_types: list[Type]) -> ValueRef:
        """Build a same-typed rank-1 vector by selecting source register lanes with a static lane map; duplicate lanes are allowed.

        Example::
            %rev = vector.shuffle<[3, 2, 1, 0]> %v : vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["source_lanes"] = source_lanes
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.shuffle", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def interleave(self, *, axis: int, even: ValueRef, odd: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Interleave two same-typed vectors along one axis; even lanes come from the first operand and odd lanes come from the second operand.

        Example::
            %r = vector.interleave<0> %lo, %hi : vector<16xi8>, vector<16xi8> -> vector<32xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["axis"] = axis
        _operands.append(even)
        _operands.append(odd)
        return cast(ValueRef, self._b.build("vector.interleave", _operands, results=results, attributes=_attributes, regions=_regions))

    def deinterleave(self, *, axis: int, source: ValueRef, results: list[Type | TiedResultSpec]) -> list[ValueRef]:
        """Split one vector along an axis into even-position and odd-position vectors of the same type.

        Example::
            %lo, %hi = vector.deinterleave<0> %r : vector<32xi8> -> vector<16xi8>, vector<16xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["axis"] = axis
        _operands.append(source)
        return cast(list[ValueRef], self._b.build("vector.deinterleave", _operands, results=results, attributes=_attributes, regions=_regions))

    def lookup(self, *, table: ValueRef, indices: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Select table vector lanes using explicit integer index lanes; every index lane must be within the table extent.

        Example::
            %values = vector.table.lookup %grid[%codes] : vector<16xf16>, vector<32xi8> -> vector<32xf16>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(table)
        _operands.append(indices)
        return cast(ValueRef, self._b.build("vector.table.lookup", _operands, results=results, attributes=_attributes, regions=_regions))

    def load(self, *, view: ValueRef, indices: list[int | ValueRef], results: list[Type | TiedResultSpec]) -> ValueRef:
        """Load a vector footprint from a typed view at a full-rank logical origin.

        Example::
            %v = vector.load %view[%row, %col] : view<[%m]x[%n]xf32, %layout> -> vector<4x8xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.load", _operands, results=results, attributes=_attributes, regions=_regions))

    def store(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef]) -> None:
        """Store a vector footprint into a typed view at a full-rank logical origin.

        Example::
            vector.store %v, %view[%row, %col] : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.store", _operands, attributes=_attributes, regions=_regions)

    def load_mask(self, *, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef, passthrough: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Masked vector load from a typed view; masked-off lanes take the passthrough value.

        Example::
            %v = vector.load.mask %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>, vector<4x8xf32> -> vector<4x8xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _operands.append(mask)
        _operands.append(passthrough)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.load.mask", _operands, results=results, attributes=_attributes, regions=_regions))

    def store_mask(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef) -> None:
        """Masked vector store into a typed view; masked-off lanes leave memory unchanged.

        Example::
            vector.store.mask %v, %view[%row, %col], %mask : vector<4x8xf32>, view<[%m]x[%n]xf32, %layout>, vector<4x8xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _operands.append(mask)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.store.mask", _operands, attributes=_attributes, regions=_regions)

    def expand(self, *, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef, passthrough: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Rank-1 masked expand load from consecutive view elements; active lanes consume memory in increasing lane order and inactive lanes take the passthrough value.

        Example::
            %v = vector.load.expand %view[%row, %col], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _operands.append(mask)
        _operands.append(passthrough)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.load.expand", _operands, results=results, attributes=_attributes, regions=_regions))

    def compress(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], mask: ValueRef) -> None:
        """Rank-1 masked compress store to consecutive view elements; active lanes produce memory in increasing lane order and inactive lanes do not write.

        Example::
            vector.store.compress %v, %view[%row, %col], %mask : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _operands.append(mask)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.store.compress", _operands, attributes=_attributes, regions=_regions)

    def gather(self, *, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Gather a vector from per-lane signed element offsets relative to a full-rank view origin.

        Example::
            %v = vector.gather %view[%row, %col][%offsets] : view<[%m]x[%n]xf32, %layout>, vector<4xindex> -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _operands.append(offsets)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.gather", _operands, results=results, attributes=_attributes, regions=_regions))

    def scatter(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef) -> None:
        """Non-atomic scatter of a vector to per-lane signed element offsets relative to a full-rank view origin; active lane addresses must be distinct.

        Example::
            vector.scatter %v, %view[%row, %col][%offsets] : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.scatter", _operands, attributes=_attributes, regions=_regions)

    def gather_mask(self, *, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, mask: ValueRef, passthrough: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Masked vector gather from per-lane signed element offsets; masked-off lanes take the passthrough value.

        Example::
            %v = vector.gather.mask %view[%row, %col][%offsets], %mask, %old : view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(view)
        _operands.append(offsets)
        _operands.append(mask)
        _operands.append(passthrough)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.gather.mask", _operands, results=results, attributes=_attributes, regions=_regions))

    def scatter_mask(self, *, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, mask: ValueRef) -> None:
        """Masked non-atomic scatter; masked-off lanes leave memory unchanged and active lane addresses must be distinct.

        Example::
            vector.scatter.mask %v, %view[%row, %col][%offsets], %mask : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _operands.append(mask)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.scatter.mask", _operands, attributes=_attributes, regions=_regions)

    def atomic_reduce(self, *, kind: str, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, ordering: str, scope: str) -> None:
        """Atomic no-result scatter reduction/update into per-lane signed element offsets. Duplicate active lane addresses are allowed and are serialized by the atomic memory contract.

        Example::
            vector.atomic.reduce<addi> %v, %view[%row, %col][%offsets] {ordering = relaxed, scope = workgroup} : vector<4xi32>, view<[%m]x[%n]xi32, %layout>, vector<4xindex>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _attributes["ordering"] = ordering
        _attributes["scope"] = scope
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.atomic.reduce", _operands, attributes=_attributes, regions=_regions)

    def atomic_reduce_mask(self, *, kind: str, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, mask: ValueRef, ordering: str, scope: str) -> None:
        """Masked atomic no-result scatter reduction/update; masked-off lanes do not access memory.

        Example::
            vector.atomic.reduce.mask<addf> %v, %view[%row, %col][%offsets], %mask {ordering = relaxed, scope = device} : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _attributes["ordering"] = ordering
        _attributes["scope"] = scope
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _operands.append(mask)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        self._b.build("vector.atomic.reduce.mask", _operands, attributes=_attributes, regions=_regions)

    def rmw(self, *, kind: str, value: ValueRef, view: ValueRef, indices: list[int | ValueRef], offsets: ValueRef, ordering: str, scope: str, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Atomic read-modify-write at per-lane signed element offsets, returning the old memory value for each lane.

        Example::
            %old = vector.atomic.rmw<addi> %v, %view[%row, %col][%offsets] {ordering = relaxed, scope = workgroup} : vector<4xi32>, view<[%m]x[%n]xi32, %layout>, vector<4xindex> -> vector<4xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _attributes["ordering"] = ordering
        _attributes["scope"] = scope
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.atomic.rmw", _operands, results=results, attributes=_attributes, regions=_regions))

    def atomic_rmw_mask(
        self,
        *,
        kind: str,
        value: ValueRef,
        view: ValueRef,
        indices: list[int | ValueRef],
        offsets: ValueRef,
        mask: ValueRef,
        passthrough: ValueRef,
        ordering: str,
        scope: str,
        results: list[Type | TiedResultSpec],
    ) -> ValueRef:
        """Masked atomic read-modify-write. Masked-off result lanes take the explicit passthrough value.

        Example::
            %old = vector.atomic.rmw.mask<addf> %v, %view[%row, %col][%offsets], %mask, %passthrough {ordering = relaxed, scope = device} : vector<4xf32>, view<[%m]x[%n]xf32, %layout>, vector<4xindex>, vector<4xi1>, vector<4xf32> -> vector<4xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _attributes["ordering"] = ordering
        _attributes["scope"] = scope
        _operands.append(value)
        _operands.append(view)
        _operands.append(offsets)
        _operands.append(mask)
        _operands.append(passthrough)
        _sentinel = -(2**63)
        _static = []
        for _idx in indices:
            if isinstance(_idx, ValueRef):
                _static.append(_sentinel)
                _operands.append(_idx)
            else:
                _static.append(_idx)
        _attributes["static_indices"] = _static
        return cast(ValueRef, self._b.build("vector.atomic.rmw.mask", _operands, results=results, attributes=_attributes, regions=_regions))

    def select(self, *, condition: ValueRef, true_value: ValueRef, false_value: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise select from two same-typed vector values using an i1 mask vector.

        Example::
            %r = vector.select %mask, %a, %b : vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(condition)
        _operands.append(true_value)
        _operands.append(false_value)
        return cast(ValueRef, self._b.build("vector.select", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cmpi(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Lanewise integer comparison producing an i1 mask vector.

        Example::
            %m = vector.cmpi slt, %lhs, %rhs : vector<16xi32> -> vector<16xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.cmpi", _operands, results=results, attributes=_attributes, regions=_regions))

    def cmpf(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Lanewise floating-point comparison producing an i1 mask vector.

        Example::
            %m = vector.cmpf olt, %lhs, %rhs : vector<16xf32> -> vector<16xi1>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.cmpf", _operands, results=results, attributes=_attributes, regions=_regions))

    def addf(self, *, assumptions: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point addition."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.addf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def mulf(self, *, assumptions: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point multiplication."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.mulf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fmaf(self, *, assumptions: str | None = None, a: ValueRef, b: ValueRef, c: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise fused multiply-add: a*b + c with single rounding.

        Example::
            %r = vector.fmaf %a, %b, %c : vector<16xf32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(a)
        _operands.append(b)
        _operands.append(c)
        return cast(ValueRef, self._b.build("vector.fmaf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def addi(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer addition."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.addi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def muli(self, *, overflow: str | None = None, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer multiplication."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if overflow is not None:
            _attributes["overflow"] = overflow
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("vector.muli", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sqrtf(self, *, assumptions: str | None = None, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise square root."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        if assumptions is not None:
            _attributes["assumptions"] = assumptions
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.sqrtf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extf(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point precision extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extf", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptrunc(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point precision truncation."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptrunc", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extsi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise signed integer extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extsi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise unsigned integer extension."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.extui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def trunci(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise integer truncation."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.trunci", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise signed integer to floating-point conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.sitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def uitofp(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise unsigned integer to floating-point conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.uitofp", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptosi(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point to signed integer conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptosi", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def fptoui(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Lanewise floating-point to unsigned integer conversion."""
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.fptoui", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def bitcast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Bitwise reinterpretation between vector register types with the same total bit count.

        Example::
            %r = vector.bitcast %input : vector<16xf32> to vector<16xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("vector.bitcast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def extractu(self, *, source: ValueRef, offset: int, width: int, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract and zero-extend one fixed bitfield from each integer source lane.

        Example::
            %lo = vector.bitfield.extractu %bytes {offset = 0, width = 4} : vector<16xi8> -> vector<16xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["offset"] = offset
        _attributes["width"] = width
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.bitfield.extractu", _operands, results=results, attributes=_attributes, regions=_regions))

    def extracts(self, *, source: ValueRef, offset: int, width: int, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Extract and sign-extend one fixed bitfield from each integer source lane.

        Example::
            %signed = vector.bitfield.extracts %bytes {offset = 4, width = 4} : vector<16xi8> -> vector<16xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["offset"] = offset
        _attributes["width"] = width
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.bitfield.extracts", _operands, results=results, attributes=_attributes, regions=_regions))

    def bitfield_insert(self, *, field: ValueRef, base: ValueRef, offset: int, width: int, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Insert the low bits of each integer field lane into a fixed bitfield of each integer base lane.

        Example::
            %packed = vector.bitfield.insert %lo into %zero {offset = 0, width = 4} : vector<16xi32>, vector<16xi8> -> vector<16xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["offset"] = offset
        _attributes["width"] = width
        _operands.append(field)
        _operands.append(base)
        return cast(ValueRef, self._b.build("vector.bitfield.insert", _operands, results=results, attributes=_attributes, regions=_regions))

    def bitpack(self, *, width: int, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Pack the low bits of each integer source lane into a contiguous little-endian bitstream stored in integer result lanes.

        Example::
            %packed = vector.bitpack<4> %codes : vector<32xi8> -> vector<16xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["width"] = width
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.bitpack", _operands, results=results, attributes=_attributes, regions=_regions))

    def bitunpacku(self, *, width: int, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Unpack unsigned fixed-width fields from a contiguous little-endian integer bitstream into zero-extended integer result lanes.

        Example::
            %codes = vector.bitunpacku<4> %packed : vector<16xi8> -> vector<32xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["width"] = width
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.bitunpacku", _operands, results=results, attributes=_attributes, regions=_regions))

    def bitunpacks(self, *, width: int, source: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Unpack signed fixed-width fields from a contiguous little-endian integer bitstream into sign-extended integer result lanes.

        Example::
            %deltas = vector.bitunpacks<3> %packed : vector<12xi8> -> vector<32xi8>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["width"] = width
        _operands.append(source)
        return cast(ValueRef, self._b.build("vector.bitunpacks", _operands, results=results, attributes=_attributes, regions=_regions))

    def dot4i(self, *, kind: str, lhs: ValueRef, rhs: ValueRef, acc: ValueRef, result_types: list[Type]) -> ValueRef:
        """Group adjacent four-lane i8 products into i32 accumulator lanes.

        Example::
            %r = vector.dot4i<s8s8> %lhs, %rhs, %acc : vector<16xi8>, vector<16xi8>, vector<4xi32>
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _operands.append(lhs)
        _operands.append(rhs)
        _operands.append(acc)
        return cast(ValueRef, self._b.build("vector.dot4i", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def reduce(self, *, kind: str, input: ValueRef, init: ValueRef, results: list[Type | TiedResultSpec]) -> ValueRef:
        """Reduce all lanes of a vector into a scalar accumulator/result.

        Example::
            %sum = vector.reduce<addf> %v, %zero : vector<16xf32> -> f32
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["kind"] = kind
        _operands.append(input)
        _operands.append(init)
        return cast(ValueRef, self._b.build("vector.reduce", _operands, results=results, attributes=_attributes, regions=_regions))
