# GENERATED by loom.gen.builders — do not edit.
#
# Regenerate with: python3 loom/py/loom/gen/run.py builders

from __future__ import annotations

import builtins
from typing import Any, cast

from loom.builder import IRBuilder, ValueRef
from loom.ir import Predicate, Region, Type


class IndexBuilders:
    """Typed builder methods for index ops."""

    __test__ = False

    def __init__(self, builder: IRBuilder) -> None:
        self._b = builder

    def constant(self, *, value: Any, result_types: list[Type]) -> ValueRef:
        """Materialize a compile-time address-domain constant. The result type must be index for logical coordinates or offset for physical byte counts; fixed-width integer payload constants remain scalar.constant.

        Example::
            %c0 = index.constant 0 : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["value"] = value
        return cast(ValueRef, self._b.build("index.constant", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cast(self, *, input: ValueRef, result_types: list[Type]) -> ValueRef:
        """Explicit conversion at an address boundary. At least one side must be index or offset; pure integer width changes use scalar.extsi, scalar.extui, or scalar.trunci.

        Example::
            %i = index.cast %n : i64 to index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(input)
        return cast(ValueRef, self._b.build("index.cast", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def assume(self, *, values: list[ValueRef], predicates: list[Predicate], result_types: list[Type]) -> list[ValueRef]:
        """Identity with predicate constraints on index or offset results.

        Example::
            %n2 = index.assume %n [mul(%n, 16)] : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicates"] = predicates
        _operands.extend(values)
        return cast(list[ValueRef], self._b.build("index.assume", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def add(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Address-domain addition. Operands and result must all be index or all offset.

        Example::
            %r = index.add %lhs, %rhs : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.add", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def sub(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Address-domain subtraction. Operands and result must all be index or all offset.

        Example::
            %r = index.sub %lhs, %rhs : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.sub", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def mul(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Logical coordinate multiplication. Offsets are physical byte counts and cannot be multiplied with this op.

        Example::
            %r = index.mul %lhs, %rhs : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.mul", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def div(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Logical coordinate quotient for non-negative index values with a positive divisor. Offsets are physical byte counts and cannot be divided with this op; use an explicit layout or storage mapping before deriving physical address pieces.

        Example::
            %q = index.div %lane, %group_size : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.div", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def rem(self, *, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Logical coordinate remainder for non-negative index values with a positive divisor. Offsets are physical byte counts and cannot use remainder with this op; use an explicit layout or storage mapping before deriving physical address pieces.

        Example::
            %r = index.rem %lane, %group_size : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.rem", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def madd(self, *, a: ValueRef, b: ValueRef, c: ValueRef, result_types: list[Type]) -> ValueRef:
        """Logical coordinate multiply-add: a*b + c. Offsets are physical byte counts and cannot be multiplied with this op.

        Example::
            %r = index.madd %a, %b, %c : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _operands.append(a)
        _operands.append(b)
        _operands.append(c)
        return cast(ValueRef, self._b.build("index.madd", _operands, results=result_types, attributes=_attributes, regions=_regions))

    def cmp(self, *, predicate: str, lhs: ValueRef, rhs: ValueRef, result_types: list[Type]) -> ValueRef:
        """Address-domain comparison. Operands must both be index or both be offset.

        Example::
            %p = index.cmp slt, %i, %n : index
        """
        _operands: list[ValueRef | int] = []
        _attributes: builtins.dict[str, Any] = {}
        _regions: list[Region] = []
        _attributes["predicate"] = predicate
        _operands.append(lhs)
        _operands.append(rhs)
        return cast(ValueRef, self._b.build("index.cmp", _operands, results=result_types, attributes=_attributes, regions=_regions))
